import { BCSCLoadingProvider } from '@/bcsc-theme/contexts/BCSCLoadingContext'
import { fireEvent, render, waitFor } from '@testing-library/react-native'
import React from 'react'
import { setPIN, verifyPIN } from 'react-native-bcsc-core'

import { BasicAppContext } from '../../../../../__mocks__/helpers/app'
import { ChangePINForm } from './ChangePINForm'

jest.mock('react-native-bcsc-core', () => ({
  setPIN: jest.fn(),
  verifyPIN: jest.fn(),
}))

const mockSetPIN = jest.mocked(setPIN)
const mockVerifyPIN = jest.mocked(verifyPIN)

describe('ChangePINForm', () => {
  const mockOnSuccess = jest.fn()

  beforeEach(() => {
    jest.clearAllMocks()
  })

  it('renders correctly with all PIN fields', () => {
    const tree = render(
      <BasicAppContext>
        <BCSCLoadingProvider>
          <ChangePINForm onSuccess={mockOnSuccess} />
        </BCSCLoadingProvider>
      </BasicAppContext>
    )

    expect(tree.getByText('BCSC.ChangePIN.EnterCurrentPIN')).toBeTruthy()
    expect(tree.getByText('BCSC.ChangePIN.EnterNewPIN')).toBeTruthy()
    expect(tree.getByText('BCSC.ChangePIN.ReenterNewPIN')).toBeTruthy()
    expect(tree.getByText('BCSC.ChangePIN.RememberPIN')).toBeTruthy()
    expect(tree.getByText('BCSC.ChangePIN.RememberPINDescription')).toBeTruthy()
    expect(tree).toMatchSnapshot()
  })

  it('shows checkbox acknowledgment', () => {
    const tree = render(
      <BasicAppContext>
        <BCSCLoadingProvider>
          <ChangePINForm onSuccess={mockOnSuccess} />
        </BCSCLoadingProvider>
      </BasicAppContext>
    )

    expect(tree.getByText('BCSC.ChangePIN.IUnderstand')).toBeTruthy()
  })

  it('shows Change PIN button', () => {
    const tree = render(
      <BasicAppContext>
        <BCSCLoadingProvider>
          <ChangePINForm onSuccess={mockOnSuccess} />
        </BCSCLoadingProvider>
      </BasicAppContext>
    )

    expect(tree.getByText('BCSC.ChangePIN.ButtonTitle')).toBeTruthy()
  })

  it('button is disabled when PINs are not entered and checkbox unchecked', () => {
    const tree = render(
      <BasicAppContext>
        <BCSCLoadingProvider>
          <ChangePINForm onSuccess={mockOnSuccess} />
        </BCSCLoadingProvider>
      </BasicAppContext>
    )

    const button = tree.getByTestId('com.ariesbifold:id/ChangePIN')
    expect(button.props.accessibilityState.disabled).toBe(true)
  })

  it('validates current PIN is verified before changing', async () => {
    mockVerifyPIN.mockResolvedValue({
      success: false,
      locked: false,
      remainingTime: 0,
      message: 'Incorrect PIN',
    })

    const tree = render(
      <BasicAppContext>
        <BCSCLoadingProvider>
          <ChangePINForm onSuccess={mockOnSuccess} />
        </BCSCLoadingProvider>
      </BasicAppContext>
    )

    // Find and fill the PIN inputs
    const inputs = tree.getAllByAccessibilityHint('Enter your 6-digit PIN')
    expect(inputs).toHaveLength(3) // Current, New, Confirm

    // Fill all inputs
    fireEvent.changeText(inputs[0], '123456')
    fireEvent.changeText(inputs[1], '654321')
    fireEvent.changeText(inputs[2], '654321')

    // Check the checkbox
    const checkbox = tree.getByTestId('com.ariesbifold:id/IUnderstand')
    fireEvent.press(checkbox)

    // Press the button
    const button = tree.getByTestId('com.ariesbifold:id/ChangePIN')
    fireEvent.press(button)

    await waitFor(() => {
      expect(mockVerifyPIN).toHaveBeenCalledWith('123456')
    })

    // Should NOT call setPIN if verification fails
    expect(mockSetPIN).not.toHaveBeenCalled()
  })

  it('calls onSuccess when PIN change is successful', async () => {
    mockVerifyPIN.mockResolvedValue({
      success: true,
      locked: false,
      remainingTime: 0,
      walletKey: 'test-wallet-key',
    })
    mockSetPIN.mockResolvedValue({
      success: true,
      walletKey: 'new-wallet-key',
      isAutoGenerated: false,
    })

    const tree = render(
      <BasicAppContext>
        <BCSCLoadingProvider>
          <ChangePINForm onSuccess={mockOnSuccess} />
        </BCSCLoadingProvider>
      </BasicAppContext>
    )

    const inputs = tree.getAllByAccessibilityHint('Enter your 6-digit PIN')
    fireEvent.changeText(inputs[0], '123456')
    fireEvent.changeText(inputs[1], '654321')
    fireEvent.changeText(inputs[2], '654321')

    const checkbox = tree.getByTestId('com.ariesbifold:id/IUnderstand')
    fireEvent.press(checkbox)

    const button = tree.getByTestId('com.ariesbifold:id/ChangePIN')
    fireEvent.press(button)

    await waitFor(() => {
      expect(mockVerifyPIN).toHaveBeenCalledWith('123456')
      expect(mockSetPIN).toHaveBeenCalledWith('654321')
      expect(mockOnSuccess).toHaveBeenCalled()
    })
  })

  it('shows error when PINs do not match', async () => {
    const tree = render(
      <BasicAppContext>
        <BCSCLoadingProvider>
          <ChangePINForm onSuccess={mockOnSuccess} />
        </BCSCLoadingProvider>
      </BasicAppContext>
    )

    const inputs = tree.getAllByAccessibilityHint('Enter your 6-digit PIN')
    fireEvent.changeText(inputs[0], '123456')
    fireEvent.changeText(inputs[1], '654321')
    fireEvent.changeText(inputs[2], '111111') // Different

    const checkbox = tree.getByTestId('com.ariesbifold:id/IUnderstand')
    fireEvent.press(checkbox)

    const button = tree.getByTestId('com.ariesbifold:id/ChangePIN')
    fireEvent.press(button)

    await waitFor(() => {
      expect(tree.getByText('BCSC.ChangePIN.PINsDoNotMatch')).toBeTruthy()
    })

    expect(mockVerifyPIN).not.toHaveBeenCalled()
  })

  it('disables button when current PIN is too short', async () => {
    const tree = render(
      <BasicAppContext>
        <BCSCLoadingProvider>
          <ChangePINForm onSuccess={mockOnSuccess} />
        </BCSCLoadingProvider>
      </BasicAppContext>
    )

    const inputs = tree.getAllByAccessibilityHint('Enter your 6-digit PIN')
    fireEvent.changeText(inputs[0], '123') // Too short
    fireEvent.changeText(inputs[1], '654321')
    fireEvent.changeText(inputs[2], '654321')

    const checkbox = tree.getByTestId('com.ariesbifold:id/IUnderstand')
    fireEvent.press(checkbox)

    const button = tree.getByTestId('com.ariesbifold:id/ChangePIN')
    expect(button.props.accessibilityState.disabled).toBe(true)

    expect(mockVerifyPIN).not.toHaveBeenCalled()
  })

  it('disables button when new PIN is too short', async () => {
    const tree = render(
      <BasicAppContext>
        <BCSCLoadingProvider>
          <ChangePINForm onSuccess={mockOnSuccess} />
        </BCSCLoadingProvider>
      </BasicAppContext>
    )

    const inputs = tree.getAllByAccessibilityHint('Enter your 6-digit PIN')
    fireEvent.changeText(inputs[0], '123456')
    fireEvent.changeText(inputs[1], '123') // Too short
    fireEvent.changeText(inputs[2], '654321')

    const checkbox = tree.getByTestId('com.ariesbifold:id/IUnderstand')
    fireEvent.press(checkbox)

    const button = tree.getByTestId('com.ariesbifold:id/ChangePIN')
    expect(button.props.accessibilityState.disabled).toBe(true)

    expect(mockVerifyPIN).not.toHaveBeenCalled()
  })

  it('disables button when confirm PIN is too short', async () => {
    const tree = render(
      <BasicAppContext>
        <BCSCLoadingProvider>
          <ChangePINForm onSuccess={mockOnSuccess} />
        </BCSCLoadingProvider>
      </BasicAppContext>
    )

    const inputs = tree.getAllByAccessibilityHint('Enter your 6-digit PIN')
    fireEvent.changeText(inputs[0], '123456')
    fireEvent.changeText(inputs[1], '654321')
    fireEvent.changeText(inputs[2], '123') // Too short

    const checkbox = tree.getByTestId('com.ariesbifold:id/IUnderstand')
    fireEvent.press(checkbox)

    const button = tree.getByTestId('com.ariesbifold:id/ChangePIN')
    expect(button.props.accessibilityState.disabled).toBe(true)

    expect(mockVerifyPIN).not.toHaveBeenCalled()
  })

  it('shows account locked message when verify returns locked', async () => {
    mockVerifyPIN.mockResolvedValue({
      success: false,
      locked: true,
      remainingTime: 300,
      message: 'Account is locked for 5 minutes',
    })

    const tree = render(
      <BasicAppContext>
        <BCSCLoadingProvider>
          <ChangePINForm onSuccess={mockOnSuccess} />
        </BCSCLoadingProvider>
      </BasicAppContext>
    )

    const inputs = tree.getAllByAccessibilityHint('Enter your 6-digit PIN')
    fireEvent.changeText(inputs[0], '123456')
    fireEvent.changeText(inputs[1], '654321')
    fireEvent.changeText(inputs[2], '654321')

    const checkbox = tree.getByTestId('com.ariesbifold:id/IUnderstand')
    fireEvent.press(checkbox)

    const button = tree.getByTestId('com.ariesbifold:id/ChangePIN')
    fireEvent.press(button)

    await waitFor(() => {
      expect(mockVerifyPIN).toHaveBeenCalledWith('123456')
      expect(tree.getByText('Account is locked for 5 minutes')).toBeTruthy()
    })

    expect(mockSetPIN).not.toHaveBeenCalled()
  })

  it('shows default locked message when verify returns locked without message', async () => {
    mockVerifyPIN.mockResolvedValue({
      success: false,
      locked: true,
      remainingTime: 300,
      message: '',
    })

    const tree = render(
      <BasicAppContext>
        <BCSCLoadingProvider>
          <ChangePINForm onSuccess={mockOnSuccess} />
        </BCSCLoadingProvider>
      </BasicAppContext>
    )

    const inputs = tree.getAllByAccessibilityHint('Enter your 6-digit PIN')
    fireEvent.changeText(inputs[0], '123456')
    fireEvent.changeText(inputs[1], '654321')
    fireEvent.changeText(inputs[2], '654321')

    const checkbox = tree.getByTestId('com.ariesbifold:id/IUnderstand')
    fireEvent.press(checkbox)

    const button = tree.getByTestId('com.ariesbifold:id/ChangePIN')
    fireEvent.press(button)

    await waitFor(() => {
      expect(tree.getByText('BCSC.ChangePIN.AccountLocked')).toBeTruthy()
    })
  })

  it('shows error when setPIN fails', async () => {
    mockVerifyPIN.mockResolvedValue({
      success: true,
      locked: false,
      remainingTime: 0,
      walletKey: 'test-wallet-key',
    })
    mockSetPIN.mockResolvedValue({
      success: false,
      walletKey: '',
      isAutoGenerated: false,
    })

    const tree = render(
      <BasicAppContext>
        <BCSCLoadingProvider>
          <ChangePINForm onSuccess={mockOnSuccess} />
        </BCSCLoadingProvider>
      </BasicAppContext>
    )

    const inputs = tree.getAllByAccessibilityHint('Enter your 6-digit PIN')
    fireEvent.changeText(inputs[0], '123456')
    fireEvent.changeText(inputs[1], '654321')
    fireEvent.changeText(inputs[2], '654321')

    const checkbox = tree.getByTestId('com.ariesbifold:id/IUnderstand')
    fireEvent.press(checkbox)

    const button = tree.getByTestId('com.ariesbifold:id/ChangePIN')
    fireEvent.press(button)

    await waitFor(() => {
      expect(tree.getByText('BCSC.ChangePIN.FailedToSetPIN')).toBeTruthy()
    })

    expect(mockOnSuccess).not.toHaveBeenCalled()
  })

  it('shows error when exception is thrown', async () => {
    mockVerifyPIN.mockRejectedValue(new Error('Network error'))

    const tree = render(
      <BasicAppContext>
        <BCSCLoadingProvider>
          <ChangePINForm onSuccess={mockOnSuccess} />
        </BCSCLoadingProvider>
      </BasicAppContext>
    )

    const inputs = tree.getAllByAccessibilityHint('Enter your 6-digit PIN')
    fireEvent.changeText(inputs[0], '123456')
    fireEvent.changeText(inputs[1], '654321')
    fireEvent.changeText(inputs[2], '654321')

    const checkbox = tree.getByTestId('com.ariesbifold:id/IUnderstand')
    fireEvent.press(checkbox)

    const button = tree.getByTestId('com.ariesbifold:id/ChangePIN')
    fireEvent.press(button)

    await waitFor(() => {
      expect(tree.getByText('BCSC.ChangePIN.ErrorChangingPIN')).toBeTruthy()
    })

    expect(mockOnSuccess).not.toHaveBeenCalled()
  })

  it('shows checkbox error when not checked', async () => {
    const tree = render(
      <BasicAppContext>
        <BCSCLoadingProvider>
          <ChangePINForm onSuccess={mockOnSuccess} />
        </BCSCLoadingProvider>
      </BasicAppContext>
    )

    const inputs = tree.getAllByAccessibilityHint('Enter your 6-digit PIN')
    fireEvent.changeText(inputs[0], '123456')
    fireEvent.changeText(inputs[1], '654321')
    fireEvent.changeText(inputs[2], '654321')

    // Don't check the checkbox

    const button = tree.getByTestId('com.ariesbifold:id/ChangePIN')
    fireEvent.press(button)

    await waitFor(() => {
      expect(tree.getByText('BCSC.ChangePIN.MustCheckBox')).toBeTruthy()
    })

    expect(mockVerifyPIN).not.toHaveBeenCalled()
  })
})
