import { BCSCLoadingProvider } from '@/bcsc-theme/contexts/BCSCLoadingContext'
import { fireEvent, render, waitFor } from '@testing-library/react-native'
import React from 'react'
import { setPIN } from 'react-native-bcsc-core'
import { BasicAppContext } from '../../../../../__mocks__/helpers/app'
import { PINEntryForm } from './PINEntryForm'

jest.mock('react-native-bcsc-core', () => ({
  setPIN: jest.fn(),
  canPerformDeviceAuthentication: jest.fn().mockResolvedValue(false),
  AccountSecurityMethod: {
    PinNoDeviceAuth: 'app_pin_no_device_authn',
    PinWithDeviceAuth: 'app_pin_has_device_authn',
    DeviceAuth: 'device_authentication',
  },
}))

jest.mock('@/bcsc-theme/hooks/useBCSCApiClient', () => ({
  useBCSCApiClientState: () => ({
    client: {},
    isClientReady: true,
  }),
}))

jest.mock('@/bcsc-theme/api/hooks/useRegistrationApi', () => ({
  __esModule: true,
  default: () => ({
    register: jest.fn().mockResolvedValue(undefined),
  }),
}))

describe('PINEntryForm', () => {
  const mockSetPIN = jest.mocked(setPIN)
  const mockOnSuccess = jest.fn()

  beforeEach(() => {
    jest.clearAllMocks()
  })

  it('renders correctly with create and confirm PIN fields', () => {
    const tree = render(
      <BasicAppContext>
        <BCSCLoadingProvider>
          <PINEntryForm onSuccess={mockOnSuccess} />
        </BCSCLoadingProvider>
      </BasicAppContext>
    )

    expect(tree.getByText('BCSC.PIN.CreatePIN')).toBeTruthy()
    expect(tree.getByText('BCSC.PIN.ConfirmPIN')).toBeTruthy()
    expect(tree.getByText('BCSC.PIN.RememberPIN')).toBeTruthy()
    expect(tree.getByText('BCSC.PIN.RememberPINDescription')).toBeTruthy()
    expect(tree).toMatchSnapshot()
  })

  it('uses custom translation prefix when provided', () => {
    const tree = render(
      <BasicAppContext>
        <BCSCLoadingProvider>
          <PINEntryForm onSuccess={mockOnSuccess} translationPrefix="Custom.Prefix" />
        </BCSCLoadingProvider>
      </BasicAppContext>
    )

    expect(tree.getByText('Custom.Prefix.CreatePIN')).toBeTruthy()
    expect(tree.getByText('Custom.Prefix.ConfirmPIN')).toBeTruthy()
  })

  it('shows checkbox acknowledgment', () => {
    const tree = render(
      <BasicAppContext>
        <BCSCLoadingProvider>
          <PINEntryForm onSuccess={mockOnSuccess} />
        </BCSCLoadingProvider>
      </BasicAppContext>
    )

    expect(tree.getByText('BCSC.PIN.IUnderstand')).toBeTruthy()
  })

  it('shows Continue button', () => {
    const tree = render(
      <BasicAppContext>
        <BCSCLoadingProvider>
          <PINEntryForm onSuccess={mockOnSuccess} />
        </BCSCLoadingProvider>
      </BasicAppContext>
    )

    expect(tree.getByText('Global.Continue')).toBeTruthy()
  })

  it('button is disabled when PINs are not entered and checkbox unchecked', () => {
    const tree = render(
      <BasicAppContext>
        <BCSCLoadingProvider>
          <PINEntryForm onSuccess={mockOnSuccess} />
        </BCSCLoadingProvider>
      </BasicAppContext>
    )

    const button = tree.getByTestId('com.ariesbifold:id/Continue')
    expect(button.props.accessibilityState.disabled).toBe(true)
  })

  it('calls onSuccess with wallet key when PIN is set successfully', async () => {
    mockSetPIN.mockResolvedValue({
      success: true,
      walletKey: 'test-wallet-key',
      isAutoGenerated: false,
    })

    const tree = render(
      <BasicAppContext>
        <BCSCLoadingProvider>
          <PINEntryForm onSuccess={mockOnSuccess} />
        </BCSCLoadingProvider>
      </BasicAppContext>
    )

    const inputs = tree.getAllByAccessibilityHint('Enter your 6-digit PIN')
    expect(inputs).toHaveLength(2) // Create and Confirm

    fireEvent.changeText(inputs[0], '123456')
    fireEvent.changeText(inputs[1], '123456')

    const checkbox = tree.getByTestId('com.ariesbifold:id/IUnderstand')
    fireEvent.press(checkbox)

    const button = tree.getByTestId('com.ariesbifold:id/Continue')
    fireEvent.press(button)

    await waitFor(() => {
      expect(mockSetPIN).toHaveBeenCalledWith('123456')
      expect(mockOnSuccess).toHaveBeenCalledWith({
        success: true,
        walletKey: 'test-wallet-key',
      })
    })
  })

  it('shows error when PINs do not match', async () => {
    const tree = render(
      <BasicAppContext>
        <BCSCLoadingProvider>
          <PINEntryForm onSuccess={mockOnSuccess} />
        </BCSCLoadingProvider>
      </BasicAppContext>
    )

    const inputs = tree.getAllByAccessibilityHint('Enter your 6-digit PIN')
    fireEvent.changeText(inputs[0], '123456')
    fireEvent.changeText(inputs[1], '654321') // Different

    const checkbox = tree.getByTestId('com.ariesbifold:id/IUnderstand')
    fireEvent.press(checkbox)

    const button = tree.getByTestId('com.ariesbifold:id/Continue')
    fireEvent.press(button)

    await waitFor(() => {
      expect(tree.getByText('BCSC.PIN.PINsDoNotMatch')).toBeTruthy()
    })

    expect(mockSetPIN).not.toHaveBeenCalled()
  })

  it('keeps button disabled when PIN is too short', () => {
    const tree = render(
      <BasicAppContext>
        <BCSCLoadingProvider>
          <PINEntryForm onSuccess={mockOnSuccess} />
        </BCSCLoadingProvider>
      </BasicAppContext>
    )

    const inputs = tree.getAllByAccessibilityHint('Enter your 6-digit PIN')
    fireEvent.changeText(inputs[0], '123') // Too short
    fireEvent.changeText(inputs[1], '123')

    const checkbox = tree.getByTestId('com.ariesbifold:id/IUnderstand')
    fireEvent.press(checkbox)

    // Button should remain disabled when PINs are too short
    const button = tree.getByTestId('com.ariesbifold:id/Continue')
    expect(button.props.accessibilityState.disabled).toBe(true)

    expect(mockSetPIN).not.toHaveBeenCalled()
  })

  it('shows checkbox error when not checked', async () => {
    const tree = render(
      <BasicAppContext>
        <BCSCLoadingProvider>
          <PINEntryForm onSuccess={mockOnSuccess} />
        </BCSCLoadingProvider>
      </BasicAppContext>
    )

    const inputs = tree.getAllByAccessibilityHint('Enter your 6-digit PIN')
    fireEvent.changeText(inputs[0], '123456')
    fireEvent.changeText(inputs[1], '123456')

    // Don't check the checkbox

    const button = tree.getByTestId('com.ariesbifold:id/Continue')
    fireEvent.press(button)

    await waitFor(() => {
      expect(tree.getByText('BCSC.PIN.MustCheckBox')).toBeTruthy()
    })

    expect(mockSetPIN).not.toHaveBeenCalled()
  })

  it('shows error when setPIN fails', async () => {
    mockSetPIN.mockResolvedValue({
      success: false,
      walletKey: '',
      isAutoGenerated: false,
    })

    const tree = render(
      <BasicAppContext>
        <BCSCLoadingProvider>
          <PINEntryForm onSuccess={mockOnSuccess} />
        </BCSCLoadingProvider>
      </BasicAppContext>
    )

    const inputs = tree.getAllByAccessibilityHint('Enter your 6-digit PIN')
    fireEvent.changeText(inputs[0], '123456')
    fireEvent.changeText(inputs[1], '123456')

    const checkbox = tree.getByTestId('com.ariesbifold:id/IUnderstand')
    fireEvent.press(checkbox)

    const button = tree.getByTestId('com.ariesbifold:id/Continue')
    fireEvent.press(button)

    await waitFor(() => {
      expect(tree.getByText('BCSC.PIN.FailedToSetPIN')).toBeTruthy()
    })

    expect(mockOnSuccess).not.toHaveBeenCalled()
  })

  it('shows error when exception is thrown during setPIN', async () => {
    mockSetPIN.mockRejectedValue(new Error('Network error'))

    const tree = render(
      <BasicAppContext>
        <BCSCLoadingProvider>
          <PINEntryForm onSuccess={mockOnSuccess} />
        </BCSCLoadingProvider>
      </BasicAppContext>
    )

    const inputs = tree.getAllByAccessibilityHint('Enter your 6-digit PIN')
    fireEvent.changeText(inputs[0], '123456')
    fireEvent.changeText(inputs[1], '123456')

    const checkbox = tree.getByTestId('com.ariesbifold:id/IUnderstand')
    fireEvent.press(checkbox)

    const button = tree.getByTestId('com.ariesbifold:id/Continue')
    fireEvent.press(button)

    await waitFor(() => {
      expect(tree.getByText('BCSC.PIN.ErrorSettingPIN')).toBeTruthy()
    })

    expect(mockOnSuccess).not.toHaveBeenCalled()
  })

  it('shows error when first PIN is too short when pressing Continue', async () => {
    const tree = render(
      <BasicAppContext>
        <BCSCLoadingProvider>
          <PINEntryForm onSuccess={mockOnSuccess} />
        </BCSCLoadingProvider>
      </BasicAppContext>
    )

    const inputs = tree.getAllByAccessibilityHint('Enter your 6-digit PIN')
    fireEvent.changeText(inputs[0], '123') // Too short
    fireEvent.changeText(inputs[1], '654321')

    const checkbox = tree.getByTestId('com.ariesbifold:id/IUnderstand')
    fireEvent.press(checkbox)

    // Button is disabled so we need to bypass by triggering validation directly
    // This is simulating the scenario where the user could somehow submit
    // Actually, the button should be disabled, so let's verify that
    const button = tree.getByTestId('com.ariesbifold:id/Continue')
    expect(button.props.accessibilityState.disabled).toBe(true)

    expect(mockSetPIN).not.toHaveBeenCalled()
  })

  it('shows error when second PIN is too short when pressing Continue', async () => {
    const tree = render(
      <BasicAppContext>
        <BCSCLoadingProvider>
          <PINEntryForm onSuccess={mockOnSuccess} />
        </BCSCLoadingProvider>
      </BasicAppContext>
    )

    const inputs = tree.getAllByAccessibilityHint('Enter your 6-digit PIN')
    fireEvent.changeText(inputs[0], '123456')
    fireEvent.changeText(inputs[1], '123') // Too short

    const checkbox = tree.getByTestId('com.ariesbifold:id/IUnderstand')
    fireEvent.press(checkbox)

    const button = tree.getByTestId('com.ariesbifold:id/Continue')
    expect(button.props.accessibilityState.disabled).toBe(true)

    expect(mockSetPIN).not.toHaveBeenCalled()
  })
})
