# Codecov configuration documentation
# https://docs.codecov.com/docs/coverage-configuration
#
# Validate your configuration
# https://api.codecov.io/validate
# curl -X POST --data-binary @.codecov.yml https://codecov.io/validate

coverage:
  range: 60..80 # less than 60% means red UI, 80% and above is green, between is yellow
  round: down # round down fractional coverage ie: 70.7532 -> 70.75
  precision: 2 # number of digits after the decimal point
  status:
    project:
      default:
        target: auto
        branches:
          - main
        paths:
          - app/src
        only_pulls: true
    patch:
      default:
        target: auto # target is the current project coverage
        branches:
          - main
        paths:
          - app/src
        only_pulls: true

comment:
  layout: 'header, files, footer'
  require_changes: false
  hide_project_coverage: false
