#!/bin/sh
. "$(git --exec-path)/git-sh-setup"

require_clean_work_tree "update lock files"

yarn install
( cd app/ios; pod install )
( cd app/android; ./gradlew app:dependencies --write-locks )

git add .
git commit -sm "chore:update lock files" --no-verify
