// prettier-ignore
const translation = {
  "BCID": {
    "GetID": "Obtenir BCID",
    "GetDigitalID": "Obtenez votre Identité personnelle",
  },
  "Error": {
    "Title2020": "Incapable d'analiser l'invitation.",
    "Message2020": "Un problème est survenu lors de l'analysation de l'invitation de connection.",
    "Title2021": "Incapable de recevoir l'invitation.",
    "Message2021": "Un problème est survenu lors de la réception de l'invitation de connection.",
    "Title2022": "Incapable de trouver la NDA (DID) d'héritage.",
    "Message2022": "Un problème est survenu lors de l'extraction du dépôt de la numérotation directe à l'arrivé (DID).",
    "Title2025": "Authentification BCSC",
    "Message2025": "Un problème survenu a été raporté par le BCSC.",
    "Title2026": "Oups! Un problème est survenu.",
    "Message2026": "L'application a rencontré un problème. Essayez de la redémarrer.",
    "Title2027": "Incapable d'analiser l'invitation.",
    "Message2027": "Un problème est survenu lors de l'analyse de l'attestation de l'invitation de connection.",
    "Title2028": "Incapable de recevoir l'invitation.",
    "Message2028": "Un problème est survenu pendant la réception de l'attestation de l'invitation de connection.",
    "Title2029": "Incapable de gérer la preuve d'attestation.",
    "Message2029": "Un problème est survenu de la gestion lors de la requête de preuve d'attestation.",
    "Title2030": "Unable to complete app initialization (FR)",
    "Message2030": "There was a problem while initializing the app. (FR)",
    "Title2031": "Unable to complete agent initialization (FR)",
    "Message2031": "There was a problem while initializing the agent. (FR)",
    "Title2032": "Unable to open app-to-app URL (FR)",
    "Message2032": "There was a problem while opening the app-to-app URL. (FR)",
    "NoMessage": "Aucun message",
  },
  "CameraDisclosure": {
    "AllowCameraUse": "Autoriser l'utilisation de la caméra",
    "CameraDisclosure": "La caméra est utilisée pour scanner les codes QR pour un traitement immédiat sur l'appareil. Aucune information sur les images n'est conservé, utilisée à des fins d'analyse ou partagée.",
    "ToContinueUsing": "Pour continuer à utiliser la fonction de scan de BC Wallet, veuillez activer les autorisations de la caméra.",
    "Allow": "Autoriser",
    "OpenSettings": "Ouvrir les paramètres",
  },
  "Biometry": {
    "Toggle": "Activer/Désactiver la biométrie",
    "EnabledText1": "Connectez-vous avec les données biométriques de votre téléphone plutôt que votre code PIN BC Wallet.",
    "EnabledText1Bold": "vous allez devoir utiliser vos données biométriques pour accéder à votre portefeuille numérique.",
    "EnabledText2": "Cela signifie que toutes les empreintes digitales et données faciales ajoutées sur ce téléphone peuvent être utilisées pour accéder à votre portefeuille numérique.",
    "EnabledText3": "N'importe quelle personne qui a accès à votre téléphone en utilisant la biométrie peut accéder à votre portefeuille.",
    "EnabledText3Bold": "Assurez-vous d'être la seule personne à avoir accès à votre portefeuille.",
    "Warning": "Assurez-vous d'être la seule personne à avoir accès à votre portefeuille.",
    "UseToUnlock": "Utiliser les données biométriques pour débloquer le portefeuille ?",
  },
  "Credentials": {
    "AddCredential": "Ajouter des identifiants",
    "EmptyList": "Votre portefeuille est vide",
    "AddFirstCredential": "Ajouter votre premier identifiant"
  },
  "Onboarding": {
    "DifferentWalletHeading": "Un portefeuille intelligent unique",
    "DifferentWalletParagraph": "Contrairement aux autres portefeuilles numériques, BC Wallet vous aide à prouver votre identité en personne ou en ligne en stockant et en utilisant des informations d'identification numériques émises par les services participants.\n\nInteragissez en toute confiance avec les personnes et les organisations en qui vous avez confiance.",
    "DigitalCredentialsHeading": "Identifiants",
    "DigitalCredentialsParagraph": "Les titres numériques sont l'équivalent électronique des titres physiques tels que les certifications et les permis proposés par les services participants.\n\nLes services sont simplifiés et accélérés car les organisations et les individus peuvent confirmer leur identité à l'aide d'informations fiables provenant de titres numériques.",
    "PrivateConfidentialHeading": "Privé et confidentiel",
    "PrivateConfidentialParagraph": "Votre vie privée est importante.\n\nLe gouvernement de la Colombie-Britannique ne sait pas quand vous utilisez des identifiants numériques, à moins que vous n'interagissiez avec eux. Aucune analyse n'est enregistrée.\n\nVous approuvez chaque utilisation de vos identifiants numériques et ne fournissez que les informations nécessaires.",
    "GetStarted": "Commencer",
  },
  "Preface": {
    "Paragraph1": "La plupart des gens n'auront pas besoin de BC Wallet car très peu de titres numériques sont actuellement disponibles.",
    "Link1": "Voir où vous pouvez utiliser BC Wallet",
    "Paragraph2": "Si BC Wallet ne correspond pas à ce que vous recherchez, mais que vous êtes curieux, consultez notre rubrique",
    "Link2": "Présentation de BC Wallet",
  },
  "Screens": {
    "Onboarding": "BC Wallet",
    "Terms": "Conditions générales d'utilisation",
    "Settings": "Menu",
    "Preface": "BC Wallet",
    "VerificationSteps": "Setup steps (FR)",
    "EvidenceCollectionStep": {
      "Stage1": "Choose your identification (FR)",
      "Stage2": "Instructions (FR)",
      "Stage3": "Scan your identification (FR)",
      "Stage4": "Enter serial number (FR)",
      "Stage5": "Enter birthdate (FR)",
    },
    "ResidentialAddressStep": {
      "Stage1": "TODO",
    },
    "EmailStep": {
      "Stage1": "TODO",
    },
    "VerifyIdentityStep": {
      "Stage1": "TODO",
    },
  },
  "PINCreate": {
    "Explainer": {
      "PrimaryHeading": "Create a PIN that is: (FR)",
      "Bullet1": "<b>Memorable.</b> If you forget your PIN, you can't recover it. You will need to reinstall and set up your wallet again. (FR)",
      "Bullet2": "<b>Unique.</b> Your PIN prevents people from accessing your digital credentials. Do not share it with anyone. (FR)",
    }
  },
  "PersonCredentialNotification": {
    "Title": "Obtener votre carte d'identité",
    "Description": "Ajouter votre carte d'identité à votre portefeuille et utilisez-la pour accéder aux services en ligne."
  },
  "PersonCredential": {
    "ServicesCardInstalled": "Étape 1: BC Services Card est déjà installé",
    "InstallServicesCard": "Étape 1: Installation de l'application BC Services Card",
    "InstallApp": "Installer l'application",
    "AppOnOtherDevice": "Je l'ai déjà sur un autre appareil",
    "CreatePersonCred": "Étape 2: Créez votre carte d'identité",
    "StartProcess": "Démarrer le processus",
    "PageTitle": "Carte d'identité",
    "PleaseWait": "Merci de patienter pendant que nous préparons les choses pour vous",
    "WhatIsPersonCredentialLink": "Qu'est-ce qu'un justificatif personnel",
    "WhereToUseLink": "Où l'utiliser",
    "HelpLink": "Aide",
    "EstablishingConnection": "Establishing connection... (FR)",
    "ConnectedToAgent": "Connected to agent... (FR)",
    "WaitingForAppAttestation": "Waiting for app attestation... (FR)",
    "AppAttested": "App attested... (FR)",
    "OfferingCredential": "Offering credential... (FR)",
    "InitiatingAppToAppFlow": "Initiating app-to-app flow... (FR)",
  },
  "NetInfo": {
    "NoInternetConnectionTitle": "Aucune connection internet",
    "NoInternetConnectionMessage": "Vous ne pouvez pas accéder aux services en utilisant BC Wallet ou recevoir des informations d'identification jusqu'à ce que vous soyez de nouveau en ligne.\n\nVeuillez vérifier votre connexion internet.",
  },
  "Tour": {
    "GuideTitle": "Bienvenue sur BC Wallet",
    "WouldYouLike": "Souhaitez vous obtenir des conseils sur l'utilisation de BC Wallet ?",
    "UseAppGuides": "Utiliser les guides de l'application",
    "DoNotUseAppGuides": "Ne pas utiliser les guides de l'application",
    "AddAndShare": "Ajouter et partager des identifiants",
    "AddAndShareDescription": "Pour ajouter et utiliser des identifiants, vous devez scanner un code QR affiché par le fournisseur de services.",
    "AddCredentials": "Ajouter des identifiants",
    "AddCredentialsDescription": "Ajouter des identifiants en scannant un code QR affiché sur le service de l'émetteur.",
    "Notifications": "Notifications",
    "NotificationsDescription": "Après avoir scanné un code QR, l'offre de vérification ou la demande de preuve apparaîtra ici, ainsi que d'autres événements notables.",
    "YourCredentials": "Vos identifiants",
    "YourCredentialsDescription": "Les identifiants que vous avez ajoutées apparaissent ici. Vous pouvez consulter les détails des justificatifs et ajouter ou supprimer des justificatifs.",
    "CredentialOffers": "Offres d'identifiants",
    "CredentialOffersDescription": "Une organisation vous a proposé un identifiant. Examinez les détails de l'habilitation et choisissez de l'accepter ou de la refuser. Les identifiants acceptés seront ajoutés à votre portefeuille.",
    "ProofRequests": "Demandes de preuves",
    "ProofRequestsDescription": "Une organisation vous demande de prouver votre identité. Examinez ce qu'elle vous demande et choisissez de l'accepter ou de le refuser.",
    "Skip": "Sauter",
    "Next": "Suivant",
    "Back": "Retour",
    "Done": "Terminé",
  },
  "Settings": {
    "Help": "Aide",
    "MoreInformation": "Plus d'informations",
    "PlayWithBCWallet": "Jouer avec BC Wallet",
    "HelpUsingBCWallet": "Aide à l'utilisation de BC Wallet",
    "GiveFeedback": "Donner votre avis",
    "ReportAProblem": "Signaler un problème",
    "TermsOfUse": "Conditions d'utilisation",
    "PrivacyStatement": "Déclaration de confidentialité",
    "VulnerabilityDisclosurePolicy": "Politique de divulgation des vulnérabilités",
    "Accessibility": "Accessibilité",
    "IntroductionToTheApp": "Introduction à l'application",
  },
  "Developer": {
    "Environment": "Environnement",
    "Production": "Production",
    "Development": "Développement",
    "Test": "Test",
    "DeveloperMode": "Mode développeur",
    "Toggle": "Activer/Désactiver le mode développeur",
    "AttestationSupport": "Soutien d'attestation",
    "EnableProxy": "Enable proxy (FR)",
    "EnableAltPersonFlow": "Alt Person flow (FR)",
    "EnableAppToAppPersonFlow": "App-to-app Person flow (FR)",
  },
  "Tips": {
    "Header": "Conseils",
    "GettingReady": "Préparation de votre portefeuille en cours...",
    "Tip1": "Pour plus de sécurité, BC Wallet verrouille l'application après 5 minutes d'inactivité.",
    "Tip2": "Contrairement à la présentation de cartes physiques, vous partagez uniquement ce qui est nécessaire à partir de vos identifiants.",
    "Tip3": "Vos identifiants sont stockés uniquement sur ce téléphone, nulle part ailleurs.",
    "Tip4": "Les informations sont envoyées et reçues via une connexion chiffrée et non traçable.",
    "Tip5": "Souvenez-vous de votre code PIN. Si vous l'oubliez, vous devrez réinstaller et réajouter vos identifiants.",
    "Tip6": "Éviter le code PIN et déverrouiller votre portefeuille avec vos données biométriques pour une expérience plus rapide.",
    "Tip7": "Vos identifiants ajoutés le plus récemment sont placés en haut.",
    "Tip8": "Supprimez les identifiants de votre portefeuille depuis l'écran des détails des identifiants.",
    "Tip9": "Vous pouvez ignorer les notifications sans les ouvrir en appuyant sur “X” dans le coin supérieur droit.",
    "Tip10": "Besoin d'aide ? Trouvez des réponses dans la section d'aide accessible via le bouton “☰” en haut à gauche.",
    "Tip11": "Vous pouvez allumer le flash de l'appareil photo si le code QR est difficile à voir.",
    "Tip12": "Si le code QR ne se scanne pas, essayez d'augmenter la luminosité de l'écran.",
    "Tip13": "Les informations envoyées via votre portefeuille sont de confiance pour vous et vos Contacts avec lesquels vous interagissez.",
    "Tip14": "Même les identifiants révoqués ou expirés peuvent être utilisables si l'organisation ne les demande pas.",
  },
  "Init": {
    "Retry": "Réessayer",
    "Starting": "Démarrage...",
    "FetchingPreferences": "Récupération des préférences...",
    "VerifyingOnboarding": "Vérification de l'intégration...",
    "CheckingOCA": "Checking for OCA updates... (FR)",
    "InitializingAgent": "Initialisation de l'agent...",
    "Finishing": "Finalisation...",
  },
  "Feedback": {
    "GiveFeedback": "Donner votre avis",
  },
  "PushNotifications": {
    "NotificationsOffTitle": "Les notifications pour BC Wallet sont désactivées",
  },
  "AddCredentialSlider": {
    "Choose": "Choisir",
    "ScanQRCode": "Scanner un code QR",
  },
  "Scan": {
    "ScanOnySpecial": "Seuls les codes QR spéciaux peuvent être scannés par BC Wallet.",
    "ScanOnlySpecial3": "BC Wallet ne prend actuellement pas en charge l'ajout de justificatifs numériques en scannant ou en prenant des photos de justificatifs physiques.",
    "WhereToUseLink": "Voyez où vous pouvez utiliser BC Wallet.",
    "BadQRCodeDescription": "Le code QR scanné ne fonctionne pas avec BC Wallet. BC Wallet ne fonctionne qu'avec les services participants.\n\nIl ne peut actuellement pas ajouter de justificatifs numériques en prenant des photos de justificatifs physiques."
  },
  "Unified": {
    "Steps": {
      "ScanOrTakePhotos": "Scan or take photos of your ID. (FR)",
    },
    "ChooseYourID": {
      "WhatCardDoYou": "What BC Services Card do you have? (FR)",
      "SomePeopleStillCallIt": "Some people still call it a CareCard or a Health Card. It has your personal health number (PHN) on the back. (FR)",
      "CombinedCard": "Combined card (FR)",
      "CombinedCardActionText": "It's combined with my driver's licence (FR)",
      "CombinedCardDescription": "Use this card for a faster way to set up the app. (FR)",
      "PhotoCard": "Photo card (FR)",
      "PhotoCardActionText": "A card with my photo (FR)",
      "PhotoCardDescription": "Use this card for a faster way to set up the app. (FR)",
      "NoPhotoCard": "Non photo card (FR)",
      "NoPhotoCardActionText": "A card without a photo (FR)",
      "NoPhotoCardDescription": "Use this card + photo ID to set up the app. (FR)",
      "DontHaveOne": "Don't have one? (FR)",
      "CheckBefore": "Check before you continue. It's faster to set up with one of the above. (FR)",
      "CheckForServicesCard": "Check for BC Services Card (FR)",
      "CheckIfIHave": "Check if I have a BC Services Card (FR)",
      "OtherID": "Other ID (FR)",
      "OtherIDActionText": "Set up with other ID (FR)",
      "OtherIDDescription": "This option takes the longest to set up. You'll need 2 IDs to set up the app and have limited access to services. (FR)",
    },
    "Instructions": {
      "Heading": "Provide the card serial number on the back right side of your card. (FR)",
      "Paragraph": "When scanning, you should place the card in front of a white background for best results. (FR)",
      "ScanBarcode": "Scan Barcode with Camera (FR)",
      "EnterManually": "Enter Serial Number Manually (FR)",
    },
    "Scan": {},
    "ManualSerial": {
      "InputLabel": "Serial number (FR)",
      "InputSubText": "Enter the letter and numbers by the barcode on the back of your card. (FR)",
      "EmptySerialError": "Required (FR)",
      "CharCountError": "Cannot exceed 15 characters (FR)",
    },
    "Birthdate": {
      "CardSerialNumber": "Card serial number: {{ serial }} (FR)",
      "Heading": "Enter your birthdate (FR)",
      "Paragraph": "Your birthdate is only used to to set up this app. It is not shared. (FR)",
      "InputLabel": "Birthdate (FR)",
    },
  },
  "RemoteLogging": {
    "ScreenTitle": "Dépannage à distance",
    "Heading": "Avis de collecte",
    "CollectionNoticePart1": "L'activation du dépannage à distance",
    "CollectionNoticeBold": " enregistrera l'utilisation du portefeuille et des identifiants ainsi que toute information personnelle associée",
    "CollectionNoticePart2": " pendant qu'il est activé.\n\nLe dépannage à distance se désactive après 1 heure. Les informations collectées sont supprimées après 3 jours.\n\nCes informations sont collectées par le Ministère des Services aux citoyens - Direction de la cybersécurité et de la confiance numérique en vertu des sections 26(c) et 26(e) de la Loi sur l'accès à l'information et la protection de la vie privée, et seront uniquement utilisées à des fins de support client et de dépannage.\n\nPour plus d'informations, y compris qui contacter, lisez la",
    "CollectionNoticeLink": "Politique de confidentialité.",
    "CollectionNoticeWarning": "Activez le dépannage à distance uniquement si vous avez d'abord contacté la ligne de support et qu'un agent de service du gouvernement de la Colombie-Britannique vous a demandé de l'activer. Ils ne vous contacteront jamais en premier. Vous n'êtes jamais obligé de l'activer.",
    "CheckBoxTitle": "Je comprends et je veux activer le dépannage à distance.",
    "IAgree": "J'accepte",
    "ButtonTitle": "Activer",
    "SessionID": "ID de session",
    "Banner": "Dépannage à distance activé. ID : {{ sessionId }}",
  },
  "AppUpdate": {
    "Heading": "Update BC Wallet to the latest version (FR)",
    "Body": "BC Wallet was updated with new improvements. Update your app now to enjoy the latest features and enhancements. (FR)"
  },
}

export default translation
