const translation = {
  BCID: {
    GetID: 'Obtenir BCID',
    GetDigitalID: 'Ajouter mon Attestation numérique d’authentification gouvernementale',
  },
  Onboarding: {
    SkipA11y: 'Sauter',
  },
  Global: {
    Enter: 'Entrer',
    EnterPin: 'Saisir le NIP',
    '6DigitPin': 'NIP à 6 chiffres',
    Submit: 'Soumettre',
    'NoneYet!': "Vous n'avez pas d'attestation dans votre portefeuille.",
    Cancel: 'Annuler',
    Confirm: 'Confirmer',
    Accept: 'Accepter',
    Reject: 'Rejeter',
    NotNow: 'Pas maintenant',
    Share: 'Partager',
    Decline: 'Refuser',
    Back: 'Précédent',
    Next: 'Suivant',
    Continue: 'Continuer',
    Info: 'Information',
    ThisDecisionCannotBeChanged: 'Cette décision ne peut être modifiée.',
    Failure: 'Échec',
    Success: 'Succès',
    SomethingWentWrong: 'Un problème est survenu',
    Done: 'Terminé',
    Skip: 'Ignorer',
    View: 'Afficher',
    Home: 'Accueil',
    ErrorCode: "Code d'erreur",
    Okay: 'Ok',
    TryAgain: 'Réessayer',
    GoBack: 'Retourner',
    GetStarted: 'Commencer',
    Dismiss: 'Rejeter',
    On: 'Activé',
    Off: 'Fermer',
    Close: 'Retirer',
    Save: 'Enregistrer',
    ShowDetails: 'Afficher les détails',
    Biometrics: 'Biométrie',
    Remove: 'Supprimer',
    UpdateRequired: {
      Title: 'Mise à jour requise',
      Body: 'Une mise à jour requise est disponible. Veuillez mettre à jour votre application.',
      Confirm: 'Mettre à jour maintenant',
      Cancel: 'Annuler',
      ErrorTitle: 'Mise à jour indisponible',
      ErrorMsg: "Impossible de mettre à jour l'application.",
    },
    UpdateAvailable: {
      Title: 'Mise à jour disponible',
      Body: 'Une mise à jour est disponible.',
      Confirm: 'Mettre à jour maintenant',
      Cancel: 'Annuler',
      ErrorTitle: 'Mise à jour indisponible',
      ErrorMsg: "Impossible de mettre à jour l'application.",
    },
  },
  Language: {
    code_en: 'Anglais',
    code_fr: 'Français',
    'code_pt-BR': 'Portugais',
  },
  Date: {
    ShortFormat: 'D MMM',
    LongFormat: 'D MMMM',
    MinuteAgo: 'Il y a une minute',
    MinutesAgo: 'Il y a quelques minutes',
    JustNow: 'À l’instant',
    MonthLong: {
      January: 'janvier',
      February: 'février',
      March: 'mars',
      April: 'avril',
      May: 'mai',
      June: 'juin',
      July: 'juillet',
      August: 'aout',
      September: 'septembre',
      October: 'octobre',
      November: 'novembre',
      December: 'décembre',
    },
    MonthShort: {
      January: 'janv.',
      February: 'févr.',
      March: 'mars.',
      April: 'avril.',
      May: 'mai.',
      June: 'juin.',
      July: 'juil.',
      August: 'août.',
      September: 'sept.',
      October: 'oct.',
      November: 'nov.',
      December: 'déc.',
    },
  },
  ActivityLog: {
    Your: 'Votre ',
    Activity: "journal d'activité",
    Updated: 'a été mis à jour',
  },
  CameraDisclosure: {
    AllowCameraUse: "Autoriser l'utilisation de l'appareil photo",
    CameraDisclosure:
      "L'appareil photo est utilisée pour balayer les codes QR. Aucune information sur les images n'est enregistrée, utilisée à des fins d'analyse ou partagée.",
    ToContinueUsing:
      "Pour continuer à utiliser la fonction de balayage du portefeuille numérique, veuillez autoriser l'utilisation de l'appareil photo.",
    Allow: 'Autoriser',
    OpenSettings: 'Ourvir Paramètres',
  },
  Biometry: {
    Toggle: 'Activer la biométrie',
    EnabledText1:
      'Déverrouillez votre portefeuille avec la biométrie de votre appareil au lieu d’utiliser le NIP du portefeuille.',
    EnabledText1Bold:
      'Notez qu’en activant la biométrie, toute personne dont les données biométriques sont enregistrées sur votre appareil pourra déverrouiller votre portefeuille et avoir accès à vos attestations.',
    EnabledText2:
      'Cela signifie que toutes les empreintes digitales et les données faciales ajoutées sur cet appareil peuvent être utilisées pour accéder à votre portefeuille QC.',
    EnabledText3:
      "Toute personne pouvant accéder à votre téléphone à l'aide de la biométrie peut accéder à votre portefeuille numérique.",
    EnabledText3Bold: 'Assurez-vous que vous seul avez accès à votre portefeuille.',
    Warning: '\n\nAssurez-vous que vous seul avez accès à votre portefeuille.',
    UseToUnlock: 'Souhaitez-vous utiliser la biométrie pour déverrouiller votre portefeuille?',
    NotEnabledText1: "La biométrie n'est pas configurée sur cet appareil. Elle ne peut donc pas être activée.",
    NotEnabledText2:
      "Si vous souhaitez activer cette fonctionnalité, activez la biométrie dans les paramètres de l'appareil, puis revenez à cet écran.",
    UnlockPromptTitle: 'Déverrouillage du portefeuille',
    UnlockPromptDescription: 'Utilisez la biométrie pour déverrouiller votre portefeuille',
    NoBiometricsErrorTitle: 'Pas de biométrie',
    NoBiometricsErrorMessage: "La biométrie n'est pas activée sur cet appareil.",
    NoBiometricsErrorDetails: 'Pour résoudre ce problème, activez la biométrie dans les paramètres de votre appareil.',
    ProgressBarText: '3. Activer la biométrie',
  },
  Error: {
    ReportThisProblem: 'Signaler ce problème',
    Title2020: "Impossible de traiter l'invitation",
    Message2020: "Un problème est survenu lors du traitement de l'invitation à se connecter.",
    Title2021: "Impossible de recevoir l'invitation",
    Message2021: "Un problème est survenu lors de la réception de l'invitation à se connecter.",
    Title2022: "Impossible de trouver l'ancienne identité numérique.",
    Message2022: "Un problème est survenu lors de l'extraction du référentiel de l'identité numérique.",
    Title2025: 'Authentification BCSC',
    Message2025: 'Un problème a été signalé par BCSC.',
    Title2026: 'Oups! Un problème est survenu.',
    Message2026: "Un problème est survenu. Veuillez redémarrer l'application.",
    NoMessage: 'Aucun message.',
    Unknown: 'Erreur inconnue',
    Problem: 'Un problème est survenu',
    Title1034: 'Impossible de récupérer la demande de preuve.',
    Message1034: 'La demande de preuve est introuvable.',
    Title1035: "Impossible de récupérer l'offre d'attestation.",
    Message1035: "L'offre d'attestation est introuvable.",
    Title1036: 'Impossible de récupérer les attestations du portefeuille.',
    Message1036: 'Les attestations du portefeuille sont introuvables.',
    Title1037: 'Impossible de supprimer le contact.',
    Message1037: 'Un problème est survenu lors de la suppression du contact.',
    Message2024: "La demande d'authentification a été annulée.",
    Title2024: 'Authentification BCSC',
    ErrorCode: "Code d'erreur.",
    Title1024: "Impossible d'accepter l'attestation.",
    Message1024: "Un problème est survenu lors de l'acceptation de l'offre de justificatif(s).",
    Title1025: "Impossible de rejeter l'attestation.",
    Message1025: "Un problème est survenu lors du rejet de l'offre d'attestation.",
    Title1026: 'Impossible de mettre à jour les attestations récupérées.',
    Message1026: 'Un problème est survenu lors de la mise à jour des attestations récupérées.',
    Title1027: "Impossible d'accepter la demande de preuve.",
    Message1027: "Un problème est survenu lors de l'acceptation de la demande de preuve.",
    Title1028: 'Impossible de rejeter la demande de preuve.',
    Message1028: 'Un problème est survenu lors du rejet de la demande de preuve.',
    Title1029: 'Détails   Impossible de mettre à jour les attestations récupérées..',
    Message1029: 'Un problème est survenu lors de la mise à jour des attestations récupérées.',
    Title1030: "Impossible d'accepter la connexion.",
    Message1030: "Un problème est survenu lors de l'acceptation de la redirection de la connexion.",
    Title1031: "Impossible d'accepter la connexion.",
    Message1031: "Un problème est survenu lors de l'acceptation de la connexion.",
    Title1032: "Impossible de retirer l'attestation.",
    Message1032: "Un problème est survenu lors du retrait de l'attestation.",
    Title1033: "Impossible de récupérer l'attestation.",
    Message1033: "L'attestation est introuvable.",
    Title1038: 'Impossible de générer une demande de preuve.',
    Message1038: 'Un problème est survenu lors de la génération de la demande de preuve.',
    Title1039: 'Impossible de gérer le lien profond.',
    Message1039: "Un problème est survenu lors de la gestion d'un lien profond.",
    Title1040: 'Impossible de créer le NIP.',
    Message1040: 'Un problème est survenu lors de la création du NIP.',
    Title1041: 'Impossible de déverrouiller avec le NIP.',
    Message1041: 'Un problème est survenu lors du déverrouillage avec le NIP.',
    Title1042: 'Impossible de vérifier le NIP.',
    Message1042: 'Un problème est survenu lors de la vérification du NIP.',
    Title1043: 'Impossible de récupérer les attestations pour la preuve.',
    Message1043: 'Un problème est survenu lors de la récupération des attestations pour la preuve.',
    Title1044: "Impossible d'initialiser l'onboarding.",
    Message1044: "Un problème est survenu lors de l'initialisation de l'onboarding.",
    Title1045: "Impossible d'initialiser l'agent.",
    Message1045: "Un problème est survenu lors de l'initialisation de l'agent.",
  },
  Credentials: {
    AddCredential: 'Ajouter une attestation',
    AddFirstCredential: 'Ajouter votre première attestation',
    CredentialsNotFound: 'Attestations introuvables',
    CredentialDetails: 'Détails des attestations',
    EmptyList: 'Votre portefeuille est vide. Vos attestations valides seront ajoutées ici.',
    IssuedBy: 'Délivré par',
    Credential: 'attestation',
  },
  PersonCredentialNotification: {
    Title: "Obtenez votre attestation d'identité",
    Description:
      "Ajoutez l'attestation d'identité à votre portefeuille et utilisez-la pour accéder aux services en ligne.",
    ButtonTitle: 'Démarrer',
  },
  PersonCredential: {
    Issuer: 'Services Québec.',
    Name: 'Personne',
    GivenName: 'Exemple de prénom',
    FamilyName: 'Exemple de nom de famille',
    Description:
      "Ajoutez vos justificatifs d’identités à votre portefeuille pour prouver vos informations personnelles en ligne et accéder aux services en ligne.\n\nVous aurez besoin de l'application Services Québec Card configurée sur cet appareil mobile.",
    LinkDescription: "Obtenez l'application BC Services Card",
    GetCredential: "Obtenez votre attestation d'identité",
    Decline: "L'obtenir plus tard",
    PageTitle: "Attestation d'ìdentité",
    ServicesCardInstalled: "Étape 1: L'application Portefeuille Québec est installée",
    InstallServicesCard: "Étape 2: Installez l'application Portefeuille Québec",
    InstallApp: "Installez l'application",
    AppOnOtherDevice: "Je l'ai dans un autre appareil",
    CreatePersonCred: "Étape 2: Créez votre attestation d'identité numérique gouvernemantale",
    StartProcess: 'Start the process (FR)',
  },
  DefaultNotification: {
    PageTitle: 'Accueil',
    Title: "Demander votre attestation numérique d'attestation gouvernementale",
    Description: 'Ministère de la Cybersécurité et du Numérique',
    ButtonTitle: 'Démarrer',
  },
  DefaultNotificationPage: {
    Title: 'Demander son Attestation d’authentification',
    Description:
      'L’Attestation d’authentification est une attestation qui vous permettra de vous identifier plus rapidement auprès des services gouvernementaux utilisant le Service d’authentification gouvernementale.',
    SAGConnexion: 'Étape 1 - Connexion au Service d’authentication gouvernementale',
    SAGConnexionDescription: 'Vous devez vous authentifier auprès du service.',
    ANIGRequest: 'Étape 2 - Demander l’attestation',
    ANIGAcceptDescription:
      'Depuis la gestion de compte, vous devrez balayer le code QR qui vous sera présenté.\r\n\r\nVous devrez ensuite accepter l’offre d’attestation qui vous sera proposée.',
    ButtonTitle: 'Recevoir mon attestation',
    ButtonHome: 'Revenir à l’accueil',
  },
  OptionsPlus: {
    PageTitle: "Plus d'option",
    ButtonParamsApp: "Paramètres de l'application",
    ButtonHelpCenter: "Centre d'aide",
    ButtonAbout: 'À propos',
    TitleSupport: 'Soutien à la clientèle',
    DetailSupport: "Vous avez un problème avec l'application ou des questions, vous pouvez joundre l'équipe.",
    JoinUsTitle: 'Nous Joindre',
    DaysOpen: 'Du lundi au vendredi',
    OpeningHours: 'De 8h à 18h',
    PhoneNumber: '1 877 644-4545',
    TollFreeNumber: '1 800 361-9596 (numéro ATS pour malentendants)',
    Copyright: '@ Gouvernement du Québec',
  },
  StatusMessages: {
    InitAgent: "Initialisation de l'agent ...",
  },
  TermsV2: {
    ProgressBarText: "1. Conditions d'utilisation",
    Consent: {
      title: 'Consentement',
      body: "Les conditions d'utilisation ci-présente sont seulement à titre d'exemple. Les conditions québécoise sont en cours de rédaction.",
      PersonalUse: {
        title: 'Usage personnel exclusif',
        body: "Vous êtes responsable de la confidentialité de votre portefeuille numérique. Vous devez le réaliser à votre usage exclusif. Ne divulguez à personne votre code d'accès et protégez adéquatement votre téléphone mobile. Des recommandations vous sont présentées dans la rubrique *Sécurité* .",
        subsection: {
          title: 'Utilisation acceptable',
          body: "Dans le cadre de votre utilisation de l'Application sous Licence, vous ne devez prendre aucune mesure susceptible de mettre en péril la sécurité, l'intégrité et/ou la disponibilité de l'Application sous Licence, y compris, sans s'y limiter :\n\nL’utilisation de l'Application sous Licence à des fins illégales ou inappropriées ;\n\nL’altération de toute partie de l'Application sous Licence ;\n\nL’utilisation de l'Application sous Licence pour transmettre tout virus ou tout autre code informatique, fichier ou programme nuisible ou destructeur, ou pour mener des activités de piratage et/ou d'intrusion ;\n\nTenter de contourner ou de subvertir toute mesure de sécurité associée à l'Application sous Licence ;\n\nEntreprendre toute action qui pourrait raisonnablement être interprétée comme susceptible d'affecter négativement les autres utilisateurs de l'Application sous Licence ;\n\nOù\n\nSupprimer ou modifier tout symbole ou avis de propriété, y compris tout avis de droit d'auteur, marque ou logo, affiché en relation avec l'Application sous Licence.",
        },
      },
      IdentityTheft: {
        title: "En cas de vol d'identité",
        body: "Si vous soupçonnez que la sécurité de votre portefeuille et de son contenu a été compromise , vous devez communiquer immédiatement  avec *le Service québécois d’identité numérique.* Vous ne serez pas tenu responsable en cas de vol d'identité, dans la mesure où vous respectez les présentes conditions.",
        subsection: {
          title: 'Indemnisation',
          body: 'Vous acceptez d’indemniser, de défendre et de dégager de toute responsabilité la province et tous ses fonctionnaires, employés et agents respectifs à l’égard de toutes les réclamations, demandes, obligations, pertes, passifs, coûts ou dettes et dépenses (y compris, sans s’y limiter, les frais juridiques raisonnables).\n\n Découlant :\n\n (a) de votre utilisation de l’Application sous licence ;\n\n Où\n\n (b) de votre violation de toute disposition du présent CLUF',
        },
      },
      Privacy: {
        title: 'Protection et confidentialité',
        body: 'Le gouvernement du Québec se préoccupe de la protection de votre vie privée et des renseignements personnels et confidentiels qui sont contenus dans cette application. Vous avez la responsabilité de consulter *la Politique de confidentialité pour connaitre les pratiques du gouvernements du Québec à ce sujet.*',
        subsection: {
          title: 'Protection des informations personnelles',
          body: "Si vous visitez le site Web de l’application sous licence à\n\nhttps://www.quebec.ca/gouvernement/ministere/cybersecurite-numerique,\n\nY compris pour accéder au Fonction d’aide pour l’application sous licence ou le contenu connexe à https://www.quebec.ca/gouvernement/ministere/cybersecurite-numerique, certaines informations vous seront fournies conformément à la Déclaration de confidentialité de la province pour les sites Web du gouvernement. Certains renseignements sont également recueillis dans le cadre de la demande de permis, comme il est indiqué dans la Politique de confidentialité de Quebec Wallet App (la « Politique de confidentialité »), qui est incorporée par renvoi dans le présent CLUF et en fait partie. Vous consentez à la collecte par l’Application sous licence de ces informations qui, avec votre Contenu, sont stockées localement sur votre appareil et n’est pas accessible à la province, sauf dans les cas où vous choisissez de fournir des renseignements à la province, comme il est indiqué dans la politique de confidentialité. Tous les renseignements que vous fournissez à la province qui sont des « renseignements personnels », au sens de la Loi sur l’accès à l’information et la protection de la vie privée du Québec (« la Loi »), sont recueillis par la province en vertu de l’alinéa 26c la Loi, aux fins énoncées dans la Politique de confidentialité. Toute question concernant la collecte de ces renseignements peut être adressée à la personne-ressource indiquée à l'article 11. Les consentements que vous avez fournis conformément au présent article seront maintenus jusqu'à ce que vous les révoquiez par écrit à la personne-ressource mentionnée à l'article 11, auquel cas le présent ALUF prendra fin immédiatement, conformément à l'article 9.",
        },
      },
      AppAccess: {
        title: "Droit d'accès à l'application",
        body: 'Le gouvernement du Québec se préoccupe de la protection de votre vie privée et des renseignements personnels et confidentiels contenus dans cette application. À cet effet, vous avez la responsabilité de consulter la * Politique de confidentialité * pour connaître les pratiques du gouvernement du Québec à cet égard.',
        subsection: {
          title: 'Limitation de la responsabilité',
          body: 'Dans la mesure où la loi applicable le permet, la Province ne sera en aucun cas en aucun cas, la Province ne sera responsable envers toute personne ou entité de toute perte, réclamation, blessure ou dommage direct, indirect, spécial, accessoire ou consécutif, ou de toute autre perte, réclamation, blessure ou dommage.\n\nSi prévisible ou imprévisible (y compris les demandes de limitation de dommages-intérêts pour perte de profits ou occasions d’affaires, l’utilisation ou l’utilisation abusive ou l’impossibilité d’utiliser , l’application sous licence , les interruptions , la suppression ou la corruption de fichiers , la perte de programmes ou d’informations , les erreurs, les défauts ou les retards ) découlant de votre utilisation de l’application sous licence ou y étant lié de quelque façon que ce soit, qu’il soit fondé sur un contrat, un délit, une responsabilité stricte ou toute autre théorie juridique. La phrase précédente s’appliquera même si la province a été expressément informée de la possibilité d’une telle perte, réclamation, blessure ou dommage. Les parties reconnaissent qu’Apple n’est pas responsable :\n\na) traiter toute réclamation que vous ou un tiers de quelque nature que ce soit relativement à la demande autorisée;\n\nb) votre possession et/ou utilisation de la demande de permis.',
        },
      },
      More: {
        body: 'En savoir plus sur *ces conditions générales(*)*',
      },
    },
  },
  PINCreate: {
    UserAuthenticationPin: "NIP d'authentification de l'utilisateur",
    PinMustBe6DigitsInLength: 'Le NIP doit être composé de 6 chiffres',
    PinsEnteredDoNotMatch: 'Les NIP saisis ne correspondent pas',
    '6DigitPin': 'NIP à 6 chiffres',
    ReenterPin: 'Saisir le NIP à nouveau',
    Create: 'Créer',
    PINTooShort: 'Le NIP doit contenir 6 chiffres',
    InvalidPIN: "Le NIP n'est pas valide",
    PINsDoNotMatch: 'Les NIP ne correspondent pas',
    PleaseUseOnlyNumbersInYourPIN: 'Le NIP doit contenir 6 chiffres',
    YourPINMustBe6DigitsInLength: 'Le NIP doit contenir 6 chiffres',
    EnteredPINsDoNotMatch: 'Les NIP ne sont pas identiques. Veuillez essayer de nouveau.',
    YouNeedToCreateA6DigitPIN: 'Veuillez créer un NIP à 6 chiffres',
    PleaseReenterYourPIN: 'Veuillez saisir le NIP de nouveau',
    EnterPINTitle: 'Veuillez saisir un NIP à 6 chiffres',
    EnterPIN: 'Veuillez saisir un NIP à 6 chiffres',
    ReenterPIN: 'Veuillez saisir à nouveau votre NIP',
    CreatePIN: 'Veuillez créer un NIP à 6 chiffres',
    ReenterPINTitle: 'Veuillez saisir à nouveau votre NIP',
    RememberPIN: "Ne pas oublier votre numéro d'identification personnel (NIP).",
    Warning: "Il n'y a aucun moyen de le récupérer. Si vous l'oubliez, vous devrez :",
    BulletPoint1: 'Configurer votre portefeuille à nouveau',
    BulletPoint2: 'Demander de nouveau les attestations déjà émises dans votre portefeuille',
    MoreInformation: 'En savoir plus sur le NIP.',
    PINDisclaimer:
      'Si vous oubliez votre NIP, vous devrez configurer votre application et ajouter vos cartes à nouveau.',
    Show: 'Afficher le NIP',
    Hide: 'Masquer le NIP',
    ChangePIN: 'Modifier le NIP',
    Continue: 'Continuer',
    EnterYourCurrentPIN: 'Veuiller saisir votre NIP',
    PinChangeSuccessTitle: 'Changement de NIP réussi',
    PinChangeSuccessMessage:
      'Votre NIP a été changé avec succès. Vous pouvez maintenant vous connecter avec votre nouveau NIP.',
    EnterOldPINTitle: 'Entrez votre ancien NIP',
    NewPIN: 'nouveau',
    RememberChangePIN: 'Changez votre NIP pour sécuriser votre portefeuille.',
    Message: {
      CrossPatternValidation: 'Votre NIP contient une séquence en forme de croix. Veuillez choisir un autre NIP.',
      OddOrEvenSequenceValidation: 'Votre NIP contient une suite paire ou impaire. Veuillez choisir un autre NIP. ',
      NoRepetitionOfTheTwoSameNumbersValidation:
        'Votre NIP contient une répétition de deux chiffres (p. ex.: 1212). Veuillez choisir un autre NIP.',
      NoRepetitionOfTheSameNumbersValidation:
        'Votre NIP contient une répétition de trois (3) chiffres (p. ex.: 222). Veuillez choisir un autre NIP. ',
      NoSeriesOfNumbersValidation: 'Une série de nombres consécutifs a été détectée dans votre NIP.',
      PINOnlyContainDigitsValidation: 'Votre NIP doit contenir six (6) chiffres. Veuillez choisir un nouveau NIP.',
      PINTooShortValidation: 'Votre NIP doit contenir six (6) chiffres. Veuillez choisir un nouveau NIP.',
      PINTooLongValidation: 'Votre NIP doit contenir six (6) chiffres. Veuillez choisir un nouveau NIP.',
      AncienPINIncorrect: 'Votre ancien NIP est incorrect. Veuillez réessayer.',
      OldPINIncorrect: "L'ancien NIP est incorrect. Veuillez réessayer.",
    },
    Helper: {
      CrossPatternValidation: 'Ne doit pas contenir une séquence en forme de croix.',
      OddOrEvenSequenceValidation: 'Ne doit pas contenir de série paire ou impaire.',
      NoRepetitionOfTheTwoSameNumbersValidation: 'Ne doit pas contenir de répétition de deux chiffres. (ex: 1212)',
      NoRepetitionOfTheSameNumbersValidation: 'Ne doit pas contenir de répétition. (ex: 222)',
      NoSeriesOfNumbersValidation: 'Ne doit pas contenir de série. (ex: 123)',
      PINOnlyContainDigitsValidation: 'Doit contenir des chiffres seulement.',
      PINTooShortValidation: 'Votre NIP doit contenir 6 chiffres.',
      PINTooLongValidation: 'Votre NIP doit contenir 6 chiffres.',
    },
    ProgressBarText: '2. Sécuriser le portefeuille',
  },
  AttemptLockout: {
    Title: 'Votre portefeuille est temporairement verrouillé ',
    Description: "Trop d'essais ont été tentés lors de la saisie de votre NIP ",
    TryAgain: 'Vous pouvez réessayer dans :',
    Hours: 'heures',
    Minutes: 'minutes',
    Seconds: 'secondes',
  },
  ContactDetails: {
    Created: 'Créé',
    ConnectionState: 'État de la connexion',
    AContact: 'Un contact',
    DateOfConnection: 'Date de connexion : {{ date }}',
    RemoveTitle: 'Supprimer ce contact',
    RemoveCaption: "Pour ajouter des attestations, l'organisation émettrice doit figurer parmi vos contacts.",
    UnableToRemoveTitle: 'Impossible de supprimer le contact',
    UnableToRemoveCaption:
      "Impossible de supprimer, car il y a des attestations émises par ce contact dans votre portefeuille. Supprimez d'abord les attestations, puis supprimez ce contact.",
    GoToCredentials: 'Accéder aux attestations',
    ContactRemoved: 'Contact supprimé',
    RemoveContactMessageTop: 'En supprimant ce contact, vous ne pourrez plus :',
    RemoveContactMessageBottom: "Ce contact ne sera pas informé que vous l'avez supprimé de vos contacts.",
    RemoveContactsBulletPoint1: 'Envoyez un message à ce contact.',
    RemoveContactsBulletPoint2: "Obtenez de nouvelles attestations d'identité de ce contact.",
    RemoveContactsBulletPoint3:
      "Soyez informé des mises à jour de vos informations d'identification émises par ce contact.",
    RemoveContactsBulletPoint4: 'Demander des informations à ce contact ou celui-ci vous demande des informations.',
    RemoveContact: 'Supprimer le contact',
    GoToCredentialDetail: "Aller au détail de l'attestation",
    CredentialName: "Nom de l'attestation",
    Credentials: 'Mes attestations avec ce contact',
    NoCredentials: "Vous n'avez aucune attestation de ce contact.",
  },
  WhatAreContacts: {
    Title: "Qu'est-ce qu'un contact?",
    Preamble: "L'ajout d'organisations en tant que contact vous permettra de:",
    ListItemCredentialUpdates: 'Obtenir des mises à jour des attestations émises par cette organisation.',
    ListItemNewCredentials: "Obtenir de nouvelles attestations d'identité.",
    ListItemProofRequest: "Demandes d'attestations accélérées.",
    RemoveContacts: 'Vous pouvez à tout moment supprimer des contacts de votre  liste. ',
    ContactsLink: 'liste de contacts',
    ContactSharing: "L'utilisation de vos justificatifs d'identité n'est jamais partagée avec vos contacts.",
    ListItemDirectMessage: 'Envoyer un message direct à vos contacts',
    ListItemNotifiedOfUpdates: 'Être informé des mises à jour de vos attestations émises par eux',
    ListItemRequest: "Demander des informations à votre contact ou qu'il vous demande des informations",
  },
  Contacts: {
    EmptyList: 'Votre portefeuille est vide. Vos contacts connectés seront ajoutés ici.',
    TypeHere: 'Saisissez votre message ici.',
    PeopleAndOrganizations:
      'Les personnes et les organisations avec lesquelles vous avez interagi sont répertoriées ici.',
    WhatAreContacts: "Qu'est-ce que les contacts?",
    AddContact: 'Ajouter un contact',
  },
  CredentialDetails: {
    Id: 'Identifiant :',
    CreatedAt: 'Créé à :',
    Version: 'Version',
    Issued: 'Délivré',
    PrivacyPolicy: 'Politique de confidentialité',
    TermsAndConditions: "Conditions d'utilisation",
    RemoveFromWallet: 'Retirer du portefeuille',
    Revoked: 'Révoqué',
    Choose: 'Choisir',
    GetPersonCred: "Obtenez votre attestation d'identité",
    ScanQrCode: 'Balayer un code QR',
    CredentialRevokedMessageTitle: 'Cette attestation est révoquée',
    CredentialRevokedMessageBody:
      "Cette attestation peut ne plus fonctionner pour certaines demandes de preuve. Le cas échéant, vous devrez mettre à jour l'attestation avec l'émetteur.",
    NewRevoked: 'Attestation révoquée',
    RemoveTitle: "Retirer l'attestation du portefeuille",
    RemoveCaption: 'Vous ne pourrez plus prouver les informations de cette attestation avec ce portefeuille.',
    CredentialNotFound: 'Attestation non trouvée',
    CredentialRemoved: 'Attestation retirée',
    IssuedBy: 'Attestation émise par:',
    RemoveCredential: "Supprimer l'attestation",
    YouWillNotLose: 'Vous ne perdrez pas',
    YouWillNotLoseListItem1: 'Votre attestation dans le système qui vous a délivré votre attestation.',
    YouWillNotLoseListItem2: "L'organisation émettrice en tant que contact.",
    HowToGetThisCredentialBack: 'Comment récupérer cette attestation',
    HowToGetThisCredentialBackListItem1:
      'Vous devrez vous rendre auprès de l’organisation qui vous a délivré cette attestation et la demander à nouveau.',
  },
  Home: {
    Welcome: 'Bonjour!',
    ScanQrCode: 'Balayer un code QR',
    NotificationTitle: 'Nouvelles activités',
    Notification: 'Notification',
    Notifications: 'Notifications',
    OneNotification: '1 Notification',
    CountNotifications: '{{ count }} Notifications',
    NoNewUpdates: "Vous n'avez pas de nouvelles notifications.",
    NoCredentials: "Vous n'avez pas d'attestation dans votre portefeuille.",
    SeeAll: 'Voir toutes les notifications',
    YouHave: 'Vous avez',
    Credential: 'attestation',
    Credentials: 'attestations',
    InYourWallet: 'dans votre portefeuille',
    NewMessage: 'Nouveau message',
    SentMessage: 'a envoyé un message',
    ReceivedMessage: 'Vous avez reçu un nouveau message',
    ViewMessage: 'Voir le message',
    SentCredential: "a envoyé une offre d'attestation",
    ReceivedCredential: 'Vous avez reçu une nouvelle attestation',
  },
  Notifications: {
    Dismiss: 'Supprimer',
  },
  Activities: {
    Timing: {
      Today: 'Aujourd’hui',
      ThisWeek: 'Cette semaine',
      LastWeek: 'La semaine dernière',
      Older: 'Plus ancien',
    },
    FooterNothingElse: "Il n'y a rien d'autre",
    NotificationsDeleted_one: '{{ count }} notification supprimée.',
    NotificationsDeleted_other: '{{ count }} notifications supprimées.',
  },
  PrivacyPolicy: {
    Title: 'Politique de confidentialité',
    CameraDisclosure:
      "La caméra est utilisée pour scanner les codes QR pour un traitement immédiat sur l'appareil. Aucune information sur les images n'est stockée, utilisée à des fins d'analyse ou partagée.",
  },
  Scan: {
    SuccessfullyAcceptedConnection: 'Connexion acceptée avec succès',
    AcceptingConnection: 'Acceptation de la connexion',
    ConnectionRecordIdNotFound: "Identifiant de l'enregistrement de connexion introuvable",
    ConnectionAccepted: 'Connexion acceptée',
    ConnectionNotFound: 'Connexion non détectée',
    InvalidQrCode: 'Code QR invalide. Veuillez réessayer.',
    UnableToHandleRedirection: 'Impossible de traiter la redirection',
    Close: 'Fermer',
    Torch: 'Flash',
    ScanHelp: 'Aide à la numérisation',
    ScanNow: 'Numériser maintenant',
    WhatToScan: 'Quels codes QR peuvent être scannés ?',
    ScanOnySpecial: 'Seuls certains codes QR spéciaux peuvent être scannés par le portefeuille.',
    ScanOnlySpecial2:
      "Ces codes QR sont présentés par des services ou des personnes qui souhaitent recevoir une offre d'attestation, une demande d'informations ou pour se connecter.",
    ScanOnlySpecial3:
      "Le portefeuille ne prend actuellement pas en charge l'ajout d'attestations numériques en scannant ou en prenant des photos de cartes physiques.",
    WhereToUseLink: 'Découvrez où vous pouvez utiliser le portefeuille',
    BadQRCode: 'QR Code non reconnu',
    BadQRCodeDescription:
      "Le QR code scanné ne fonctionne pas avec le portefeuille. Le portefeuille ne fonctionne qu'avec les services participants.\n\nIl ne peut actuellement pas ajouter des attestations numériques en prenant des photos de cartes physiques.",
    WillScanAutomatically: 'Un code QR valide sera scanné automatiquement.',
    ScanQRCode: 'Scanner le code QR',
    MyQRCode: 'Mon code QR',
  },
  Connection: {
    JustAMoment: 'Veuillez patienter pendant que nous établissons une connexion sécurisée...',
    TakingTooLong:
      "L'opération prend plus de temps que prévu. Vous pouvez retourner à l'accueil ou continuer à patienter.",
    ConnectionInvitation: "Demande d'invitation à la connexion",
    ScanQR: 'Balayer le code QR',
    ScanQRComment: 'avec votre portefeuille numérique pour établir une connexion.',
    MakingConnection: 'Connexion en cours...',
    ConnectionCompleted: 'Connexion établie!!',
    Toggle: "Activer la fonctionnalité d'invitation à la connexion",
    UseConnectionInviterCapability: "Utiliser la fonctionnalité d'invitation à la connexion ?",
    OpenContact: 'Ouvrir le contact',
    ShareQR: "Partager ce code QR avec quelqu'un l'ajoutera en tant que contact.",
  },
  CredentialOffer: {
    ThisIsTakingLongerThanExpected:
      'Cette opération prend plus de temps que prévu. Revenez plus tard pour obtenir votre nouvelle attestation.',
    'RejectThisCredential?': 'Souhaitez-vous rejeter cette attestation?',
    AcceptingCredential: "Acceptation de l'attestation",
    SuccessfullyAcceptedCredential: 'Attestation acceptée avec succès',
    RejectingCredential: "Rejet de l'attestation",
    SuccessfullyRejectedCredential: 'Attestation rejetée avec succès',
    CredentialNotFound: 'Attestation introuvable',
    CredentialAccepted: 'Attestation acceptée',
    CredentialRejected: 'Attestation rejetée',
    CredentialAddedToYourWallet: 'Attestation ajoutée à votre portefeuille',
    CredentialDeclined: 'Attestation refusée',
    CredentialOnTheWay: 'Votre attestation est en cours de transmission',
    CredentialOffer: "Nouvelle offre d'attestation",
    IsOfferingYouACredential: 'vous propose un attestation',
    ConfirmDeclineCredential: 'Oui, refuser cette attestation',
    AbortDeclineCredential: 'Non, revenir en arrière',
    DeleteOfferTitle: 'Supprimer cette offre ?',
    DeleteOfferMessage: 'La suppression de cette offre supprimera la notification de votre liste.',
    DeleteOfferDescription:
      "Vous ne reconnaissez pas l'organisation? Veuillez vérifier votre liste de contacts. Vous recevez des notifications seulement de la part des contacts avec qui vous avez établi une connexion (p. ex.: Gouvernement du Québec).",
    NewCredentialOffer: "Nouvelle offre d'attestation",
    ConfirmDeclinedTitle: 'Êtes-vous sûr de vouloir refuser cette attestation?',
    ConfirmDeclinedMessage:
      "Afin de recevoir à nouveau cette attestation, vous devrez formuler une nouvelle demande auprès de l'émetteur.",
    ConfirmDecline: "Oui, refuser l'attestation",
    AbortDecline: 'Non, revenir en arrière',
    DeclineTitle: "Refuser l'attestation?",
    Declined: 'Refusé',
    DeclineParagraph1:
      "Afin de recevoir à nouveau cette attestation, vous devrez recommencer la procédure d'émission en communiquant avec l'émetteur.",
    DeclineParagraph2: 'Êtes-vous sûr de vouloir refuser cette attestation?',
    CustomOfferTitle: 'Supprimer cette offre?',
    CustomOfferParagraph1: 'En supprimant cette offre, vous supprimez la notification de votre liste.',
    CustomOfferParagraph2:
      "Vous ne reconnaissez pas l'émetteur? Vérifiez votre liste de contacts. Seuls les contacts qui y figurent peuvent vous envoyer des notifications.",
  },
  ConnectionAlert: {
    AddedContacts: 'Nouveau contact ajouté',
    WhatAreContacts: 'Que sont les contacts ?',
    NotificationBodyUpper: 'Vouz pouvez trouver ',
    NotificationBodyLower: ' dans vos contacts. Gérer vos contacts dans les paramètres.',
    PopupIntro: "L'ajout d'organisations aux contacts vous permettra d': ",
    PopupPoint1: 'Obtenir les mises à jour des attestations délivrées par cette organisation.',
    PopupPoint2: 'Obtenir de nouvelles attestations',
    PopupPoint3: 'Demandes de preuves accélérées',
    SettingsLink: 'Paramètres',
    SettingsInstruction: 'Vous pouvez à tout moment supprimer des contacts dans ',
    PrivacyMessage: "L'utilisation de vos attestations n'est jamais partagée avec vos contacts.",
    PopupExit: "J'ai compris",
  },
  ProofRequest: {
    FromYourWallet: 'à partir de votre portefeuille',
    MissingCredentials: 'Attestations manquantes',
    PredicateGeDate: 'est après le',
    PredicateLeDate: 'est avant le',
    PredicateGe: 'est supérieur ou égal à',
    PredicateGr: 'est supérieur à',
    PredicateLe: 'est inférieur ou égal à',
    PredicateLs: 'est inférieur à',
    ChangeCredential: "Changer l'attestation",
    'DeclineThisProof?': 'Refuser cette demande de preuve?',
    MultipleCredentials: 'Vous avez plusieurs attestations parmi lesquelles choisir :',
    OfferDelay: "Retard de l'offre",
    'RejectThisProof?': 'Rejeter cette preuve?',
    AcceptingProof: 'Acceptation de la preuve',
    SuccessfullyAcceptedProof: 'Preuve acceptée avec succès',
    ProofNotFound: 'Preuve introuvable',
    RejectingProof: 'Rejet de la preuve',
    ProofAccepted: 'Preuve acceptée',
    ProofRejected: 'Preuve rejetée',
    RequestedCredentialsCouldNotBeFound: "Les attestations demandées n'ont pas été trouvées",
    ProofRequest: 'Nouvelle demande de preuve',
    NotAvailableInYourWallet: 'Non disponible dans votre portefeuille',
    IsRequesting: 'demande',
    IsRequestingSomethingYouDontHaveAvailable: "demande une information que vous n'avez pas à votre disposition",
    IsRequestingYouToShare: 'vous demande de partager',
    WhichYouCanProvideFrom: 'que vous pouvez fournir à partir de',
    Details: 'Détails',
    SendingTheInformationSecurely: "Envoi sécurisé de l'information",
    InformationSentSuccessfully: 'Informations envoyées avec succès',
    ProofRequestDeclined: 'Demande de preuve refusée',
    RequestProcessing: "Un instant, s'il vous plaît...",
    ProofRequestNotFound: 'Demande de preuve non trouvée',
    NewProofRequest: 'Nouvelle demande de preuve',
    Credential: 'Attestation.',
    Credentials: 'Attestations.',
    NewProof: 'Nouvelle preuve',
    ConfirmDeclinedTitle: 'Êtes-vous sûr de vouloir refuser cette demande de preuve ?',
    ConfirmDeclinedMessage:
      'Pour recevoir la demande de preuve, {nom du vérificateur} doit vous envoyer une nouvelle demande de connexion.',
    ConfirmDecline: 'Oui, refuser cette demande de preuve',
    AbortDecline: 'Non, revenir en arrière',
    DeclineTitle: 'Refuser la demande de preuve?',
    Declined: 'Refusé',
    ShareFollowingInformation: "Partage les informations suivantes à partir de l'attestation {{count}}.",
    ShareFollowingInformation_one: "partage les informations suivantes à partir de l'attestation {{count}}.",
    ShareFollowingInformation_other: "partage les informations suivantes à partir de l'attestation {{count}}.",
    DeclineBulletPoint1:
      "Vous devez prouver que vous êtes admissible auprès de l'organisation {nom de l'organisation} pour accéder à un service.",
    DeclineBulletPoint2:
      "Afin de recevoir à nouveau la demande de preuve, vous devrez recommencer le processus en communiquant avec l'organisation émettrice (émetteur, le service…).",
    DeclineBulletPoint3: 'Etes-vous sûr de vouloir refuser cette demande de preuve?',
    SensitiveInformation: 'Cette demande nécessite des informations sensibles.',
    PredicateNotSatisfied: 'Condition non satisfaite',
    YouDoNotHaveDataPredicate: 'Vous ne répondez pas aux exigences de cette demande de preuve de',
    ReviewSentInformation_one: 'Vous avez partagé les informations suivantes de {{count}} attestation avec',
    ReviewSentInformation_other: 'Vous avez partagé les informations suivantes de {{count}} attestations avec',
    ReviewSentInformation: 'Vous avez partagé les informations suivantes de {{count}} attestations avec',
  },
  TabStack: {
    Home: 'Accueil',
    Activities: 'Activités',
    Credentials: 'Attestations',
    OptionsPlus: 'Plus',
  },
  RootStack: {
    Contacts: 'Contacts',
    Settings: "Paramètres de l'application",
  },
  QRScanner: {
    PermissionToUseCamera: "Autorisation d'utiliser l'appareil photo",
    WeNeedYourPermissionToUseYourCamera: 'Nous avons besoin de votre autorisation pour utiliser votre appareil photo.',
    Ok: 'Ok',
  },
  QRRender: {
    GenerationError: 'Impossible de générer le code QR',
  },
  Record: {
    Hide: 'Masquer',
    Show: 'Afficher',
    HideAll: 'Masquer tout',
    Hidden: 'Masqué',
    ShowAll: 'Afficher tout',
    InvalidDate: 'Date invalide: ',
    Zoom: 'Zoom',
  },
  Loading: {
    TakingTooLong:
      "La tentative de connexion prend plus de temps que prévu. Vous pouvez retourner à l'accueil ou continuer à patienter.",
    BackToHome: "Retour à l'accueil",
  },
  NameWallet: {
    EnableWalletNaming: 'Activer le nommage du portefeuille ?',
    ToggleWalletNaming: 'Basculer le nommage du portefeuille',
    NameYourWallet: 'Nommez votre portefeuille',
    EditWalletName: 'Modifier le nom du portefeuille',
    ThisIsTheName: "Ceci est le nom que les gens voient lorsqu'ils se connectent avec vous.",
    CharCountTitle: 'Nombre de caractères dépassé',
    CharCountDescription:
      'Vous avez dépassé le nombre maximum de 50 caractères. Veuillez réduire votre nombre de caractères.',
    EmptyNameTitle: 'Le nom du portefeuille ne peut pas être vide',
    EmptyNameDescription:
      "Ceci est le nom que les gens voient lorsqu'ils se connectent avec vous.\n\nVeuillez entrer un nom de portefeuille.",
  },
  Screens: {
    Splash: 'Page de garde',
    Onboarding: 'Introduction',
    Preface: 'Portefeuille QC',
    Terms: "Conditions d'utilisation",
    CreatePin: 'Créer un NIP à 6 chiffres',
    EnterPin: 'Saisir le NIP',
    Home: 'Accueil',
    Scan: 'Lire un code QR',
    Credentials: 'Attestations',
    OptionsPlus: "Plus d'options",
    HelpCenter: "Centre d'aide",
    About: 'À propos',
    CredentialDetails: 'Détails des attestations',
    Notifications: 'Notifications',
    History: 'Historique',
    CredentialOffer: "Proposition d'attestation",
    ProofRequest: 'Demande de preuve',
    ProofChangeCredential: "Changer l'attestation",
    ProofRequestAttributeDetails: 'Détails des attributs de la demande de preuve',
    Settings: 'Paramètres',
    Language: 'Langue',
    Contacts: 'Contacts',
    ContactDetails: 'Informations du contact',
    ProofRequestDetails: 'Informations de la demande de preuve',
    ProofDetails: 'Informations de la preuve',
    Tours: "Guides d'application",
    Decline: 'Refuser',
    Biometry: 'Biométrie',
    Developer: 'Options de développeur',
    ChangePIN: 'Changer le NIP',
    CommonDecline: 'Refuser',
    ProofRequests: 'Demandes de preuve',
    SendProofRequest: 'Envoyer une demande de preuve',
    ChooseProofRequest: 'Choisissez une demande de preuve',
    ProofRequestUsageHistory: "Historique d'utilisation",
    ConnectionInvitation: 'Invitation de connexion',
    CreateConnectionInvitation: 'Créer une invitation de connexion',
    AttemptLockout: 'Temporairement verrouillé',
    OnTheWay: 'En cours de transmission',
    Declined: 'Refusé/e',
    UseBiometry: 'Utiliser la biométrie',
    RecreatePIN: 'Changer le NIP',
    CustomNotification: 'Notification personnalisée',
    ProofRequesting: 'Demande de preuve',
    NameWallet: 'Nommer le portefeuille',
    CreatePIN: 'Créer un NIP',
    EnterPIN: 'Entrer le NIP',
    DataRetention: 'Conservation des données',
    RenameContact: 'Renommer le contact',
  },
  OnboardingPages: {
    FirstPageTitle: 'Bienvenue dans le portefeuille numérique du Québec',
    FirstPageBody1:
      'Le portefeuille Québec vous permet de recevoir, enregistrer et utiliser vos attestations numériques.',
    FirstPageBody2: 'Cette application est sécurisée et aide à protéger votre confidentialité en ligne.',
    FirstPageBody3:
      "Le portefeuille québécois en est actuellement aux premiers stades de développement et la technologie est en cours d'exploration. La plupart des gens n'auront pas besoin du portefeuille numérique, car il n'y a que quelques justificatifs d'identité actuellement disponibles.",
    SecondPageTitle: 'Une attestation numérique, enregistrée secrètement',
    SecondPageBody:
      'Le portefeuille Québec protège vos attestations numériques, une version digitale de vos permis et cartes d’identité.\n\nElles sont enregistrées de manière sécurisée, seulement sur votre appareil.',
    ThirdPageTitle: 'Partager uniquement ce qui est nécessaire',
    ThirdPageBody:
      'Pour recevoir une attestation, vous devez lire le code QR qui vous sera présenté. \n\nLes informations seront communiquées grace à une communication privée et protégée.',
    FourthPageTitle: 'Prenez le contrôle de vos informations',
    FourthPageBody:
      'Vous avez le contrôle sur les informations qui sont partagées et utilisées depuis votre portefeuille Québec. Vous ne partagez que les informations requises selon la situation. \n\nLe gouvernement du Québec n’est jamais mis au courant des interactions réalisées lorsque vous utilisez une attestation numérique.',
    ButtonGetStarted: 'Configurer le portefeuille',
  },
  RenameContact: {
    ThisContactName: "Ce nom de contact n'est affiché que dans votre liste de contacts.",
    ContactName: 'Nom du contact',
    CharCountTitle: 'Dépassement de la limite de caractères',
    CharCountDescription:
      'Vous avez dépassé la limite maximale de 50 caractères. Veuillez réduire le nombre de caractères.',
    EmptyNameTitle: 'Le nom du contact ne peut pas être vide',
    EmptyNameDescription:
      "C'est le nom que vous verrez pour ce contact dans votre liste de contacts.\n\nVeuillez entrer un nom de contact.",
  },
  NetInfo: {
    NoInternetConnectionTitle: 'Pas de connexion Internet',
    NoInternetConnectionMessage:
      "Vous ne pouvez pas accéder aux services à l'aide du portefeuille numérique, ni recevoir d'attestations tant que vous ne serez pas de nouveau en ligne.\n\nVeuillez vérifier votre connexion Internet.",
    LedgerConnectivityIssueTitle: 'Services de portefeuille',
    LedgerConnectivityIssueMessage:
      "Il se peut qu'un pare-feu vous empêche de vous connecter aux services liés au portefeuille.",
  },
  Settings: {
    Help: 'Aide',
    Preference: 'Préférences',
    History: 'Historique',
    Days: 'Jours',
    Security: 'Sécurité',
    Biometrics: 'Biométrie',
    BiometricActive: 'Activé',
    BiometricDisabled: 'Désactivé',
    Notification: 'Notifications',
    AppTheme: "Thème de l'application",
    MoreInformation: "Plus d'information",
    HelpUsingBCWallet: "Aide à l'utilisation du portefeuille numérique de la C.-B.",
    ReportAProblem: 'Signaler un problème',
    TermsOfUse: "Conditions d'utilisation",
    PrivacyStatement: 'Déclaration de confidentialité',
    VulnerabilityDisclosurePolicy: 'Politique de divulgation des vulnérabilités',
    Accessibility: 'Accessibilité',
    IntroductionToTheApp: "Introduction de l'application",
    Version: "Version de l'application",
    VersionString: '0.0.0-0',
    AppPreferences: "À propos de l'application : Préférences ",
    AboutApp: "À propos de l'application",
    Language: "Langue d'affichage",
    AppSettings: "Paramètres de l'application",
    WhatAreContacts: 'Qu’est-ce qu’un contact?',
    Developer: 'Fonctionnalité développeur',
    AppGuides: "Guides de l'application",
    Build: 'Créer',
    GiveFeedback: 'Donner votre avis',
    ChangePin: 'Modifier',
    MyPin: 'Mon NIP',
    DataRetention: 'Conservation des données',
    PreventAutoLock: 'Empêcher le verrouillage automatique',
    TogglePreventAutoLock: 'Basculer le verrouillage automatique',
    ScanMyQR: 'Scanner mon code QR',
    PlayWithBCWallet: 'Jouer avec le Portefeuille Québec',
    ForcedUpdates: 'Utiliser la mise à jour forcée',
    ToggleForcedUpdates: 'Basculer la mise à jour forcée',
  },
  Tour: {
    GuideTitle: 'Bienvenue au Portefeuille numérique',
    WouldYouLike: "Souhaitez-vous obtenir des conseils sur la façon d'utiliser le Portefeuille numérique?",
    UseAppGuides: 'Utiliser les conseils',
    DoNotUseAppGuides: 'Ne pas utiliser les conseils',
    AddAndShare: 'Ajouter et partager des attestations',
    AddAndShareDescription:
      'Pour ajouter et utiliser des attestations, vous devez balayer le code QR affiché par le fournisseur de services.',
    Notifications: 'Notifications',
    NotificationsDescription:
      "Après avoir balayé le code QR, l'offre d'attestation ou la demande de preuve ainsi que d'autres événements notables apparaîtront ici .",
    YourCredentials: 'Vos attestations',
    YourCredentialsDescription:
      "Vos nouvelles attestations d'identité numériques apparaissent ici. Vous pouvez réviser, ajouter et supprimer vos attestations.",
    Skip: 'Ignorer',
    Next: 'Suivant',
    Back: 'Précédent',
    Done: 'Terminer',
    AddCredentials: 'Ajouter des justificatifs',
    AddCredentialsDescription: 'Ajoutez des justificatifs en balayant un code QR affiché sur le service émetteur.',
    CredentialOffers: 'Offres de justificatifs',
    CredentialOffersDescription:
      "Une organisation vous a offert un justificatif. Examinez les détails du justificatif et choisissez de l'accepter ou de le refuser. Les justificatifs acceptés seront ajoutés à votre portefeuille.",
    ProofRequests: 'Demandes de preuve',
    ProofRequestsDescription:
      "Une organisation vous demande de prouver vos justificatifs. Examinez ce qu'ils demandent et choisissez de l'accepter ou de le refuser.",
  },
  Tips: {
    Header: 'Conseils',
    GettingReady: 'Préparez votre portefeuille...',
    Tip1: "Par souci de sécurité, l'application du portefeuille numérique du Québec se verrouille après 5 minutes d'inactivité.",
    Tip2: 'Contrairement à la présentation de cartes physiques, vous ne partagez que ce qui est nécessaire à partir de vos justificatifs',
    Tip3: 'Vos justificatifs sont stockés uniquement sur ce téléphone, nulle part ailleurs',
    Tip4: "Les informations sont envoyées et reçues par l'entremise d'une connexion cryptée intraçable.",
    Tip5: "N'oubliez pas votre NIP. Si vous l'oubliez, vous devrez réinstaller et rajouter vos attestations",
    Tip6: "Ignorez le code NIP et déverrouillez votre portefeuille à l'aide de vos données biométriques pour une navigation plus rapide.",
    Tip7: 'Vos attestations les plus récemment ajoutées sont placés en haut de la liste.',
    Tip8: "Supprimez les attestations de votre portefeuille à partir de l'écran des attestations.",
    Tip9: "Vous pouvez ignorer les notifications sans les ouvrir en cliquant sur le bouton  'X' dans le coin supérieur droit.",
    Tip10: "Besoin d'aide? Trouvez des réponses dans la section d'aide du bouton '☰' dans le coin supérieur gauche",
    Tip11: "Vous pouvez activer le flash de l'appareil photo en cas de problème de lecture du code QR .",
    Tip12: "Si le code QR ne se balaie pas, essayez d'augmenter la luminosité de l'écran.",
    Tip13:
      "Les informations envoyées par l'intermédiaire de votre portefeuille sont fiables pour vous et pour les contacts avec lesquels vous communiquez.",
    Tip14:
      "Même les attestations d'identité révoquées ou expirées peuvent être utilisées si l'organisation n'en fait pas la demande.",
  },
  Preface: {
    PrimaryHeading: 'Cette application est-elle pour vous ?',
    Paragraph1:
      "La plupart des gens n'auront pas besoin le portefeuille numérique car très peu d'attestations numériques sont actuellement disponibles.",
    Confirmed: "J'ai confirmé que cette application est pour moi.",
  },
  Chat: {
    OpenItem: 'Ouvrir',
    UserYou: 'Vous avez',
    CredentialProposalSent: "envoyé une proposition d'attestation",
    CredentialOfferReceived: "envoyé une offre d'attestation",
    CredentialRequestSent: "refusé une offre d'attestation",
    CredentialDeclined: "refusé une offre d'attestation",
    CredentialReceived: 'reçu une attestation',
    ProofRequestSent: 'envoyé une demande de preuve',
    ProofPresentationReceived: 'vous a envoyé des informations',
    ProofRequestReceived: 'reçu une demande de preuve',
    ProofRequestRejected: 'rejeté une demande de preuve',
    ProofRequestRejectReceived: 'rejeté une demande de preuve',
    ProofRequestSatisfied: 'informations partagées',
    OpenPresentation: 'Ouvrir la présentation',
    ViewRequest: 'Voir la demande',
    ViewOffer: "Voir l'offre",
    YouConnected: 'Vous êtes connecté avec',
  },
  Init: {
    Retry: 'Réessayer',
    Starting: 'Débuter...',
    CheckingAuth: 'Vérification de l’authentification...',
    FetchingPreferences: 'Récupération des préférences...',
    VerifyingOnboarding: "Vérification de l'intégration...",
    GettingCredentials: 'Récupération des attestations...',
    RegisteringTransports: 'Enregistrement des transports...',
    InitializingAgent: 'Initialisation de l’agent...',
    CacheWarmup: 'Récuperation de la mémoire du cache...',
    ConnectingLedgers: 'Connexion aux fichiers...',
    SettingAgent: 'Configuration de l’agent...',
    Finishing: 'Finalisation...',
  },
  Feedback: {
    GiveFeedback: 'Donnez votre avis',
  },
  PINEnter: {
    Title: 'Portefeuille numérique du Québec',
    EnterPIN: 'Veuiller saisir votre NIP',
    Unlock: 'Déverrouiller',
    Or: 'Ou',
    BiometricsUnlock: 'Déverrouiller avec la biométrie',
    LoggedOutDescription:
      "Pour protéger vos informations, vous êtes déconnecté de votre portefeuille si vous ne l'avez pas utilisé pendant 5 minutes.",
    AttemptLockoutWarning:
      "Note: pour votre sécurité, la saisie d'un autre code NIP incorrect verrouillera temporairement le portefeuille.",
    IncorrectPIN: ' NIP erroné',
    EnableBiometrics: 'Vous devez activer la biométrie pour utiliser le portefeuille.',
    BiometricsNotProvided: 'La biométrie est indisponible. Veuillez saisir le NIP du portefeuille.',
    BiometricsError: 'Échec de la biométrie.',
    BiometricsErrorEnterPIN: 'Veuillez saisir le NIP du portefeuille.',
    LockedOut: "Votre portefeuille a été verrouillé après {{ time }} minute(s) d'inactivité.",
    ReEnterPIN: 'Saisissez à nouveau votre NIP.',
    BiometricsChangedEnterPIN: 'Veuillez saisir le NIP du portefeuille.',
    RepeatPIN: 'Essayez votre NIP à nouveau',
    LoggedOut: 'Vous avez été déconnecté du portefeuille.',
    BiometricsChanged:
      'Le déverrouillage avec la biométrie a été désactivé, car les données biométriques de votre appareil ont changé.',
  },
  Terms: {
    TermsOfService: "Conditions d'utilisation",
    IAgree: "J'accepte",
    Attestation: "J'ai lu, je comprends et j'accepte les conditions.",
  },
  Verifier: {
    UseVerifierCapability: 'Utiliser la fonctionnalité de vérification?',
    Toggle: 'Activer la fonctionnalité de vérification',
    ProcessingProof: "Un instant, s'il vous plaît...",
    ZeroKnowledgeProof: 'Preuve à divulgation nulle',
    Parameterizable: 'Paramétrable',
    GenerateNewQR: 'Générer un nouveau code QR',
    BackToList: 'Retour à la liste',
    ShareLink: 'Partager le lien',
    ScanQR: 'Veuillez lire ce code QR',
    ScanQRComment: 'avec votre portefeuille numérique pour recevoir une demande de preuve.',
    InformationReceived: 'Information reçue',
    InformationReceivedDetails: 'a partagé les informations suivantes.',
    ProofVerificationFailed: 'La vérification de la preuve a échoué',
    ViewDetails: 'Voir les détails',
    HideDetails: 'Cacher les détails',
    UseProofRequest: 'Utilisez cette demande de preuve',
    SendThisProofRequest: 'Envoyer cette demande de preuve',
    SendProofRequest: 'Envoyer une demande de preuve',
    EmptyList: 'Votre portefeuille est vide. Vos modèles de demande de preuve seront ajoutés ici.',
    ShowTemplateUsageHistory: "Afficher l'historique d'utilisation",
    RequestSent: 'Demande de présentation envoyée',
    PresentationDeclined: 'Demande de présentation refusée',
    PresentationReceived: 'Demande de présentation reçue',
    PresentationFailed: 'Demande de présentation échue',
    ProofRequestRejected: 'Demande de présentation rejetée',
    PresentationFrom: 'Depuis',
    PresentationState: 'État',
    ConnectionlessPresentation: 'Sans connexion',
    TutorialStep1Title: 'Présenter ce code QR au destinataire',
    TutorialStep1Description: "Vous entrez en contact avec l'autre personne. Elle recevra une demande de preuve.",
    InvalidPredicateValueTitle: 'Valeur invalide pour {{ predicate }}',
    InvalidPredicateValueDetails: 'Doit être un chiffre',
    ConnectionLessLabel: 'Anonyme',
    AcceptDevCredentials: 'Accepter les identifiants de développement?',
    UseDevVerifierTemplates: 'Utiliser les modèles de vérificateur de développement?',
    ToggleDevTemplates: 'Basculer les modèles de vérificateur de développement',
    RefreshQR: 'Actualiser le code QR',
  },
  Developer: {
    Environment: 'Environnement',
    Production: 'Production',
    Development: 'Développement',
    Test: 'Test',
    DeveloperMode: 'Mode développeur',
    Toggle: 'Basculer le mode développeur',
    CQEN: 'CQEN',
    MCN: 'MCN',
  },
  ProofRequestTemplates: {
    ProofRequestForAgeValidationName: "Preuve d'âge (18+)",
    ProofRequestForAgeValidationDescription: "Vérifiez que l'utilisateur a 18 ans ou plus",
    ProofRequestForFullNameName: 'Demande du nom complet',
    ProofRequestForFullNameDescription: "Demander le nom complet de l'utilisateur",
    ProofRequestForFullNameAndAgeName: "Demande du nom complet et preuve d'âge (18+)",
    ProofRequestForFullNameAndAgeDescription: "Demander le nom complet et la preuve que l'utilisateur a 18 ans ou plus",
  },
  AddCredentialSlider: {
    Choose: 'Choisir',
    ScanQRCode: 'Balayer un code QR',
    Title: 'Ajouter une attestation',
  },
  HelpCenter: {
    Help: 'Aide',
    ButtonHelpCenter: "Revenir au centre d'aide",
    ConsultHelpCenter: "Consulter le centre d'aide",
  },
  About: {
    Accessibility: 'Accessibilité',
    TermsOfUse: "Conditions d'utilisation",
    PrivacyPolicy: 'Politique de confidentialité',
  },
}

export default translation
