//
//  PINServiceProtocol.swift
//  bcsc-core
//
//  Extracted protocol definition for testability.
//  The full PINService implementation is in PINService.swift.
//

import Foundation

protocol PINServiceProtocol {
    func setPIN(issuer: String, accountID: String, pin: String, isAutoGenerated: Bool) throws -> String
    func verifyPINAndGetHash(issuer: String, accountID: String, pin: String) -> String?
    func deletePIN(issuer: String, accountID: String) throws
    func getPINHash(issuer: String, accountID: String) -> (hash: String, isAutoGenerated: Bool)?
    func isPINAutoGenerated(issuer: String, accountID: String) -> Bool
}
