//
//  PINSecret.swift
//  bcsc-core
//
//  Created by BC Wallet Mobile on 2024-11-24.
//

import Foundation

struct PINSecret {
  /// Salt used to hash PIN
  let salt: Data
  /// Derived key from hashing algorithm
  /// taking in PIN and salt
  let key: String
  /// Flag indicating if the PIN was auto-generated for device security
  /// (vs user-created for PIN security). Used to prompt users to create
  /// their own PIN in future app versions.
  let isAutoGenerated: Bool

  private let issuer: String
  private let accountID: String

  var id: String {
    return Self.composeID(issuer: issuer, accountID: accountID)
  }

  init(salt: Data, key: String, issuer: String, accountID: String, isAutoGenerated: Bool = false) {
    self.salt = salt
    self.key = key
    self.issuer = issuer
    self.accountID = accountID
    self.isAutoGenerated = isAutoGenerated
  }

  init(salt: Data, key: String, id: String, isAutoGenerated: Bool = false) {
    self.salt = salt
    self.key = key
    self.isAutoGenerated = isAutoGenerated

    let object = Self.decomposeID(id: id)
    self.issuer = object.issuer
    self.accountID = object.accountID
  }

  static func composeID(issuer: String, accountID: String) -> String {
    return "\(issuer).\(accountID)"
  }

  static func decomposeID(id: String) -> (issuer: String, accountID: String) {
    let idArr = id.split(separator: ".").compactMap({ String($0) })

    return (issuer: idArr.first ?? "", accountID: idArr.last ?? "")
  }
}
