package com.bcsccore.authentication

import android.content.Context
import android.util.Log
import com.bcsccore.storage.NativeCompatiblePinStorage
import com.bcsccore.storage.NativeCompatibleStorage

/**
 * PinService wrapper that uses native-compatible PIN storage.
 * This ensures rollback compatibility with ias-android.
 *
 * This class provides the same interface as the original PinService
 * but uses NativeCompatiblePinStorage under the hood for:
 * - EncryptedSharedPreferences (matching native)
 * - Native-compatible PBKDF2 parameters (210k iterations, SHA256)
 * - Native-compatible key naming conventions
 *
 * PIN aliases use the v3 format "$issuer.$accountId" to remain compatible
 * during v3→v4 migration
 */
class PinService(
    private val context: Context,
    private val storage: NativeCompatibleStorage,
) {
    companion object {
        private const val TAG = "PinService"
    }

    private val nativePinStorage: NativeCompatiblePinStorage by lazy {
        NativeCompatiblePinStorage(context)
    }

    /**
     * A helper method to fetch the issuer from storage
     */
    private fun getIssuer(accountId: String): String {
        val issuerName = storage.getDefaultIssuerName()
        val accounts = storage.readAccounts(issuerName)
        val issuer = accounts?.firstOrNull { it.uuid == accountId }?.issuer
        if (issuer == null) {
            Log.e(TAG, "getIssuer: no account found for accountId=$accountId. PIN operations will fail")
        }
        return issuer ?: ""
    }

    // Outputs {issuer}.{account}
    // e.g. "bcsc-issuer.1234-5678-9012"
    private fun buildAlias(accountId: String): String = "${getIssuer(accountId)}.$accountId"

    /**
     * Checks if a PIN is set for the given account ID.
     */
    fun hasPIN(accountId: String): Boolean {
        val alias = buildAlias(accountId)
        val hasPin = nativePinStorage.hasPin(alias)
        Log.d(TAG, "hasPIN($accountId): $hasPin")
        return hasPin
    }

    /**
     * Sets a PIN for the given account ID.
     * Uses native-compatible storage format.
     *
     * @param accountId The account identifier
     * @param pin The PIN to set
     * @param isAutoGenerated Whether the PIN was auto-generated (for device security) or user-created
     */
    fun setPIN(
        accountId: String,
        pin: String,
        isAutoGenerated: Boolean = false,
    ) {
        val alias = buildAlias(accountId)
        Log.d(TAG, "setPIN for account: $accountId (isAutoGenerated: $isAutoGenerated)")

        // Check for old-format PIN and warn (can't migrate due to different crypto params)
        if (nativePinStorage.checkForOldFormatPin(alias)) {
            Log.w(TAG, "Old-format PIN found. Will be replaced with native-compatible format.")
            nativePinStorage.removeOldFormatPin(alias)
        }

        val result = nativePinStorage.setPin(alias, pin, isAutoGenerated)
        if (result == null) {
            throw RuntimeException("Failed to set PIN for account: $accountId")
        }

        Log.d(TAG, "Successfully set PIN for account: $accountId")
    }

    /**
     * Sets a PIN for the given account ID and returns the hash.
     * Uses native-compatible storage format.
     *
     * @param accountId The account identifier
     * @param pin The PIN to set
     * @param isAutoGenerated Whether the PIN was auto-generated (for device security) or user-created
     * @return The PBKDF2 hash of the PIN for use as wallet key
     */
    fun setPINReturningHash(
        accountId: String,
        pin: String,
        isAutoGenerated: Boolean = false,
    ): String {
        val alias = buildAlias(accountId)
        Log.d(TAG, "setPINReturningHash for account: $accountId (isAutoGenerated: $isAutoGenerated)")

        // Check for old-format PIN and warn (can't migrate due to different crypto params)
        if (nativePinStorage.checkForOldFormatPin(alias)) {
            Log.w(TAG, "Old-format PIN found. Will be replaced with native-compatible format.")
            nativePinStorage.removeOldFormatPin(alias)
        }

        val pinSecret = nativePinStorage.setPin(alias, pin, isAutoGenerated)
        if (pinSecret == null) {
            throw RuntimeException("Failed to set PIN for account: $accountId")
        }

        Log.d(TAG, "Successfully set PIN for account: $accountId")
        return pinSecret.key
    }

    /**
     * Sets up a device security PIN (auto-generated) and returns the hash.
     *
     * @param accountId The account identifier
     * @param pin The auto-generated PIN
     * @return The PBKDF2 hash of the PIN for use as wallet key
     */
    fun setupDeviceSecurityPIN(
        accountId: String,
        pin: String,
    ): String = setPINReturningHash(accountId, pin, isAutoGenerated = true)

    /**
     * Validates a PIN for the given account ID.
     */
    fun validatePIN(
        accountId: String,
        pin: String,
    ): Boolean {
        val alias = buildAlias(accountId)
        val isValid = nativePinStorage.verifyPin(alias, pin)
        Log.d(TAG, "validatePIN($accountId): $isValid")
        return isValid
    }

    /**
     * Validates a PIN and returns the hash if successful.
     *
     * @param accountId The account identifier
     * @param pin The PIN to validate
     * @return Pair of (isValid, hash) where hash is only present if valid
     */
    fun validatePINReturningHash(
        accountId: String,
        pin: String,
    ): Pair<Boolean, String?> {
        val alias = buildAlias(accountId)
        val isValid = nativePinStorage.verifyPin(alias, pin)
        Log.d(TAG, "validatePINReturningHash($accountId): $isValid")

        if (isValid) {
            val hashResult = nativePinStorage.getPinHash(alias)
            return Pair(true, hashResult?.first)
        }
        return Pair(false, null)
    }

    /**
     * Removes the PIN for the given account ID.
     */
    fun removePIN(accountId: String): Boolean {
        val alias = buildAlias(accountId)
        Log.d(TAG, "removePIN for account: $accountId")

        // Also remove old-format if exists
        nativePinStorage.removeOldFormatPin(alias)

        return nativePinStorage.removePin(alias)
    }

    /**
     * Gets the PIN hash (PBKDF2 derived key) for use as an Askar wallet key.
     *
     * @param accountId The account identifier
     * @return Pair of (hash, isAutoGenerated) or null if not found
     */
    fun getPINHash(accountId: String): Pair<String, Boolean>? {
        val alias = buildAlias(accountId)
        val result = nativePinStorage.getPinHash(alias)
        Log.d(TAG, "getPINHash($accountId): ${if (result != null) "found" else "not found"}")
        return result
    }

    /**
     * Checks if the stored PIN was auto-generated (for device security) or user-created.
     *
     * @param accountId The account identifier
     * @return true if PIN was auto-generated, false if user-created or not found
     */
    fun isPINAutoGenerated(accountId: String): Boolean {
        val alias = buildAlias(accountId)
        val isAutoGenerated = nativePinStorage.isPinAutoGenerated(alias)
        Log.d(TAG, "isPINAutoGenerated($accountId): $isAutoGenerated")
        return isAutoGenerated
    }
}
