package com.bcsccore.authentication

import android.content.Context
import android.util.Log
import com.bcsccore.storage.NativeCompatiblePinStorage

/**
 * PinService wrapper that uses native-compatible PIN storage.
 * This ensures rollback compatibility with ias-android.
 *
 * This class provides the same interface as the original PinService
 * but uses NativeCompatiblePinStorage under the hood for:
 * - EncryptedSharedPreferences (matching native)
 * - Native-compatible PBKDF2 parameters (210k iterations, SHA256)
 * - Native-compatible key naming conventions
 */
class PinService(
    private val context: Context,
) {
    companion object {
        private const val TAG = "PinService"
    }

    private val nativePinStorage: NativeCompatiblePinStorage by lazy {
        NativeCompatiblePinStorage(context)
    }

    /**
     * Checks if a PIN is set for the given account ID.
     */
    fun hasPIN(accountId: String): Boolean {
        val hasPin = nativePinStorage.hasPin(accountId)
        Log.d(TAG, "hasPIN($accountId): $hasPin")
        return hasPin
    }

    /**
     * Sets a PIN for the given account ID.
     * Uses native-compatible storage format.
     *
     * @param accountId The account identifier
     * @param pin The PIN to set
     * @param isAutoGenerated Whether the PIN was auto-generated (for device security) or user-created
     */
    fun setPIN(
        accountId: String,
        pin: String,
        isAutoGenerated: Boolean = false,
    ) {
        Log.d(TAG, "setPIN for account: $accountId (isAutoGenerated: $isAutoGenerated)")

        // Check for old-format PIN and warn (can't migrate due to different crypto params)
        if (nativePinStorage.checkForOldFormatPin(accountId)) {
            Log.w(TAG, "Old-format PIN found. Will be replaced with native-compatible format.")
            nativePinStorage.removeOldFormatPin(accountId)
        }

        val result = nativePinStorage.setPin(accountId, pin, isAutoGenerated)
        if (result == null) {
            throw RuntimeException("Failed to set PIN for account: $accountId")
        }

        Log.d(TAG, "Successfully set PIN for account: $accountId")
    }

    /**
     * Sets a PIN for the given account ID and returns the hash.
     * Uses native-compatible storage format.
     *
     * @param accountId The account identifier
     * @param pin The PIN to set
     * @param isAutoGenerated Whether the PIN was auto-generated (for device security) or user-created
     * @return The PBKDF2 hash of the PIN for use as wallet key
     */
    fun setPINReturningHash(
        accountId: String,
        pin: String,
        isAutoGenerated: Boolean = false,
    ): String {
        Log.d(TAG, "setPINReturningHash for account: $accountId (isAutoGenerated: $isAutoGenerated)")

        // Check for old-format PIN and warn (can't migrate due to different crypto params)
        if (nativePinStorage.checkForOldFormatPin(accountId)) {
            Log.w(TAG, "Old-format PIN found. Will be replaced with native-compatible format.")
            nativePinStorage.removeOldFormatPin(accountId)
        }

        val pinSecret = nativePinStorage.setPin(accountId, pin, isAutoGenerated)
        if (pinSecret == null) {
            throw RuntimeException("Failed to set PIN for account: $accountId")
        }

        Log.d(TAG, "Successfully set PIN for account: $accountId")
        return pinSecret.key
    }

    /**
     * Sets up a device security PIN (auto-generated) and returns the hash.
     *
     * @param accountId The account identifier
     * @param pin The auto-generated PIN
     * @return The PBKDF2 hash of the PIN for use as wallet key
     */
    fun setupDeviceSecurityPIN(
        accountId: String,
        pin: String,
    ): String = setPINReturningHash(accountId, pin, isAutoGenerated = true)

    /**
     * Validates a PIN for the given account ID.
     */
    fun validatePIN(
        accountId: String,
        pin: String,
    ): Boolean {
        val isValid = nativePinStorage.verifyPin(accountId, pin)
        Log.d(TAG, "validatePIN($accountId): $isValid")
        return isValid
    }

    /**
     * Validates a PIN and returns the hash if successful.
     *
     * @param accountId The account identifier
     * @param pin The PIN to validate
     * @return Pair of (isValid, hash) where hash is only present if valid
     */
    fun validatePINReturningHash(
        accountId: String,
        pin: String,
    ): Pair<Boolean, String?> {
        val isValid = nativePinStorage.verifyPin(accountId, pin)
        Log.d(TAG, "validatePINReturningHash($accountId): $isValid")

        if (isValid) {
            val hashResult = nativePinStorage.getPinHash(accountId)
            return Pair(true, hashResult?.first)
        }
        return Pair(false, null)
    }

    /**
     * Removes the PIN for the given account ID.
     */
    fun removePIN(accountId: String): Boolean {
        Log.d(TAG, "removePIN for account: $accountId")

        // Also remove old-format if exists
        nativePinStorage.removeOldFormatPin(accountId)

        return nativePinStorage.removePin(accountId)
    }

    /**
     * Gets the PIN hash (PBKDF2 derived key) for use as an Askar wallet key.
     *
     * @param accountId The account identifier
     * @return Pair of (hash, isAutoGenerated) or null if not found
     */
    fun getPINHash(accountId: String): Pair<String, Boolean>? {
        val result = nativePinStorage.getPinHash(accountId)
        Log.d(TAG, "getPINHash($accountId): ${if (result != null) "found" else "not found"}")
        return result
    }

    /**
     * Checks if the stored PIN was auto-generated (for device security) or user-created.
     *
     * @param accountId The account identifier
     * @return true if PIN was auto-generated, false if user-created or not found
     */
    fun isPINAutoGenerated(accountId: String): Boolean {
        val isAutoGenerated = nativePinStorage.isPinAutoGenerated(accountId)
        Log.d(TAG, "isPINAutoGenerated($accountId): $isAutoGenerated")
        return isAutoGenerated
    }
}
