// prettier-ignore
const translation = {
  "BCID": {
    "GetID": "Get BCID",
    "GetDigitalID": "Get your Person credential",
  },
  "Error": {
    "Title2020": "Unable to parse invitation",
    "Message2020": "There was a problem parsing the connection invitation.",
    "Title2021": "Unable to receive invitation",
    "Message2021": "There was a problem receiving the invitation to connect.",
    "Title2022": "Unable to find legacy DID",
    "Message2022": "There was a problem extracting the did repository.",
    "Title2025": "BCSC Authentication",
    "Message2025": "There was a problem reported by BCSC.",
    "Title2026": "Oops! Something went wrong",
    "Message2026": "The app has encountered a problem. Try restarting the app.",
    "Title2027": "Unable to parse invitation",
    "Message2027": "There was a problem parsing the attestation connection invitation.",
    "Title2028": "Unable to receive invitation",
    "Message2028": "There was a problem receiving the attestation invitation to connect.",
    "Title2029": "Unable to handle attestation proof",
    "Message2029": "There was a problem while handling an attestation proof request.",
    "Title2030": "Unable to complete app initialization",
    "Message2030": "There was a problem while initializing the app.",
    "Title2031": "Unable to complete agent initialization",
    "Message2031": "There was a problem while initializing the agent.",
    "Title2032": "Unable to open app-to-app URL",
    "Message2032": "There was a problem while opening the app-to-app URL.",
    "NoMessage": "No Message",
  },
  "CameraDisclosure": {
    "AllowCameraUse": "Allow camera use",
    "CameraDisclosure": "The camera is used to scan QR codes that initiate a credential offer or credential request. No information about the images is stored, used for analytics, or shared.",
    "ToContinueUsing": "To continue using the BC Wallet scan feature, please allow camera permissions.",
    "Allow": "Allow",
    "OpenSettings": "Open settings",
  },
  "Biometry": {
    "Toggle": "Toggle Biometrics",
    "EnabledText1": "Log in with your phone's biometrics instead of your wallet PIN.",
    "EnabledText1Bold": "you will need to use biometrics to open your BC Wallet.",
    "EnabledText2": "This means all fingerprint and facial data added on this phone can be used to access your BC Wallet.",
    "EnabledText3": "Anyone who can access your phone with biometrics can access your BC Wallet.",
    "EnabledText3Bold": "Ensure only you have access to your wallet.",
    "Warning": "Ensure only you have access to your wallet.",
    "UseToUnlock": "Use biometrics to unlock wallet?"
  },
  "Credentials": {
    "AddCredential": "Add Credential",
    "EmptyList": "Your wallet is empty.",
    "AddFirstCredential": "Add your first credential"
  },
  "Onboarding": {
    "DifferentWalletHeading": "A different smart wallet",
    "DifferentWalletParagraph": "Unlike other digital wallets, BC Wallet helps you prove who you are in-person or online by storing and using digital credentials issued by participating services.\n\nInteract with confidence with individuals and organizations you trust.",
    "DigitalCredentialsHeading": "Digital credentials",
    "DigitalCredentialsParagraph": "Digital credentials are the electronic equivalent of physical credentials such as certifications and permits offered by participating services.\n\nServices are simplified and expedited as organizations and individuals can confirm who you are with trusted information from digital credentials.",
    "PrivateConfidentialHeading": "Private and confidential",
    "PrivateConfidentialParagraph": "Your privacy is important.\n\nThe B.C. government doesn't know when you use digital credentials, unless you're interacting with them. No analytics are recorded.\n\nYou approve every use of your digital credentials, and only provide the information that's needed.",
    "GetStarted": "Get Started",
  },
  "Preface": {
    "Paragraph1": "Most people will not have a need for BC Wallet because very few digital credentials are currently available.",
    "Link1": "See where you can use BC Wallet",
    "Paragraph2": "If BC Wallet isn't what you're looking for but you're curious, check out our",
    "Link2": "BC Wallet showcase",
  },
  "Screens": {
    "Onboarding": "BC Wallet",
    "Terms": "Terms of Use",
    "Settings": "Menu",
    "Preface": "BC Wallet",
    "VerificationSteps": "Setup steps",
    "EvidenceCollectionStep": {
      "Stage1": "Choose your identification",
      "Stage2": "Instructions",
      "Stage3": "Scan your identification",
      "Stage4": "Enter serial number",
      "Stage5": "Enter birthdate",
    },
    "ResidentialAddressStep": {
      "Stage1": "TODO",
    },
    "EmailStep": {
      "Stage1": "TODO",
    },
    "VerifyIdentityStep": {
      "Stage1": "TODO",
    },
  },
  "PINCreate": {
    "Explainer": {
      "PrimaryHeading": "Create a PIN that is:",
      "Bullet1": "<b>Memorable.</b> If you forget your PIN, you can't recover it. You will need to reinstall and set up your wallet again.",
      "Bullet2": "<b>Unique.</b> Your PIN prevents people from accessing your digital credentials. Do not share it with anyone.",
    }
  },
  "PersonCredentialNotification": {
    "Title": "Get your Person credential",
    "Description": "Add your Person credential to your wallet and use it to get access to services online.",
    "ButtonTitle": "Start",
  },
  "PersonCredential": {
    "ServicesCardInstalled": "Step 1: BC Services Card app installed",
    "InstallServicesCard": "Step 1: Install the BC Services Card app",
    "InstallApp": "Install the app",
    "AppOnOtherDevice": "I have it on another device",
    "CreatePersonCred": "Step 2: Create your Person credential",
    "StartProcess": "Start the process",
    "PageTitle": "Person Credential",
    "PleaseWait": "Please wait as we get things ready for you",
    "WhatIsPersonCredentialLink": "What is a Person credential",
    "WhereToUseLink": "Where to use",
    "HelpLink": "Help",
    "EstablishingConnection": "Establishing connection...",
    "ConnectedToAgent": "Connected to agent...",
    "WaitingForAppAttestation": "Waiting for app attestation...",
    "AppAttested": "App attested...",
    "OfferingCredential": "Offering credential...",
    "InitiatingAppToAppFlow": "Initiating app-to-app flow...",
  },
  "NetInfo": {
    "NoInternetConnectionTitle": "No internet connection",
    "NoInternetConnectionMessage": "You're unable to access services using BC Wallet or receive credentials until you're back online.\n\nPlease check your internet connection."
  },
  "Tour": {
    "GuideTitle": "Welcome to BC Wallet",
    "WouldYouLike": "Would you like some guidance on how to use BC Wallet?",
    "UseAppGuides": "Use app guides",
    "DoNotUseAppGuides": "Don't use app guides",
    "AddAndShare": "Add and share credentials",
    "AddAndShareDescription": "To add and use credentials you scan a QR code displayed by the service provider.",
    "AddCredentials": "Add credentials",
    "AddCredentialsDescription": "Add credentials by scanning a QR code displayed on the issuer service.",
    "Notifications": "Notifications",
    "NotificationsDescription": "After you scan a QR code, the credential offer or proof request will appear here, as well as other notable events.",
    "YourCredentials": "Your credentials",
    "YourCredentialsDescription": "Your added digital credentials appear here. You can review credential details and add and delete credentials.",
    "CredentialOffers": "Credential offers",
    "CredentialOffersDescription": "An organization has offered you a credential. Review the credentials details and choose to accept or decline it. Accepted credentials will be added to your wallet.",
    "ProofRequests": "Proof requests",
    "ProofRequestsDescription": "An organization is asking you to prove your credentials. Review what they're asking for and choose to accept or decline it.",
    "Skip": "Skip",
    "Next": "Next",
    "Back": "Back",
    "Done": "Done",
  },
  "Settings": {
    "Help": "Help",
    "MoreInformation": "More Information",
    "PlayWithBCWallet": "Play with BC Wallet",
    "HelpUsingBCWallet": "Help using BC Wallet",
    "GiveFeedback": "Give feedback",
    "ReportAProblem": "Report a problem",
    "TermsOfUse": "Terms of use",
    "PrivacyStatement": "Privacy statement",
    "VulnerabilityDisclosurePolicy": "Vulnerability disclosure policy",
    "Accessibility": "Accessibility",
    "IntroductionToTheApp": "Introduction to the app"
  },
  "Developer": {
    "Environment": "Environment",
    "Production": "Production",
    "Development": "Development",
    "Test": "Test",
    "DeveloperMode": "Developer mode",
    "Toggle": "Toggle Developer Mode",
    "AttestationSupport": "Attestation support",
    "EnableProxy": "Enable proxy",
    "EnableAltPersonFlow": "Alt Person flow",
    "EnableAppToAppPersonFlow": "App-to-app Person flow",
    "SwitchMode": "Switch mode",
    "SwitchTheme": "Switch theme",
  },
  "Tips": {
    "Header": "Tips",
    "GettingReady": "Getting your wallet ready...",
    "Tip1": "For extra security, BC Wallet locks the app after 5 minutes of inactivity",
    "Tip2": "Unlike showing physical cards, you share only what is necessary from your credentials",
    "Tip3": "Your credentials are stored only on this phone, nowhere else",
    "Tip4": "Information is sent and received over an untraceable encrypted connection",
    "Tip5": "Remember your PIN. If you forget it, you'll need to reinstall and re-add your credentials",
    "Tip6": "Skip the PIN and unlock your wallet using your biometrics for a faster experience",
    "Tip7": "Your most recently added credentials are placed at the top",
    "Tip8": "Remove credentials in your wallet from the credential details screen",
    "Tip9": "You can dismiss notifications without opening them by tapping “X” in the top right corner",
    "Tip10": "Need help? Find answers in the help section within the “☰” button on the top left corner",
    "Tip11": "You can turn on the camera flash if the QR code is hard to see",
    "Tip12": "If the QR code isn't scanning, try increasing the screen's brightness",
    "Tip13": "Information sent via your wallet is trusted by you and your Contacts you interact with",
    "Tip14": "Even revoked or expired credentials can be usable if the organization doesn't request for it",
  },
  "Init": {
    "Retry": "Retry",
    "Starting": "Starting...",
    "FetchingPreferences": "Fetching preferences...",
    "VerifyingOnboarding": "Verifying onboarding...",
    "CheckingOCA": "Checking for OCA updates...",
    "InitializingAgent": "Initializing agent...",
    "Finishing": "Finishing..."
  },
  "Feedback": {
    "GiveFeedback": "Give Feedback",
  },
  "PushNotifications": {
    "NotificationsOffTitle": "Notifications for BC Wallet are turned off",
  },
  "AddCredentialSlider": {
    "Choose": "Choose",
    "ScanQRCode": "Scan a QR code",
  },
  "Scan": {
    "ScanOnySpecial": "Only special QR codes can be scanned by BC Wallet.",
    "ScanOnlySpecial3": "BC Wallet currently doesn't support adding digital credential by scanning or taking photos of physical ones.",
    "WhereToUseLink": "See where you can use BC Wallet",
    "BadQRCodeDescription": "Ths QR code scanned doesn't work with BC Wallet. BC Wallet only works with participating services.\n\nIt currently can't add digital credentials by taking photos of physical ones."
  },
  "Unified": {
    "Steps": {
      "ScanOrTakePhotos": "Scan or take photos of your ID."
    },
    "ChooseYourID": {
      "WhatCardDoYou": "What BC Services Card do you have?",
      "SomePeopleStillCallIt": "Some people still call it a CareCard or a Health Card. It has your personal health number (PHN) on the back.",
      "CombinedCard": "Combined card",
      "CombinedCardActionText": "It's combined with my driver's licence",
      "CombinedCardDescription": "Use this card for a faster way to set up the app.",
      "PhotoCard": "Photo card",
      "PhotoCardActionText": "A card with my photo",
      "PhotoCardDescription": "Use this card for a faster way to set up the app.",
      "NoPhotoCard": "Non photo card",
      "NoPhotoCardActionText": "A card without a photo",
      "NoPhotoCardDescription": "Use this card + photo ID to set up the app.",
      "DontHaveOne": "Don't have one?",
      "CheckBefore": "Check before you continue. It's faster to set up with one of the above.",
      "CheckForServicesCard": "Check for BC Services Card",
      "CheckIfIHave": "Check if I have a BC Services Card",
      "OtherID": "Other ID",
      "OtherIDActionText": "Set up with other ID",
      "OtherIDDescription": "This option takes the longest to set up. You'll need 2 IDs to set up the app and have limited access to services.",
    },
    "Instructions": {
      "Heading": "Provide the card serial number on the back right side of your card.",
      "Paragraph": "When scanning, you should place the card in front of a white background for best results.",
      "ScanBarcode": "Scan Barcode with Camera",
      "EnterManually": "Enter Serial Number Manually",
    },
    "Scan": {},
    "ManualSerial": {
      "InputLabel": "Serial number",
      "InputSubText": "Enter the letter and numbers by the barcode on the back of your card.",
      "EmptySerialError": "Required",
      "CharCountError": "Cannot exceed 15 characters",
    },
    "Birthdate": {
      "CardSerialNumber": "Card serial number: {{ serial }}",
      "Heading": "Enter your birthdate",
      "Paragraph": "Your birthdate is only used to to set up this app. It is not shared.",
      "InputLabel": "Birthdate",
    },
  },
  "RemoteLogging": {
    "ScreenTitle": "Remote troubleshooting",
    "Heading": "Collection notice",
    "CollectionNoticePart1": "Turning on remote troubleshooting will",
    "CollectionNoticeBold": " record Wallet and Credential usage and any associated personal information",
    "CollectionNoticePart2": " while it is turned on.\n\nRemote troubleshooting turns off after 1 hour. The information collected is deleted after 3 days.\n\nThis information is collected by Ministry of Citizens' Services - Cybersecurity and Digital Trust Branch under sections 26(c) and 26(e) of the Freedom of Information and Protection of Privacy Act, and will only be used for the purpose of customer support and troubleshooting.\n\nFor more information, including who to contact, read the",
    "CollectionNoticeLink": "Privacy Policy.",
    "CollectionNoticeWarning": "Only turn on remote troubleshooting if you contacted the support line first and a service agent from the Government of British Columbia asked you to turn it on. They will never contact first. You are never required to turn it on.",
    "CheckBoxTitle": "I understand and want to turn on remote troubleshooting.",
    "IAgree": "I Agree",
    "ButtonTitle": "Turn on",
    "SessionID": "Session ID",
    "Banner": "Remote Troubleshoot on. ID: {{ sessionId }}"
  },
  "AppUpdate": {
    "Heading": "Update BC Wallet to the latest version",
    "Body": "BC Wallet was updated with new improvements. Update your app now to enjoy the latest features and enhancements."
  },
}

export default translation
