// prettier-ignore
const translation = {
  "Global": {
    "OK": "OK",
    "Cancel": "Cancel",
    "Continue": "Continue",
    "Back": "Back",
    "GoBack": "Go Back",
    "Loading": "Loading...",
    "Close": "Close",
  },
  "BCID": {
    "GetDigitalID": "Get your Person credential",
    "DismissMenu": "Dismiss menu",
  },
  "Error": {
    "Title2020": "Unable to parse invitation",
    "Message2020": "There was a problem parsing the connection invitation.",
    "Title2021": "Unable to receive invitation",
    "Message2021": "There was a problem receiving the invitation to connect.",
    "Title2022": "Unable to find legacy DID",
    "Message2022": "There was a problem extracting the did repository.",
    "Title2026": "Oops! Something went wrong",
    "Message2026": "The app has encountered a problem. Try restarting the app.",
    "Title2031": "Unable to complete agent initialization",
    "Message2031": "There was a problem while initializing the agent.",
    "Title2032": "Unable to open app-to-app URL",
    "Message2032": "There was a problem while opening the app-to-app URL.",
    "Title2033": "Failed to load services",
    "Message2033": "There was a problem while loading the services. Please try again later.",
    "OK": "OK",
    "NoMessage": "No Message",
  },
  "Screens": {
    "Preface": "BC Wallet",
  },
  "AppUpdate": {
    "Heading": "Update BC Wallet to the latest version",
    "Body": "BC Wallet was updated with new improvements. Update your app now to enjoy the latest features and enhancements.",
  },
  "Credentials": {
    "AddCredential": "Add Credential",
    "AddFirstCredential": "Add your first credential"
  },
  "Onboarding": {
    "DifferentWalletHeading": "A different smart wallet",
    "DifferentWalletParagraph": "Unlike other digital wallets, BC Wallet helps you prove who you are in-person or online by storing and using digital credentials issued by participating services.\n\nInteract with confidence with individuals and organizations you trust.",
    "DigitalCredentialsHeading": "Digital credentials",
    "DigitalCredentialsParagraph": "Digital credentials are the electronic equivalent of physical credentials such as certifications and permits offered by participating services.\n\nServices are simplified and expedited as organizations and individuals can confirm who you are with trusted information from digital credentials.",
    "PrivateConfidentialHeading": "Private and confidential",
    "PrivateConfidentialParagraph": "Your privacy is important.\n\nThe B.C. government doesn't know when you use digital credentials, unless you're interacting with them. No analytics are recorded.\n\nYou approve every use of your digital credentials, and only provide the information that's needed.",
    "GetStarted": "Get Started",
  },
  "Preface": {
    "Paragraph1": "Most people will not have a need for BC Wallet because very few digital credentials are currently available.",
    "Link1": "See where you can use BC Wallet",
    "Paragraph2": "If BC Wallet isn't what you're looking for but you're curious, check out our",
    "Link2": "BC Wallet showcase",
  },
  "PINCreate": {
    "Header": "BC Wallet",
    "Subheader": "Secure your wallet",
    "Explainer": {
      "PrimaryHeading": "Create a PIN that is:",
      "Bullet1": "<b>Memorable.</b> If you forget your PIN, you can't recover it. You will need to reinstall and set up your wallet again.",
      "Bullet2": "<b>Unique.</b> Your PIN prevents people from accessing your digital credentials. Do not share it with anyone.",
    }
  },
  "PersonCredentialNotification": {
    "Title": "Get your Person credential",
    "Description": "Add your Person credential to your wallet and use it to get access to services online.",
    "ButtonTitle": "Start",
  },
  "PersonCredential": {
    "ServicesCardInstalled": "Step 1: BC Services Card app installed",
    "InstallServicesCard": "Step 1: Install the BC Services Card app",
    "InstallApp": "Install the app",
    "AppOnOtherDevice": "I have it on another device",
    "CreatePersonCred": "Step 2: Create your Person credential",
    "StartProcess": "Start the process",
    "PageTitle": "Person Credential",
    "WhatIsPersonCredentialLink": "What is a Person credential",
    "WhereToUseLink": "Where to use",
    "HelpLink": "Help",
    "EstablishingConnection": "Establishing connection...",
    "ConnectedToAgent": "Connected to agent...",
    "WaitingForAppAttestation": "Waiting for app attestation...",
    "AppAttested": "App attested...",
    "OfferingCredential": "Offering credential...",
    "InitiatingAppToAppFlow": "Initiating app-to-app flow...",
  },
  "Tour": {
    "AddAndShare": "Add and share credentials",
    "AddAndShareDescription": "To add and use credentials you scan a QR code displayed by the service provider.",
    "AddCredentials": "Add credentials",
    "AddCredentialsDescription": "Add credentials by scanning a QR code displayed on the issuer service.",
    "Notifications": "Notifications",
    "NotificationsDescription": "After you scan a QR code, the credential offer or proof request will appear here, as well as other notable events.",
    "YourCredentials": "Your credentials",
    "YourCredentialsDescription": "Your added digital credentials appear here. You can review credential details and add and delete credentials.",
    "CredentialOffers": "Credential offers",
    "CredentialOffersDescription": "An organization has offered you a credential. Review the credentials details and choose to accept or decline it. Accepted credentials will be added to your wallet.",
    "ProofRequests": "Proof requests",
    "ProofRequestsDescription": "An organization is asking you to prove your credentials. Review what they're asking for and choose to accept or decline it.",
    "Skip": "Skip",
    "Next": "Next",
    "Back": "Back",
    "Done": "Done",
  },
  "Settings": {
    "Help": "Help",
    "MoreInformation": "More Information",
    "PlayWithBCWallet": "Play with BC Wallet",
    "HelpUsingBCWallet": "Help using BC Wallet",
    "GiveFeedback": "Give feedback",
    "ReportAProblem": "Report a problem",
    "TermsOfUse": "Terms of use",
    "IntroductionToTheApp": "Introduction to the app",
  },
  "Developer": {
    "Environment": "Environment",
    "DeveloperMode": "Developer mode",
    "Toggle": "Toggle Developer Mode",
    "EnableProxy": "Enable proxy",
    "EnableAppToAppPersonFlow": "App-to-app Person flow",
    "SwitchMode": "Switch mode",
    "SwitchTheme": "Switch theme",
    "Testing": "Testing",
    "ErrorAlertTest": "Error & Alert Testing",
    "ErrorModals": "Error Modals",
    "ErrorModalsDescription": "Trigger errors that display as modal dialogs with title, description, and technical details.",
    "ErrorAsNativeAlert": "Errors as Native Alerts",
    "ErrorAsNativeAlertDescription": "Trigger errors that display as native OS alert dialogs.",
    "PlainAlerts": "Plain Alerts",
    "PlainAlertsDescription": "Trigger non-error alert messages.",
    "DismissErrorModal": "Dismiss Error Modal",
    "DismissErrorModalDescription": "Programmatically dismiss the current error modal if one is displayed.",
    "DismissCurrentError": "Dismiss Current Error",
  },
  "Tips": {
    "Header": "Tips",
    "GettingReady": "Getting your wallet ready...",
  },
  "Init": {
    "Retry": "Retry",
    "Starting": "Starting...",
    "CheckingOCA": "Checking for OCA updates...",
    "InitializingAgent": "Initializing agent...",
    "Finishing": "Finishing..."
  },
  "Feedback": {
    "GiveFeedback": "Give Feedback",
  },
  "AddCredentialSlider": {
    "Choose": "Choose",
    "ScanQRCode": "Scan a QR code",
  },
  "BCSC": {
    "Components": {
      "CloseDropdown": "Close dropdown menu",
    },
    "Title": "BC Services Card",
    "FullTitle": "BC Services Card App",
    "LocaleStringFormat": "en-CA",
    "Screens": {
      "Settings": "Settings",
      "SetupTypes": "BC Services Card",
      "SetupSteps": "Setup Steps",
      "VerificationMethodSelection": "Choose How to Verify",
      "InformationRequired": "Information Required",
      "TransferAccountInstructions": "Transfer Instructions",
      "TransferAccountScan": "Scan QR Code",
      "ContactUs": "Contact Us",
      "HelpCentre": "Help Centre",
      "PrivacyInformation": "Privacy Information",
      "ManageDevices": "Manage Devices",
    },
    "Loading": {
      "DefaultMessage": "A secure way to prove who you are online",
    },
    "Security": {
      "AuthenticatePrompt": "Authenticate to secure your app",
      "AuthenticateToSecure": "Authenticate to secure your app"
    },
    "PIN": {
      "CreatePIN": "Create a 6-digit PIN",
      "ConfirmPIN": "Confirm PIN",
      "RememberPIN": "Remember your PIN",
      "RememberPINDescription": "We cannot help you get or reset your PIN if you forget it. It's only saved on this device. It's never shared with us.",
      "IUnderstand": "I understand if I forget my PIN that I have to set up this app again.",
      "MustCheckBox": "You must check this box to continue.",
      "PINTooShort": "PIN must be 6 digits",
      "PINsDoNotMatch": "PINs do not match",
      "SettingUpPIN": "Setting up your PIN...",
      "SettingUpAccount": "Setting up your account...",
      "FailedToSetPIN": "Failed to set PIN",
      "ErrorSettingPIN": "An error occurred while setting the PIN"
    },
    "ChangePIN": {
      "ScreenTitle": "Change your PIN",
      "EnterCurrentPIN": "Enter your current PIN",
      "EnterNewPIN": "Enter a new 6-digit PIN",
      "ReenterNewPIN": "Re-enter new PIN",
      "RememberPIN": "Remember your PIN",
      "RememberPINDescription": "We cannot help you get or reset your PIN if you forget it. It's only saved on this device.",
      "IUnderstand": "I understand if I forget my PIN that I have to set up this app again.",
      "MustCheckBox": "You must check this box to continue.",
      "ButtonTitle": "Change PIN",
      "ChangingPIN": "Changing your PIN...",
      "PINTooShort": "Your PIN must be 6 digits",
      "PINsDoNotMatch": "PIN does not match",
      "IncorrectPIN": "Incorrect PIN",
      "AccountLocked": "Your account is locked. Please try again later.",
      "FailedToSetPIN": "Failed to change PIN",
      "ErrorChangingPIN": "An error occurred while changing the PIN"
    },
    "Settings": {
      "HeaderA": "App Settings",
      "HeaderB": "Information",
      "Help": "Help",
      "SignOut": "Sign out",
      "Biometrics": "Biometrics",
      "EditNickname": "Edit Nickname",
      "AutoLockTime": "Auto lock time",
      "Notifications": "Notifications",
      "ForgetPairings": "Forget pairings",
      "Privacy": "Privacy",
      "ContactUs": "Contact us",
      "Feedback": "Feedback",
      "Accessibility": "Accessibility",
      "AnalyticsOptIn": "Analytics Opt-In Placeholder",
      "TermsOfUse": "Terms of use",
      "Analytics": "Analytics",
      "RemoveAccount": "Remove account",
      "AppSecurity": {
        "ScreenTitle": "App Security",
        "ChangeAppSecurity": "Change App Security",
        "Title": "App Security",
        "Description": "Choose how you want to secure this app and access your credentials. You can switch between using your device's biometric authentication or a PIN.",
        "CurrentMethod": "Current security method",
        "ChooseMethod": "Switch to",
        "DeviceAuth": "Device Authentication",
        "PIN": "PIN",
        "UseDeviceAuth": "Use {{method}}",
        "DeviceAuthSubtext": "Use your {{platform}}'s built-in security to unlock the app.",
        "UsePIN": "Use a PIN",
        "PINSubtext": "Create a personal PIN to unlock the app.",
        "CurrentlySelected": "Currently active",
        "DeviceAuthNotSetup": "Device authentication is not available. Set up Face ID, Touch ID, or a device passcode in your device settings to use this option.",
        "DeviceAuthUnavailableTitle": "Device Authentication Unavailable",
        "DeviceAuthUnavailableMessage": "Please set up Face ID, Touch ID, or a device passcode in your device settings first.",
        "AuthenticateToSwitch": "Authenticate to change your security method",
        "SuccessTitle": "Success",
        "SwitchedToDeviceAuth": "Your app is now secured with {{method}}.",
        "SwitchedToPIN": "Your app is now secured with a PIN.",
        "ErrorTitle": "Error",
        "SetupFailedMessage": "Failed to change security method. Please try again.",
        "SwitchToPINTitle": "Switch to PIN",
        "SwitchToPINMessage": "You will need to create a new PIN to secure the app."
      },
      "ChangePIN": {
        "ButtonTitle": "Change PIN",
        "ScreenTitle": "Create PIN",
        "SettingUpPIN": "Setting up your PIN...",
        "SuccessTitle": "Success",
        "PINChanged": "Your PIN has been changed successfully."
      },
    },
    "Services": {
      "CatalogueTitle": "Services",
      "CatalogueSearch": "Search services",
      "WantToLogin": "Do you want to log in to",
      "RequestedInformation": "They will receive the following information:",
      "FromAccountPrefix": "From your",
      "FromAccount": "Account",
      "PrivacyNotice": "Privacy notice",
      "ReportSuspiciousPrefix": "Not you?",
      "ReportSuspicious": "Report Suspicious Activity",
      "NoLoginInstructions": "You will need to go to their website first if you want to log in to it. You can't log in to services directly from this app.",
      "NoLoginProof": "You will use this app to prove who you are when you log in.",
      "Goto": "Go to",
      "NotListed": "Services not listed?",
      "NotListedDescription": "Services that are only available to specific people or people in specific professions are not listed above.",
      "NotListedDescriptionContact": "Contact the service to the link to their website.",
      "PrivacyPolicy": "Privacy Policy",
      "LoginErrorTitle": "Unable to quick login to service",
      "SavedServices": "Saved Services",
      "NoSavedServices": "No saved services",
      "Remove": "Remove",
      "Open": "Open",
    },
    "Modals": {
      "InternetDisconnected": {
        "Header": "No internet connection",
        "ContentA": "It looks like you aren’t connected to the internet. A connection is required for this app to function.",
        "ContentB": "Check that your device is connected to the internet or try again.",
        "RetryButton": "Retry",
      },
      "MandatoryUpdate": {
        "Header": "App update required",
        "ContentA": "You must update this app to continue.",
        "ContentB": "Please update to the latest version from the {{platformStore}}.",
        "UpdateButton": "Go to {{platformStore}}",
      },
      "DeviceInvalidated": {
        "Header": "Device invalidated",
        "CancelledByCardCancel": "Your account will be removed from this app.",
        "CancelledByAgent": "Your account was removed from the app on this device at a Service BC location or by the service.",
        "CancelledByUser": "You made a change on id.gov.bc.ca to remove your account from the app on this device.",
        "CanceledByAdditionalCard": "You can't use this app if you have more than one BC Services Card.",
        "ContentA": "Tap OK to clear local data and restart setup on this device.",
        "OKButton": "OK",
      }
    },
    "Home": {
      "WhereToUseTitle": "Where to use",
      "WhereToUseDescription": "Find the websites you can log in to with this app.",
      "LogInFromComputerTitle": "Log in from a computer",
      "LogInFromComputerDescription": "Enter pairing code to log in from a different device – like a computer, laptop, or tablet.",
      "ViewMessages": "View new messages",
    },
    "Steps": {
      "ScanOrTakePhotos": "Scan or take photos of your ID.",
      "Step1": "Step 1",
      "Step2": "Step 2",
      "Step3": "Step 3",
      "Step4": "Step 4",
      "Step5": "Step 5",
      "VerificationIDMissing": "Verification request ID is missing",
      "DeviceCodeOrUserCodeMissing": "Device code or user code is missing for verification",
      "GetVerificationStep2Subtext1": "ID: BC Services Card ({{ serial }})",
      "GetVerificationStep2Subtext2": "ID: {{ evidenceType }} ({{ documentNumber }})",
      "GetVerificationStep3Subtext1": "Address: Residential address from your BC Services Card will be used",
      "GetVerificationStep3Subtext2": "Address: {{ address }}",
      "GetVerificationStep3Subtext3": "Residential address",
      "GetVerificationStep5Subtext1": "Verify identity by {{ expirationDate }}",
      "GetVerificationStep5Subtext2": "Complete additional identification first",
      "GetVerificationStep5Subtext3": "Verify identity",
      "TransferAccountSubtext": "Transfer your account from another device",
      "AddSecondIdText": "Add second ID",
      "AdditionalIdentificationRequired": "Additional identification required for non-photo BC Services Card.",
      "StoredEmail": "Email: {{ email }}",
      "EmailAddress": "Email Address",
      "EditEmail": "Edit",
      "CheckStatus": "Check status",
      "ChooseAnotherWayToVerify": "Choose another way to verify",
      "ResetData": "Reset data",
    },
    "SystemChecks": {
      "Devices": {
        "DeviceLimitReachedBannerTitle": "Device limit reached",
        "ManageDevicesButton": "Manage devices",
        "CloseButton": "Close",
        "ReviewDevicesTitle": "Review your devices",
        "ReviewDevicesContentA1": "You can have this account on a maximum of",
        "ReviewDevicesContentA2": "devices.",
        "ReviewDevicesContentB": "You can continue using these devices, but you won't be able to set up any more devices.",
        "ReviewDevicesContentC": "Remove any devices from your account that are no longer in use.",
        "ReviewDevicesContentD": "If you deleted the app from a device, without resetting it first, then it will still count as an active device."
      },
      "ServerStatus": {
        "UnavailableBannerTitle": "Service Unavailable",
      },
      "UpdateApp": {
        "UpdateAvailableBannerTitle": "App update available",
      },
      "AccountExpiryWarningDescription": {
        "ExpiringBannerTitle": "Expires in {{days}} days",
        "ExpiringBannerDescription": "Renew your account on this device before it expires on {{accountExpiration}}."
      },
      "AccountExpiryWarningAlert": {
        "Title": "BC Services Card About to Expire",
        "Message": "Your mobile card is about to expire, go here to request an extension",
        "RenewalInfoButton": "Renewal Information"
      },
      "AccountExpiryAlert": {
        "Title": "BC Services Card has expired",
        "Message": "Your mobile card has expired, you'll need to remove your card and reverify to continue using the app.",
        "RenewalInfoButton": "Renewal information",
        "DismissButton": "Dismiss"
      }
    },
    "AccountExpired": {
      "StaticBannerTitle": "Expired",
      "StaticBannerDescription": "Your account on this device expired on {{accountExpiration}}. You need to renew it before you can use it to log in.",
      "RenewButton": "Renew account",
      "RemoveButton": "Remove account",
    },
    "AccountRenewal": {
      "InformationHeader": "What you need to renew",
      "InformationBCServicesCardSubHeader": "1. BC Services Card",
      "InformationBCServicesCardContent": "It must be valid. Check the expiry date printed on the front of your card.",
      "InformationGetNewCardA": "Get a new card",
      "InformationGetNewCardB": "if it is expired.",
      "InformationPhotoIdSubHeader": "2. Photo ID",
      "InformationPhotoIdContent": "Only if your BC Services Card does not have a photo on it. You will be asked to provide one or two government-issued IDs.",
      "InformationTypesOfAcceptedId": "Types of accepted ID",
      "RenewalTimeHeader": "Time to renew",
      "RenewalTimeContentA": "You’ll need to verify your identity again and provide your ID.",
      "RenewalTimeContentB": "It may take about 1-2 business days.",
      "RenewalTimeContentC": "The time to complete depends on how you choose to verify your identity - in person, with a video call, or by sending in a video.",
      "WarningHeader": "Warning",
      "WarningContentA": "You will not be able to use this app to log in until you complete renewal.",
      "WarningContentB": "This includes logging into services like Health Gateway or Canada Revenue Agency (CRA).",
      "WarningRenewButton": "Renew"
    },
    "ForgetAllPairings": {
      "Title": "Forget all pairings?",
      "Description1": "When you use this app to log in on another computer, you are asked if you want to remember this device to skip the pairing step.",
      "Description2": "By forgetting all pairings this device will be removed as an option on any computer you previously paired with. You can use this app again to log in on another computer by pairing it again.",
      "ButtonTitle": "Forget all pairings",
      "SuccessTitle": "Success",
      "SuccessMessage": "Successfully unpaired your device",
      "ErrorTitle": "Error",
      "ErrorMessage": "Failed to unpair device",
    },
    "ContactUs": {
      "Title": "Service BC Help Desk",
      "HoursOfServiceTitle": "Hours of service",
      "HoursOfServiceDescription1": "Monday to Friday (except statutory holidays)",
      "HoursOfServiceDescription2": "7:30 am - 5 pm Pacific time",
      "TollFreeLabel": "Canada and USA toll free",
      "TollFreeNumber": "1-888-356-2741",
      "LowerMainlandLabel": "Within lower mainland or outside Canada and USA",
      "LowerMainlandNumber": "604-660-2355",
      "OtherContactsTitle": "Other contacts",
      "VisitThe": "Visit the",
      "GovernmentWebsiteText": "B.C. government website",
      "ToFindWhoToContact": "to find who to contact for:",
      "BulletPoint1": "General information about the card",
      "BulletPoint2": "Privacy-related questions",
      "BulletPoint3": "Reporting a lost or stolen card",
      "BulletPoint4": "Changing personal information",
    },
    "NicknameAccount": {
      "AccountName": "Account Nickname",
      "CreateAccountName": "Create a nickname for your account on this device. It identifies your account:",
      "EditAccountName": "Edit the nickname for your account on this device. It identifies your account:",
      "AccountNameDescription1": "When you open the app",
      "AccountNameDescription2": "In notifications",
      "CharCountTitle": "Character count exceeded",
      "EmptyNameTitle": "Enter an account nickname",
      "NameAlreadyExists": "This nickname already exists",
      "SaveAndContinue": "Save and continue",
      "RenameSuccessToastMessage": "Account nickname updated successfully",
    },
    "ManualPairing": {
      "EnterPairingCodeTitle": "Enter pairing code",
      "EnterPairingCodeMessage": "A pairing code will be provided when you log in to a website on another device.",
      "InvalidPairingCodeMessage": "Pairing code must be six characters long",
      "EmptyPairingCodeMessage": "Pairing code cannot be empty",
      "FailedToSubmitPairingCodeMessage": "Failed to submit pairing code",
      "CompletionTitle": "You're done in this app",
      "CompletionDescription": "Go back to the device you started on to continue logging in to {{serviceName}}.",
      "BookmarkService": "Save link to:",
      "ToggleBookmark": "Toggle bookmark",
    },
    "Onboarding": {
      "LearnMore": "Learn more",
      "CarouselNext": "Next",
      "CarouselBack": "Back",
      "AcceptAndContinueButton": "Accept and continue",
      "CarouselServicesHeader": "Access services online",
      "CarouselProveHeader": "Prove who you are online",
      "CarouselCannotUseHeader": "Cannot use as a health card or driver's license",
      "CarouselServicesContent": "It's accepted by many government services.",
      "CarouselProveBodyContentA": "Log in using just this app. No username or password needed.",
      "CarouselProveBodyContentB": "Access services from any device by approving login in this app.",
      "CarouselCannotUseBodyContentA": "It's not a place to store a digital copy of your BC Services Card.",
      "CarouselCannotUseBodyContentB": "It's your account to access services online only.",
      "PrivacyPolicyTitle": "Privacy",
      "PrivacyPolicyHeaderSetup": "App Setup",
      "PrivacyPolicyHeaderSecuringApp": "Securing the App",
      "PrivacyPolicyContentA": "Your personal information is collected for the purpose of setting up the app on your mobile device and using it to authenticate your identity for accessing government services online under sections 26(c), 26(e) and 26(h) of the Freedom of Information and Protection of Privacy Act.",
      "PrivacyPolicyContentB": "To set up this app you need to verify your identity by providing your information and ID. It’s temporarily stored on this device until the app is set up.",
      "PrivacyPolicyContentC": "This app can be secured with a PIN or using your device’s security. Keep your account safe. Keep your device passcode or app PIN confidential",
      "TermsOfUseTitle": "Terms of Use",
      "NotificationsHeader": "Notifications",
      "NotificationsContentA": "It's recommended you allow this app to receive push notifications.",
      "NotificationsContentB": "Notifications will be sent to you when:",
      "NotificationsBullet1": "The app is setup and ready to use",
      "NotificationsBullet2": "You choose to log in",
      "NotificationsBullet3": "You need to renew and verify your identity again",
      "NotificationsBullet4": "There are changes to your account",
      "SecureAppHeader": "Choose how to secure this app",
      "SecureAppContent": "Protect your identity. For example, if your device is lost or stolen. Keep your access confidential",
      "SecureAppDeviceAuthTitle": "Use {{deviceAuthMethodName}}",
      "SecureAppDeviceAuthSubtext": "It’s already set up on this {{platform}}. It never leaves this device or is shared with us.",
      "SecureAppPINTitle": "Create a PIN",
      "SecureAppPINSubtext": "The PIN you create is confidential. It never leaves this device or is shared with us.",
      "SecureAppNoDeviceAuthContent1": "You need to choose a PIN. It keeps your information private.",
      "SecureAppNoDeviceAuthContent2": "It prevents others from using this app to access services as you. For example, if your phone is lost or stolen.",
      "AnalyticsTitle": "Enable Analytics?",
      "AnalyticsHeader": "Help us improve your BC Services Card experience",
      "AnalyticsContent": "With your permission, we'll collect analytics about [TBD] to help our team find bugs and add new features. Opt-out anytime in settings.",
      "AcceptAnalytics": "Enable Analytics",
      "DenyAnalytics":  "Skip",
    },
    "ChooseYourID": {
      "WhatCardDoYou": "What BC Services Card do you have?",
      "SomePeopleStillCallIt": "Some people still call it a CareCard or a Health Card. It has your personal health number (PHN) on the back.",
      "CombinedCard": "Combined card",
      "CombinedCardActionText": "It's combined with my driver's licence",
      "CombinedCardDescription": "Use this card for a faster way to set up the app.",
      "PhotoCard": "Photo card",
      "PhotoCardActionText": "A card with my photo",
      "PhotoCardDescription": "Use this card for a faster way to set up the app.",
      "NoPhotoCard": "Non photo card",
      "NoPhotoCardActionText": "A card without a photo",
      "NoPhotoCardDescription": "Use this card + photo ID to set up the app.",
      "DontHaveOne": "Don't have one?",
      "CheckBefore": "Check before you continue. It's faster to set up with one of the above.",
      "CheckForServicesCard": "Check for BC Services Card",
      "CheckIfIHave": "Check if I have a BC Services Card",
      "OtherID": "Other ID",
      "OtherIDActionText": "Set up with other ID",
      "OtherIDDescription": "This option takes the longest to set up. You'll need 2 IDs to set up the app and have limited access to services.",
    },
    "Instructions": {
      "Heading": "Provide the card serial number on the back right side of your card.",
      "Paragraph": "When scanning, you should place the card in front of a white background for best results.",
      "ScanBarcode": "Scan Barcode with Camera",
      "EnterManually": "Enter Serial Number Manually",
    },
    "Scan": {
      "NoAccountFound": "No account found, restart the app and try again.",
      "NoAttestationResponse": "No attestation response, check your connection and try again.",
      "NoDeviceCodeFound": "No device code found",
      "InvalidQrCode": "Invalid QR code",
      "WillScanAutomatically": "Will scan automatically",
      "ErrorDetails": "Error details",
      "Dismiss": "Dismiss",
    },
    "ManualSerial": {
      "InputLabel": "Enter serial number",
      "InputTitle": "Enter your card's serial number manually",
      "InputSubText": "Enter the letter and numbers by the barcode on the back of your card.",
      "EmptySerialError": "Required",
      "CharCountError": "Cannot exceed 15 characters",
    },
    "Birthdate": {
      "CardSerialNumber": "Card serial number: {{ serial }}",
      "Heading": "Enter your birthdate",
      "Paragraph": "Your birthdate is only used to to set up this app. It is not shared.",
    },
    "AdditionalEvidence": {
      "PhotoRequired": "You must provide additional ID because your BC Services Card doesn't have a photo on it.",
      "PhotoRequiredDescription": "It's needed to verify your identity. You'll be asked to provide one or two government-issued IDs.",
      "CheckYourID": "Check your ID",
      "CheckYourIDBullet1": "Has the same name as on your BC Services Card",
      "CheckYourIDBullet2": "Has a recent photo",
      "CheckYourIDBullet3": "Is not expired",
      "LimitedAccess": "Limited access to services",
      "LimitedAccessDescription": "Some services only accept the app when it's set up with a BC Services Card with a photo.",
      "ChooseID": "Choose ID",
      "OpenAccountServices": "Open account services",
    },
    "AccountSetup": {
      "Title": "BC Services Card Account",
      "AddAccount": "Add account",
      "TransferAccount": "Transfer from another device",
      "ContinueAs": "Continue as:",
    },
    "NewSetup": {
      "Title": "New setup",
      "YouWillNeedTo": "You will need to:",
      "AddPhotoID": "Add a photo ID",
      "RecordVideoOrVisit": "Record a short video, have a video call, or visit a Service BC office",
      "WhoseIDQuestion": "Whose ID are you adding?",
      "MyOwnID": "My own ID",
      "SomeoneElsesID": "Someone else's ID",
      "IsOtherPersonWithYou": "Is this other person with you?",
      "Yes": "Yes",
      "No": "No",
      "CannotFinishWithoutOtherPerson": "You will not be able to finish setting up this app without the other person being present.",
      "OKToGiveHelp": "It's OK to give someone a bit of help to setup their account.",
      "YouCan": "You can",
      "YouCanReadInstructions": "Read instructions",
      "YouCanNavigateApp": "Navigate the app",
      "YouCanTypeOrScan": "Type, scan, or take pictures",
      "YouCannot": "You cannot",
      "YouCannotBeInVideo": "Be in video recordings or calls. Only the other person can be."
    },
    "CameraDisclosure": {
      "CameraPermissionRequired": "Camera permission required",
      "CameraPermissionRequiredMessage": "Please enable camera permission to take a photo.",
      "CameraPermissionRequiredMessage2": "Please enable camera permission to scan a QR code.",
      "NoCameraAvailable": "No {{device}} camera available",
      "Error": "Camera Error",
      "ErrorMessage": "An error occurred while using the camera. Please try again.",
      "ErrorTakingPhoto": "Failed to take photo. Please try again.",
      "OK": "OK",
      "CancelCamera": "Cancel camera",
      "TakePhoto": "Take photo",
      "ToggleFlash": "Toggle flash",
    },
    "PermissionDisabled": {
      "OpenSettings": "Open Settings",
      "ContinueWithoutNotifications": "Continue Without Notifications",
      "CameraTitle": "Camera Disabled",
      "CameraDescription": "Follow these steps to allow access to your camera to take a photo, record a video, or scan a QR code.",
      "MicrophoneTitle": "Microphone Disabled",
      "MicrophoneDescription": "Follow these steps to allow access to your microphone to record audio.",
      "NotificationsTitle": "Allow Notifications",
      "NotificationsDescription": "It's recommended you update your settings to allow notifications by following these steps:",
      "CameraAndMicrophoneTitle": "Camera & Microphone Disabled",
      "CameraAndMicrophoneDescription": "Follow these steps to allow access to your camera and microphone to record a video.",
      "Camera": {
        "iOS": {
          "Step1": "1. Tap 'Open Settings' below",
          "Step2": "2. Tap 'Camera'",
          "Step3": "3. Return to the app to continue",
        },
        "Android": {
          "Step1": "1. Tap 'Open Settings' below",
          "Step2": "2. Tap 'Permissions'",
          "Step3": "3. Tap 'Camera'",
          "Step4": "4. Select 'Allow'",
          "Step5": "5. Return to the app to continue",
        },
      },
      "Microphone": {
        "iOS": {
          "Step1": "1. Tap 'Open Settings' below",
          "Step2": "2. Tap 'Microphone'",
          "Step3": "3. Return to the app to continue",
        },
        "Android": {
          "Step1": "1. Tap 'Open Settings' below",
          "Step2": "2. Tap 'Permissions'",
          "Step3": "3. Tap 'Microphone'",
          "Step4": "4. Select 'Allow'",
          "Step5": "5. Return to the app to continue",
        },
      },
      "Notifications": {
        "iOS": {
          "Step1": "1. Tap 'Open Settings' below",
          "Step2": "2. Tap 'Notifications' and enable 'Allow Notifications'",
          "Step3": "3. Return to the app to continue",
        },
        "Android": {
          "Step1": "1. Tap 'Open Settings' below",
          "Step2": "2. Tap 'Notifications'",
          "Step3": "3. Tap 'App notifications'",
          "Step4": "4. Enable 'All BC Services Card notifications'",
          "Step5": "5. Return to the app to continue",
        },
      },
      "CameraAndMicrophone": {
        "iOS": {
          "Step1": "1. Tap 'Open Settings' below",
          "Step2": "2. Tap 'Camera'",
          "Step3": "3. Tap 'Microphone'",
          "Step4": "4. Return to the app to continue",
        },
        "Android": {
          "Step1": "1. Tap 'Open Settings' below",
          "Step2": "2. Tap 'Permissions'",
          "Step3": "3. Tap 'Camera' and select 'Allow'",
          "Step4": "4. Go back and tap 'Microphone'",
          "Step5": "5. Select 'Allow'",
          "Step6": "6. Return to the app to continue",
        },
      },
    },
    "EnterEmail": {
      "ErrorTitle": "Error submitting email",
      "EmailSkip": "Are you sure you don't want to provide it?",
      "EmailSkipMessage": "It is less secure without it as we can't notify you of logins or changes to your account.",
      "EmailSkipButton": "Provide email address",
      "EmailSkipButton2": "Skip",
      "EnterEmailAddress": "Enter your email address",
      "EmailDescription1": "It is recommended that you provide one for security purposes.",
      "EmailDescription2": "You will only get emails about logins and changes to your account. It also makes it quicker to set up another mobile card.",
    },
    "EmailConfirmation": {
      "ErrorTitle": "Error verifying confirmation code",
      "EmailError": "Please enter a valid email address (name@host.com).",
      "CodeError": "Please enter a six digit verification code",
      "ErrorResendingCode": "Error resending code",
      "CodeResent": "Code resent",
      "UnableToOpenEmail": "Unable to open email",
      "UnableToOpenEmailMessage": "Please check your email manually using your preferred email app.",
      "VerifyYourEmail": "Verify your email",
      "EnterTheSixDigitCode": "Enter the six digit code sent to your email",
      "ResendCode": "Resend code",
      "GoToEmail": "Go to my email",
      "OKButton": "OK",
    },
    "VerifyIdentity": {
      "DeviceCodeError": "Device code or user code is missing in the store.",
      "VerifyInPersonTitle": "Verify in person",
      "WhereToGo": "Where to go",
      "WhereToGoLink": "A Service BC Location",
      "WhatToBring": "What to bring",
      "ThisDevice": "This device",
      "YourBCServicesCard": "Your BC Services Card - if it's a non-photo card, bring your additional ID too",
      "ShowThisConfirmationNumber": "Show this confirmation number",
      "YouMustCompleteThisBy": "You must complete this by",
      "YouHaveNotBeenVerified": "You have not yet been verified",
      "Complete": "Complete",
      "CardSerialNumber": "Card serial number: {{ serial }}",
    },
    "SendVideo": {
      "InformationRequired": {
        "Heading1": "Photo of your face",
        "Heading2": "Video of your face",
        "ActionLabel": "Take Photo",
        "ActionLabel2": "Record Video",
        "ButtonText": "Send to Service BC Now",
      },
      "PendingReview":{
        "Heading": "Request pending review",
        "Description1": "We review requests:",
        "Bullet1": "Monday to Friday, 9am to 5pm",
        "Bullet2": "In the order they're received",
        "Description2": "Usually, we review requests within 2 business days. During busy periods, it may take longer.",
        "Description3": "After it's reviewed, you will get an email if your provided your email.",
        "Description4": "Do not resend your video. If you do, your request will go to the back of the queue.",
        "ButtonText": "Ok",
      },
      "SuccessfullySent": {
        "Heading": "We've received your request to verify your identity.",
        "Description1": "We review requests:",
        "Bullet1": "Monday to Friday, 9am to 5pm",
        "Bullet2": "In the order they're received",
        "Description3": "Usually, we review requests within 2 business days. During busy periods, it may take longer.",
        "ButtonText": "Ok"
      },
      "TakePhoto": {
        "CameraInstructions": "Position your face within the oval and press the button on the screen",
      },
      "TakeVideo": {
        "RecordingError": "Recording error",
        "RecordingErrorDescription": "There was an issue with the recording. Please try again.",
        "CameraPermissionRequired": "Camera Permission Required",
        "CameraPermissionRequiredDescription": "Please enable camera permission to take a photo.",
        "MicrophonePermissionRequired": "Microphone Permission Required",
        "MicrophonePermissionRequiredDescription": "Please enable microphone permission to record a video.",
        "CameraError": "Camera Error",
        "CameraErrorMessage": "There was an issue with the camera. Please try again.",
        "CameraAndMicrophonePermissionsRequired": "Camera and microphone permissions required",
        "NoFrontCameraAvailable": "No front camera available",
        "RecordingWillStartIn": "Recording will start in",
        "ShowNextPrompt": "Show Next Prompt",
        "Done": "Done",
        "StartRecordingButton": "Start Recording Video",
      },
      "VideoInstructions": {
        "Heading1": "Record a short video.",
        "Heading2": "You'll be asked to",
        "Heading3": "A person at Service BC will watch the video. They need to hear and see you clearly.",
        "Bullet1": "Keep the video under 30 seconds in length",
        "Bullet2": "Be the only person in the video",
        "Bullet3": "Be in a quiet place",
        "Bullet4": "Hold this device in front of your face",
        "Bullet5": "Check your face can be seen in the video",
        "Bullet6": "Say your first and last name",
        "Heading4": "Videos with inappropriate, offensive, or harassing behavior will not be accepted.",
        "StartRecordingButton": "Start Recording Video",
      },
      "VideoReview": {
        "VideoErrorPath":"Video path and thumbnail path are required",
        "Heading": "Can you see and hear yourself clearly in the video?",
        "UseVideo": "Use this video",
        "RetakeVideo": "Retake video",
        "TogglePlayPause": "Toggle play pause",
      },
      "VideoTooLong": {
        "Heading": "Sorry, your video is too long.",
        "Description1": "Your video has to be less than 30 seconds.",
        "Description2": "Your video was {{videoLengthSeconds}} seconds.",
        "ButtonText": "Retake",
        "CancelButtonText": "Cancel",
      },
      "UploadProgress": {
        "PreparingVideo": "Preparing your photo and video for verification",
        "PreparingDocuments": "Preparing additional documents",
        "UploadingInformation": "Uploading your documents securely",
        "FinalizingVerification": "Finalizing your request"
      }
    },
    "MismatchedSerial": {
      "Heading": "Card not found",
      "Description1": "Check the card serial number and birthdate match what is on your card:",
      "Description2": "Check your card is a BC Services Card by looking at the front of your card:",
      "SerialNumber": "Serial number: {{serial}}",
      "Birthdate": "Birthdate: {{birthdate}}",
    },
    "BirthdateLockout": {
      "Heading": "Sorry, you've tried too many times",
      "Message": "Please try again later.",
    },
    "PhotoInstructions": {
      "Heading": "Take a photo of your face. The agent will use this photo when verifying your identity.",
      "Bullet1": "Hold your phone in front of you",
      "Bullet2": "Remove your glasses for the photo only",
      "Bullet3": "Be the only person in the photo",
      "Bullet4": "Look like the photo on your BC Services Card or photo ID",
      "TakePhoto": "Take Photo of Face",
    },
    "PhotoReview": {
      "PathRequired": "Photo path is required",
      "UsePhoto": "Use this photo",
      "RetakePhoto": "Retake photo",
    },
    "TransferQRInformation": {
      "Title": "Open the BC Services Card app on your other mobile device",
      "Instructions": "Scan the QR code with the BC Services Card app on your other mobile device.",
      "Warning" : "Do not scan with the camera app.",
      "GetQRCode": "Get QR Code",
      "LearnMore": "Learn more"
    },
    "TransferInformation": {
      "Title": "Have this app on another device?",
      "Instructions": "You can transfer your account to that other device. No need to provide ID or verify your identity again.",
      "TransferAccount": "Transfer Account",
    },
    "TransferInstructions": {
      "Title": "Scan your QR code to transfer your account",
      "Step1": "1. On your other device, open the BC Services Card app and go to the Account section.",
      "Step2": "2. Choose 'Transfer to another device' to get your QR code.",
      "Step3": "3. Continue on this device and scan that QR code.",
      "ScanQRCode": "Scan QR Code",
    },
    "TransferQRDisplay": {
      "Instructions": "Scan this QR code in the BC Services Card app on your other mobile device",
      "GetNewQRCode": "Get new QR code",
    },
    "TransferSuccess": {
      "Title": "QR code scan complete",
      "Description": "The app should be set up on your other mobile device.",
      "ExtraText": "If you no longer need to use the app on this device, you can remove your account.",
      "ButtonText": "Ok"
    },
    "Verification": {
      "Title": "You're all set",
      "Description": "Use this app to securely log in to many different websites.",
      "ExtraText": "Remember, it is not a health card, vaccine card, driver's license, or photo ID.",
      "ButtonText": "Ok"
    },
    "CancelledVerification": {
      "Title": "Your identity couldn't be verified",
      "Label": "Details from Service BC agent: \n {{reason}}",
      "Button": "Ok",
      "NoReason": "No reason provided"
    },
    "DualNonBCSCEvidence": {
      "Heading": "You must provide two government-issued IDs",
      "Description": "It's needed to verify your identity.",
      "CheckYourID": "Check your IDs",
      "CheckYourIDBullet1": "Both IDs should have the same name",
      "CheckYourIDBullet2": "At least one must be issued in Canada",
      "CheckYourIDBullet3": "One must have a recent photo",
      "CheckYourIDBullet4": "Both must not be expired",
    },
    "IDPhotoInformation": {
      "Heading": "Take a photo of your ID. An agent will look at this photo when verifying your identity.",
      "IDPhotoInstructionsBullet1": "Center your ID within the frame",
      "IDPhotoInstructionsBullet2": "Have no other objects in the photo",
      "IDPhotoInstructionsBullet3": "Make sure the entire ID is visible",
      "IDPhotoInstructionsBullet4": "Make sure the image is clear without any glare or shadows",
      "TakePhoto": "Take photo of ID",
    },
    "VideoTips": {
      "PrivatePlace": "Find a private place to talk",
      "OnlyPerson": "Be the only person in the video",
      "RemoveGlasses": "Remove your glasses (if possible)"
    },
    "VideoCall": {
      "MissingSession": "Missing required parameters to end session",
      "MissingSessionOrCallId": "Missing session or call ID for keep-alive update",
      "DeviceCodeError": "Missing device or user code",
      "ServiceBC": "Service BC",
      "BeforeYouCallTitle": "Before you call",
      "WiFiRecommended": "Wi-Fi Recommended",
      "StandardDataCharges": "Standard data charges may apply for calls over a cellular network.",
      "CellularNetworkWarning": "The app detected you're on a cellular network. ",
      "FindPrivatePlace": "Find a Private Place to Talk",
      "MakeSureOnlyYou": "Make sure you'll be the only person in the video.",
      "DefaultHours": "Monday to Friday\n7:30am - 5:00pm Pacific Time",
      "ContactCentrePrivacy": "Contact Centre Privacy",
      "PrivacyNotice": "During a video call, Service BC will ask for and collect personal information. The personal information you will provide is collected for the purpose of verification of your BC Services Card. This information is collected under the authority of Section 26(c) and 26(e) of the Freedom of Information and Protection of Privacy Act (FIPPA).",
      "PrivacyContactInfo": "If you have further questions about privacy, please contact Chief Privacy Officer, 100 - 722 Johnson Street, Victoria, BC, V8W 1N1, or by phone\n250-405-3726",
      "Assistance": "Need assistance?",
      "StartVideoCallDescription": "Start a video call with a Service BC agent. They will verify your identity to finish setting up this app.",
      "YouShould": "You should:",
      "StartCall": "Start call",
      "StartVideoCall": "Start video call",
      "CallStates": {
        "CreatingSession": "Creating video session...",
        "ConnectingWebRTC": "Connecting to video service...",
        "WaitingForAgent": "Waiting for an agent to join...",
        "Initializing": "Initializing...",
        "CallEnded": "Call ended, checking verification..."
      },
      "Loading": {
        "OneMomentPlease": "One moment please...",
        "SettingThingsUp": "We're setting things up for you",
        "TakingLongerThanUsual": "This is taking longer than usual. Please be patient.",
      },
      "Banners": {
        "VideoWillResume": "Video will resume when you return to this app",
        "AgentCantSeeYou": "Agent can't see you while your video is off",
        "AgentCantHearYou": "Agent can't hear you while your microphone is muted",
        "VolumeLow": "Your volume is low, you may need to turn it up to hear the agent"
      },
      "Errors": {
        "ConnectionError": "Connection Error",
        "GenericError": "An error occurred",
        "TryAgain": "Try Again",
        "GoBack": "Go Back"
      },
      "CallBusyOrClosed": {
        "AllAgentsBusy": "All agents are busy",
        "CallUsLater": "Call us later",
        "AllAgentsBusyMessage": "We're sorry your call couldn't be answered. All of our agents are busy at the moment. Please call us back during our hours of service.",
        "CurrentlyClosedMessage": "We are currently closed. To talk to one of our agents to verify by video, call us during our hours of service.",
        "HoursOfService": "Hours of Service",
        "Reminder": "Reminder",
        "AddCardAgainReminder": "You'll need to add your card again if you don't finish verifying by {{date}}.",
        "SendVideoInstead": "Send video instead"
      },
      "VerifyNotComplete": {
        "Title": "Verify not complete",
        "NotVerifiedYet": "Your identity is not verified yet.",
        "HavingTrouble": "Having trouble?",
        "TroubleshootingTips": "If you are having issues with audio or video, try out the following tips. If you're still having trouble, call us.",
        "SendVideoInstead": "Send video instead",
        "TryAgain": "Try again"
      },
    },
    "EvidenceTypeList": {
      "Heading": "Choose photo ID",
      "Description": "Use an ID that has the same name as on your BC Services Card.",
      "NonBCSCDescription": "Use an ID that has the same name as your first ID.",
      "FirstID": "Choose your first ID",
      "SecondID": "Choose your second ID"
    },
    "EvidenceIDCollection": {
      "Heading1": "Enter the information",
      "Heading2": "exactly as shown",
      "Heading3": "on the ID.",
      "DocumentNumberSubtext": "For example:",
      "DocumentNumberError": "Please enter a valid document number",
      "FirstNameLabel": "First name",
      "FirstNameSubtext": "Your first given name",
      "FirstNameError": "Please enter a first name",
      "LastNameLabel": "Last name",
      "LastNameError": "Please enter a last name",
      "LastNameSubtext": "Also known as surname or family name",
      "BirthDateLabel": "Birth date",
      "BirthDateSubtext": "Enter your birth date",
      "BirthDateError": "Please enter a valid birth date (YYYY-MM-DD)",
      "BirthDateAgeError": "You must be {{ minimumAge }} years or older to set up a mobile card",
      "BirthDatePickerLabel": "Select birth date",
      "BirthDatePickerAccessibilityLabel": "Birth date picker",
      "MiddleNamesLabel": "Middle names",
      "MiddleNamesSubtext": "Additional given names. Only up to 2 are needed",
      "MiddleNamesError": "Please enter up to two middle names",
    },
    "Address": {
      "Heading": "Address",
      "Paragraph": "Enter the address of where you live.",
      "StreetAddressLabel": "Street Line 1",
      "StreetAddressSubtext": "Your residential street address",
      "StreetAddressRequired": "Please enter a street address",
      "CityLabel": "City",
      "CitySubtext": "The city of your current address",
      "CityRequired": "Please enter a city",
      "ProvinceLabel": "Province or Territory",
      "ProvinceSubtext": "Select a province or territory",
      "ProvinceInvalid": "Please enter a valid Canadian province or territory",
      "PostalCodeLabel": "Postal Code",
      "PostalCodeSubtext": "Your postal code in format A1A 2B2",
      "PostalCodeInvalid": "Please enter a valid postal code in A1A 2B2 format",
      "MissingPrerequisiteAttributes": "Missing prerequisite user attributes",
      "NoDeviceCodeFound": "Device previously registered, but no deviceCode found in store",
      "AddressSaved": "Address saved",
      "AuthorizationErrorTitle": "Authorization failed",
      "AuthorizationErrorMessage": "Unable to authorize device. Please check your connection and try again.",
    },
    "Account": {
      "RemoveAccount": "Remove account",
      "RemoveAccountTitle": "Remove account from this app?",
      "RemoveAccountParagraph": "To use this app again, you'll need to provide your ID and verify your identity.",
      "RemoveAccountLoading": "Removing account...",
      "TransferAccount": "Transfer account to another device",
      "AccountDetails": "All account details",
      "AccountDetailsDescription": "View your account activity, manage your email address and more.",
      "AccountInfo" : {
        "ManageDevices": "Manage Devices",
        "Description": "This cannot be used as photo ID, a driver's licence, or a health card.",
        "AppExpiryDate": "App expiry date",
        "AccountType": "Account type",
        "AccountTypeNonBCServicesCard": "Non BC Services Card",
        "Address": "Address",
        "DateOfBirth": "Date of birth",
        "EmailAddress": "Email address",
        "MyDevicesCount": "My devices ({{count}})",
        "MyDevices": "My devices",
      }
    },
    "VerificationMethods": {
      "SendVideoTitle": "Send a video",
      "SendVideoDescription": "Record a short video and we'll review it to verify your identity.",
      "VideoCallTitle": "Video call",
      "VideoCallDescription": "We will verify your identity during a video call.",
      "InPersonTitle": "In person",
      "InPersonDescription": "Find out where to go and what to bring.",
      "CannotSendVideo": "Cannot send a video?",
      "CannotMakeItToServiceBC": "Cannot make it to a Service BC Office?",
      "CannotVideoCall": "Cannot video call?"
    },
  },
  "RemoteLogging": {
    "ScreenTitle": "Remote troubleshooting",
    "Heading": "Collection notice",
    "CollectionNoticePart1": "Turning on remote troubleshooting will",
    "CollectionNoticeBold": " record Wallet and Credential usage and any associated personal information",
    "CollectionNoticePart2": " while it is turned on.\n\nRemote troubleshooting turns off after 1 hour. The information collected is deleted after 3 days.\n\nThis information is collected by Ministry of Citizens' Services - Cybersecurity and Digital Trust Branch under sections 26(c) and 26(e) of the Freedom of Information and Protection of Privacy Act, and will only be used for the purpose of customer support and troubleshooting.\n\nFor more information, including who to contact, read the",
    "CollectionNoticeLink": "Privacy Policy.",
    "CollectionNoticeWarning": "Only turn on remote troubleshooting if you contacted the support line first and a service agent from the Government of British Columbia asked you to turn it on. They will never contact first. You are never required to turn it on.",
    "CheckBoxTitle": "I understand and want to turn on remote troubleshooting.",
    "IAgree": "I Agree",
    "ButtonTitle": "Turn on",
    "SessionID": "Session ID",
    "Banner": "Remote Troubleshoot on. ID: {{ sessionId }}"
  },
  "HelpCentre": {
    "Title": "Help Centre"
  },
  "Alerts": {
    "Actions": {
      "DefaultOK": "OK",
      "Close": "Close",
    },
    "UnsecuredNetwork": {
      "Title": "Unsecured Network",
      "Description": "A secure internet connection is required. Please check your network or try another network."
    },
    "ServerTimeout": {
      "Title": "Connection Error",
      "Description": "Please try again later."
    },
    "ServerError": {
      "Title": "Server Error",
      "Description": "There is a problem with the service. Please try again later. (error 302)"
    },
    "AppUpdateRequired": {
      "Title": "App Update Required",
      "Description": "You must update this app to continue.",
      "Action1": "Go To App Store"
    },
    "ProblemWithAccount": {
      "Title": "Problem with Account",
      "Description": "There may be a problem with the account on this device. Please try again. If the problem continues, remove your account and set it up again. (error 214)",
      "Action1": "Remove Account",
    },
    "ForgetPairings": {
      "Title": "Success",
      "Description": "You have successfully unpaired your device."
    },
    "LoginServerError": {
      "Title": "Problem with Login",
      "Description": "Please try again later. (error 303)"
    },
    "TooManyAttempts": {
      "Title": "Sorry, You've Tried Too Many Times",
      "Description": "Please try again later."
    },
    "SetupExpired": {
      "Title": "Setup Expired",
      "Description": "You must start set up again."
    },
    "VerificationNotComplete": {
      "Title": "Verify Not Complete",
      "Description": "Go to a Service BC location to verify your identity."
    },
    "ProblemWithLogin": {
      "Title": "Problem with Login",
      "Description": "Please try again later. (error 304)"
    },
    "InvalidPairingCode": {
      "Title": "Invalid Pairing Code",
      "Description": "You've entered an invalid pairing code. Please re-enter your pairing code and try again."
    },
    "InvalidPairingCodeSameDevice": {
      "Title": "Invalid Login",
      "Description": "Please try again later. If the problem continues, contact the BC Services Card Help Desk."
    },
    "LiveCallFileUploadError": {
      "Title": "Problem Calling Agent",
      "Description": "Please try again later.",
    },
    "CancelMobileCardSetup": {
      "Title": "Are you sure?",
      "Description": "This will delete all information you entered to set up the app. You will have to start again.",
      "Action1": "Reset App"
    },
    "CancelVerificationRequest": {
      "Title": "Are you sure?",
      "Description": "Your verification request sent to Service BC will be deleted. Then you can choose another way to verify.",
      "Action1": "Delete Verify Request",
    },
    "DataUseWarning": {
      "Title": "Data Use",
      "Description": "The app detected that you’re on a cellular network. Calls are free over Wi-Fi. Standard data charges apply for calls over a cellular network.",
      "Action1": "Use Data",
    },
    "ThirdPartyKeyboard": {
      "Title": "Warning",
      "Description": "This device is using a non-standard keyboard. It may be able to collect everything you type. Do you want to continue using the third party keyboard?",
      "Action1": "Continue",
      "Action2": "Change Keyboard"
    },
    "AccountUpdated": {
      "Title": "Account Updated",
      "Description": "Your account has been automatically updated with information from your new BC Services Card.",
    },
    "LiveCallHavingTrouble": {
      "Title": "Having trouble?",
      "Description": "Please end your call to get additional help and troubleshooting tips.",
      "Action1": "End Call",
    },
    "ClockSkewError": {
      "Title": "Date and Time on This Device Is Incorrect",
      "Description": "You must correct it before you can use this app. Go to your Settings to update the date and time, or change it to be set automatically.",
      "Action1": "Open Settings",
    },
    "AlreadyVerified": {
      "Title": "Problem Checking Status",
      "Description": "Please close the app and try again.",
    },
    "FileUploadError": {
      "Title": "Problem with Connection",
      "Description": "Please try again."
    },
  },
  "BCWalletError": {
    "Camera": {
      "Title": "Camera Error",
      "Broken": "Unable to access the camera. Please check your device settings.",
      "InvalidQRCode": "The QR code could not be recognized. Please try again.",
    },
    "Network": {
      "Title": "Server Error",
      "UnknownServerErrorDescription": "An unknown server error occurred. Please try again later.",
      "NoInternetTitle": "No Internet Connection",
      "NoInternetDescription": "No internet connection. Please check your network settings and try again.",
      "ServerErrorDescription": "There is a problem with the service. Please try again later. (error 302)",
      "TimeoutTitle": "Connection Error",
      "TimeoutDescription": "Please try again later.",
      "UnsecuredTitle": "Unsecured Network",
      "UnsecuredDescription": "A secure internet connection is required. Please check your network and try again.",
      "ConnectionProblem": "There was a problem with the connection. Please try again.",
      "EmptyResponse": "The server returned an empty response. Please try again.",
      "BadRequest": "The request was invalid. Please try again.",
      "ServerOutage": "The service is currently unavailable. Please try again later.",
      "RetryLater": "The service is busy. Please try again later.",
      "InvalidURL": "The URL is invalid. Please check and try again.",
      "TooManyAttemptsTitle": "Sorry, You've Tried Too Many Times",
      "TooManyAttemptsDescription": "Please try again later.",
    },
    "Login": {
      "Title": "Problem with App",
      "ProblemWithLoginTitle": "Problem with Login",
      "ParseErrorDescription": "Please try again later. (error 304)",
      "Rejected": "There may be a problem with your account in this app. Please try again. If the problem continues, remove and add your account again. ",
      "Unauthorized": "You are not authorized to access this service.",
      "Forbidden": "Access to this service is forbidden.",
      "ServerErrorDescription": "Please try again later. (error 303)",
      "InvalidPairingCodeTitle": "Invalid Pairing Code",
      "InvalidPairingCodeDescription": "You've entered an invalid pairing code. Please re-enter your pairing code and try again.",
      "SameDeviceInvalidPairingCodeTitle": "Invalid Login",
      "SameDeviceInvalidPairingCodeDescription": "Please try again later. If the problem continues, contact the BC Services Card Help Desk."
    },
    "Card": {
      "Title": "Card Error",
      "ExpiredWillRemove": "Your card has expired and will be removed.",
      "Cancelled": "Your card has been cancelled.",
      "Expired": "Your card has expired.",
      "Removed": "Your card has been removed.",
      "TypeChanged": "Your card type has changed.",
      "NotFound": "The card could not be found.",
      "WillExpire": "Your physical card will expire soon. Please renew it.",
    },
    "Verification": {
      "Title": "Verification Error",
      "NotCompleteTitle": "Verify Not Complete",
      "NotCompleteDescription": "Go to a Service BC location to verify your identity.",
      "StepsIncomplete": "Some verification steps are incomplete. Please complete all required steps.",
      "UploadServerError": "Failed to upload verification data. Please try again.",
      "UploadUnknownError": "An unknown error occurred during upload. Please try again.",
      "FileUploadError": "Failed to upload the file. Please try again.",
      "VideoNotComplete": "Video verification is not complete. Please try again.",
      "VideoCaptureError": "An error occurred while capturing video. Please try again.",
      "RemoteIncomplete": "Remote verification is incomplete. Please complete the process.",
      "DeleteRequestError": "Failed to delete the verification request. Please try again.",
      "VideoServiceHoursNull": "Video service hours could not be retrieved. Please try again later.",
      "VerifyRequestExpiredTitle": "Setup Expired",
      "VerifyRequestExpiredDescription": "You must start set up again.",
    },
    "Token": {
      "Title": "Problem with App",
      "Invalid": "There may be a problem with your account in this app. Please try again. If the problem continues, remove and add your account again.",
      "NoTokensReturnedTitle": "Problem with Account",
      "NoTokensReturnedDescription": "No authentication tokens were returned. Please try again.",
      "Null": "Authentication token is missing. Please sign in again.",
      "ExpiryError": "Failed to retrieve token expiry. Please sign in again.",
      "DecryptVerifyError": "Failed to verify authentication. Please sign in again.",
      "DeserializeError": "Failed to process authentication. Please sign in again.",
      "ParseJWTError": "Failed to parse authentication token. Please sign in again.",
      "DecryptJWEError": "Failed to decrypt authentication data. Please sign in again.",
      "MissingJWK": "Authentication key is missing. Please sign in again.",
      "JWSVerificationFailed": "Authentication verification failed. Please sign in again.",
      "JOSEException": "An authentication error occurred. Please sign in again.",
      "ClaimsSetError": "Failed to process authentication claims. Please sign in again.",
      "SignClaimsError": "Failed to sign authentication claims. Please try again.",
      "ParseJWSError": "Failed to parse authentication signature. Please sign in again.",
      "JWTDeviceInfoError": "Failed to process device authentication info. Please try again.",
    },
    "Storage": {
      "Title": "Storage Error",
      "WriteError": "Failed to save data. Please try again.",
      "ReadError": "Failed to read data. Please try again.",
      "KeychainKeyExists": "A security key already exists. Please contact support.",
      "KeychainKeyNotFound": "Security key not found. Please sign in again.",
      "KeychainGenerationError": "Failed to generate security key. Please try again.",
      "DeleteKeyPairError": "Failed to delete security key. Please try again.",
      "KeysOutOfSync": "Your security keys are out of sync. Please sign in again.",
      "ToJSONFailure": "Failed to convert data to JSON format. Please try again.",
      "ToJSONStringFailure": "Failed to serialize data. Please try again.",
    },
    "Device": {
      "Title": "Device Error",
      "AppUpdateRequiredTitle": "App Update Required",
      "AppUpdateRequiredDescription": "You must update this app to continue.",
      "ProtectionRequired": "Device protection is required. Please enable a passcode or biometrics.",
      "ClockSkew": "Your device clock is not synchronized. Please check your date and time settings.",
      "AuthorizationError": "Device authorization failed. Please try again.",
      "IncorrectOS": "This app is not supported on your current operating system.",
      "KeypairGenerationError": "The app does not appear to be installed correctly. Please remove the app from your device and add it again.",
      "KeypairGenerationTitle": "Problem with App",
    },
    "General": {
      "Title": "Something Went Wrong",
      "Unknown": "An unexpected error occurred. Please try again.",
      "RegistrationError": "Registration failed. Please try again.",
      "AppVersionNotSupported": "This app version is no longer supported. Please update.",
      "RegistrationNull": "Registration data is missing. Please try again.",
      "AuthorizationNull": "Authorization data is missing. Please try again.",
      "DeserializeError": "Failed to process data. Please try again.",
      "SerializeError": "Failed to prepare data. Please try again.",
      "ProviderNull": "Service provider data is missing. Please try again.",
      "RegistrationFailure": "Client registration failed. Please try again.",
      "CreateRegistrationFailed": "Failed to create registration. Please try again.",
      "InvalidRegistration": "The registration request is invalid. Please try again.",
      "MissingJSONValues": "Required data is missing from the response. Please try again.",
      "ServerConfiguration": "Server configuration error. Please try again later.",
      "AddCardServerError": "Failed to add card due to a server error. Please try again.",
      "PINStoreError": "Failed to store PIN. Please try again.",
      "ProviderError": "Service provider error. Please try again.",
      "FetchedProviderNull": "Failed to fetch service provider. Please try again.",
      "TermsOfUseError": "Failed to load terms of use. Please try again.",
      "EmptyKeychain": "Security credentials are empty. Please sign in again.",
      "SetupNotComplete": "App setup is not complete. Please complete the setup process.",
      "StringResourceError": "Failed to retrieve required text resource. Please try again.",
    },
    "Wallet": {
      "Title": "Wallet Error",
      "StateLoadError": "Failed to load wallet state. Please restart the app.",
      "AgentInitError": "Failed to initialize wallet agent. Please restart the app.",
      "SecretNotFound": "Wallet credentials not found. Please sign in again.",
    },
    "Connection": {
      "Title": "Connection Error",
      "ParseInvitationError": "There was a problem parsing the connection invitation.",
      "ReceiveInvitationError": "There was a problem receiving the invitation to connect.",
      "LegacyDIDError": "There was a problem extracting the connection identifier.",
      "AppToAppURLError": "There was a problem opening the app-to-app URL.",
      "ServiceCardAuthError": "There was a problem authenticating with the service card.",
    },
    "Attestation": {
      "Title": "Attestation Error",
      "BadInvitation": "Unable to parse attestation agent invitation.",
      "ConnectionError": "Unable to connect to the attestation service.",
      "NonceError": "There was a problem with the attestation service.",
      "GenerationError": "There was a problem generating attestation.",
      "ValidationError": "There was a problem validating attestation.",
      "AgentUndefined": "The agent cannot be undefined for attestation.",
      "IntegrityUnavailable": "Device integrity service is not available.",
      "GeneralProofError": "There was a problem with the attestation proof.",
      "RequestError": "There was a problem with the attestation request.",
      "UnsupportedPlatform": "Attestation is not supported on this platform.",
    },
  },
}

export default translation
