source 'https://cdn.cocoapods.org'
require_relative '../node_modules/react-native/scripts/react_native_pods'

# prevents location usage from react-native-vision-camera
$VCEnableLocation = false

# From RNP docs here: https://www.npmjs.com/package/react-native-permissions/v/4.0.1
def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end
  
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

# uncomment wanted permissions (also from RNP docs linked above)
setup_permissions([
  # 'AppTrackingTransparency',
  # 'Bluetooth',
  # 'Calendars',
  # 'CalendarsWriteOnly',
  'Camera',
  # 'Contacts',
  'FaceID',
  # 'LocationAccuracy',
  # 'LocationAlways',
  # 'LocationWhenInUse',
  # 'MediaLibrary',
  'Microphone',
  # 'Motion',
  'Notifications'
  # 'PhotoLibrary',
  # 'PhotoLibraryAddOnly',
  # 'Reminders',
  # 'Siri',
  # 'SpeechRecognition',
  # 'StoreKit',
])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'AriesBifold' do
  config = use_native_modules!

  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Enable ccache for all pod targets to speed up C/C++/ObjC compilation.
    # The wrapper scripts fall through to plain clang when ccache is not installed,
    # so this is safe for both local dev and CI.
    ccache_clang   = File.join(__dir__, 'scripts', 'ccache-clang.sh')
    ccache_clangpp = File.join(__dir__, 'scripts', 'ccache-clang++.sh')
    if File.exist?(ccache_clang)
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |build_config|
          build_config.build_settings['CC']  = ccache_clang
          build_config.build_settings['CXX'] = ccache_clangpp
        end
      end
    end
  end
end