source 'https://rubygems.org'
# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 3.3.6"
gem 'cocoapods', '~> 1.14.3', '!= 1.15.0', '!= 1.15.1'
gem 'activesupport', '~> 7.2.3'

gem 'concurrent-ruby', '< 1.3.7'

# Ruby 3.4.0 has removed some libraries from the standard library.
gem 'bigdecimal', '~> 4.1.2'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'
