import { Button, ButtonType, ScreenWrapper, ThemedText, TOKENS, useServices, useTheme } from '@bifold/core'
import { useCallback, useState } from 'react'
import { ScrollView, StyleSheet, View } from 'react-native'
import {
  AccountSecurityMethod,
  canPerformBiometricAuthentication,
  canPerformDeviceAuthentication,
  deleteAccountFlags,
  deleteAuthorizationRequest,
  deletePIN,
  getAccount,
  getAccountFlags,
  getAccountSecurityMethod,
  getAuthorizationRequest,
  getAvailableBiometricType,
  getBestAvailableAccountSecurityMethod,
  hasPINSet,
  isAccountLocked,
  isPINAutoGenerated,
  performDeviceAuthentication,
  removeAccount,
  setAccount,
  setAccountFlags,
  setAccountSecurityMethod,
  setAuthorizationRequest,
  setPIN,
  setupDeviceSecurity,
  unlockWithDeviceSecurity,
  verifyPIN,
  type AccountFlags,
  type NativeAccount,
  type NativeAuthorizationRequest,
} from 'react-native-bcsc-core'

// NOTE: This screen is for testing purposes only and should not be included in production builds.

// Dummy test data
const TEST_PIN = '123456'
const TEST_ISSUER = 'https://idsit.gov.bc.ca/device/'

const TEST_ACCOUNT: Omit<NativeAccount, 'id'> = {
  issuer: TEST_ISSUER,
  clientID: 'test-client-id',
  securityMethod: AccountSecurityMethod.PinWithDeviceAuth,
  nickname: 'Test Account',
  displayName: 'Test User',
}

const TEST_AUTH_REQUEST: NativeAuthorizationRequest = {
  deviceCode: 'test-device-code',
  userCode: 'TEST1234',
  firstName: 'Test',
  lastName: 'User',
  birthdate: new Date('1990-01-01').getDate(),
  status: 1, // pending
  expiry: Date.now() / 1000 + 3600, // 1 hour from now
}

const TEST_ACCOUNT_FLAGS: AccountFlags = {
  isEmailVerified: false,
  userSkippedEmailVerification: true,
  emailAddress: 'test@example.com',
}

const TestButton = ({ title, onPress }: { title: string; onPress: () => void }) => (
  <Button buttonType={ButtonType.Secondary} title={title} accessibilityLabel={title} onPress={onPress} />
)

const SectionHeader = ({ title }: { title: string }) => {
  const { Spacing } = useTheme()
  return (
    <ThemedText variant="bold" style={{ marginTop: Spacing.md, marginBottom: Spacing.xs }}>
      {title}
    </ThemedText>
  )
}

export const AuthTestScreen: React.FC = () => {
  const { Spacing, ColorPalette } = useTheme()
  const [output, setOutput] = useState<string>('Test output will appear here...')
  const [logger] = useServices([TOKENS.UTIL_LOGGER])

  const styles = StyleSheet.create({
    outputBox: {
      padding: Spacing.md,
      borderRadius: 8,
      minHeight: 120,
      maxHeight: 180,
    },
    outputText: {
      fontFamily: 'monospace',
      fontSize: 12,
      color: ColorPalette.grayscale.darkGrey,
    },
    buttonRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.sm,
    },
  })

  const logResult = useCallback(
    (label: string, result: unknown) => {
      const resultStr = typeof result === 'object' ? JSON.stringify(result, null, 2) : String(result)
      setOutput(`${label}:\n${resultStr}`)
      logger.info(`[TEST] ${label}: ${JSON.stringify(result, null, 2)}`)
    },
    [logger],
  )

  const logError = useCallback(
    (label: string, error: unknown) => {
      const errorStr = error instanceof Error ? error.message : String(error)
      setOutput(`❌ ${label} ERROR:\n${errorStr}`)
      logger.error(`[TEST] ${label} ERROR: ${errorStr}`)
    },
    [logger],
  )

  // Account Methods
  const testSetAccount = async () => {
    try {
      await setAccount(TEST_ACCOUNT)
      logResult('setAccount', `Success!`)
    } catch (e) {
      logError('setAccount', e)
    }
  }

  const testGetAccount = async () => {
    try {
      const result = await getAccount()
      logResult('getAccount', result)
    } catch (e) {
      logError('getAccount', e)
    }
  }

  const testRemoveAccount = async () => {
    try {
      await removeAccount()
      logResult('removeAccount', 'Success')
    } catch (e) {
      logError('removeAccount', e)
    }
  }

  // PIN Methods
  const testSetPIN = async () => {
    try {
      const result = await setPIN(TEST_PIN)
      logResult('setPIN', result)
    } catch (e) {
      logError('setPIN', e)
    }
  }

  const testVerifyPIN = async () => {
    try {
      const result = await verifyPIN(TEST_PIN)
      logResult('verifyPIN', result)
    } catch (e) {
      logError('verifyPIN', e)
    }
  }

  const testVerifyWrongPIN = async () => {
    try {
      const result = await verifyPIN('000000')
      logResult('verifyPIN (wrong)', result)
    } catch (e) {
      logError('verifyPIN (wrong)', e)
    }
  }

  const testDeletePIN = async () => {
    try {
      const result = await deletePIN()
      logResult('deletePIN', result)
    } catch (e) {
      logError('deletePIN', e)
    }
  }

  const testHasPINSet = async () => {
    try {
      const result = await hasPINSet()
      logResult('hasPINSet', result)
    } catch (e) {
      logError('hasPINSet', e)
    }
  }

  const testIsPINAutoGenerated = async () => {
    try {
      const result = await isPINAutoGenerated()
      logResult('isPINAutoGenerated', result)
    } catch (e) {
      logError('isPINAutoGenerated', e)
    }
  }

  // Device Auth Methods
  const testPerformDeviceAuth = async () => {
    try {
      const result = await performDeviceAuthentication('Testing biometric auth')
      logResult('performDeviceAuthentication', result)
    } catch (e) {
      logError('performDeviceAuthentication', e)
    }
  }

  const testCanPerformDeviceAuth = async () => {
    try {
      const result = await canPerformDeviceAuthentication()
      logResult('canPerformDeviceAuthentication', result)
    } catch (e) {
      logError('canPerformDeviceAuthentication', e)
    }
  }

  const testGetBiometricType = async () => {
    try {
      const result = await getAvailableBiometricType()
      logResult('getAvailableBiometricType', result)
    } catch (e) {
      logError('getAvailableBiometricType', e)
    }
  }

  const testCanPerformBiometric = async () => {
    try {
      const result = await canPerformBiometricAuthentication()
      logResult('canPerformBiometricAuthentication', result)
    } catch (e) {
      logError('canPerformBiometricAuthentication', e)
    }
  }

  // Security Method
  const testSetSecurityMethod = async () => {
    try {
      const result = await setAccountSecurityMethod(AccountSecurityMethod.DeviceAuth)
      logResult('setAccountSecurityMethod', result)
    } catch (e) {
      logError('setAccountSecurityMethod', e)
    }
  }

  const testGetSecurityMethod = async () => {
    try {
      const result = await getAccountSecurityMethod()
      logResult('getAccountSecurityMethod', result)
    } catch (e) {
      logError('getAccountSecurityMethod', e)
    }
  }

  const testIsAccountLocked = async () => {
    try {
      const result = await isAccountLocked()
      logResult('isAccountLocked', result)
    } catch (e) {
      logError('isAccountLocked', e)
    }
  }

  const testGetBestAvailableAccountSecurityMethod = async () => {
    try {
      const result = await getBestAvailableAccountSecurityMethod()
      logResult('getBestAvailableAccountSecurityMethod', result)
    } catch (e) {
      logError('getBestAvailableAccountSecurityMethod', e)
    }
  }

  // Device Security
  const testSetupDeviceSecurity = async () => {
    try {
      const result = await setupDeviceSecurity()
      logResult('setupDeviceSecurity', result)
    } catch (e) {
      logError('setupDeviceSecurity', e)
    }
  }

  const testUnlockWithDeviceSecurity = async () => {
    try {
      const result = await unlockWithDeviceSecurity('Unlock to test')
      logResult('unlockWithDeviceSecurity', result)
    } catch (e) {
      logError('unlockWithDeviceSecurity', e)
    }
  }

  // Authorization Request
  const testSetAuthRequest = async () => {
    try {
      const result = await setAuthorizationRequest(TEST_AUTH_REQUEST)
      logResult('setAuthorizationRequest', result)
    } catch (e) {
      logError('setAuthorizationRequest', e)
    }
  }

  const testGetAuthRequest = async () => {
    try {
      const result = await getAuthorizationRequest()
      logResult('getAuthorizationRequest', result)
    } catch (e) {
      logError('getAuthorizationRequest', e)
    }
  }

  const testDeleteAuthRequest = async () => {
    try {
      const result = await deleteAuthorizationRequest()
      logResult('deleteAuthorizationRequest', result)
    } catch (e) {
      logError('deleteAuthorizationRequest', e)
    }
  }

  // Account Flags
  const testSetAccountFlags = async () => {
    try {
      const result = await setAccountFlags(TEST_ACCOUNT_FLAGS)
      logResult('setAccountFlags', result)
    } catch (e) {
      logError('setAccountFlags', e)
    }
  }

  const testGetAccountFlags = async () => {
    try {
      const result = await getAccountFlags()
      logResult('getAccountFlags', result)
    } catch (e) {
      logError('getAccountFlags', e)
    }
  }

  const testDeleteAccountFlags = async () => {
    try {
      const result = await deleteAccountFlags()
      logResult('deleteAccountFlags', result)
    } catch (e) {
      logError('deleteAccountFlags', e)
    }
  }

  return (
    <ScreenWrapper padded scrollViewContainerStyle={{ gap: Spacing.sm, flexGrow: 1 }}>
      {/* Output Display */}
      <View style={[styles.outputBox, { backgroundColor: ColorPalette.grayscale.lightGrey }]}>
        <ScrollView>
          <ThemedText style={styles.outputText}>{output}</ThemedText>
        </ScrollView>
      </View>

      {/* Account Methods */}
      <SectionHeader title="Account" />
      <View style={styles.buttonRow}>
        <TestButton title="Set Account" onPress={testSetAccount} />
        <TestButton title="Get Account" onPress={testGetAccount} />
        <TestButton title="Remove Account" onPress={testRemoveAccount} />
      </View>

      {/* PIN Methods */}
      <SectionHeader title="PIN" />
      <View style={styles.buttonRow}>
        <TestButton title="Set PIN" onPress={testSetPIN} />
        <TestButton title="Verify PIN ✓" onPress={testVerifyPIN} />
        <TestButton title="Verify PIN ✗" onPress={testVerifyWrongPIN} />
      </View>
      <View style={styles.buttonRow}>
        <TestButton title="Delete PIN" onPress={testDeletePIN} />
        <TestButton title="Has PIN?" onPress={testHasPINSet} />
        <TestButton title="Auto PIN?" onPress={testIsPINAutoGenerated} />
      </View>

      {/* Device Auth */}
      <SectionHeader title="Device Auth" />
      <View style={styles.buttonRow}>
        <TestButton title="Perform Auth" onPress={testPerformDeviceAuth} />
        <TestButton title="Can Auth?" onPress={testCanPerformDeviceAuth} />
        <TestButton title="Biometric Type" onPress={testGetBiometricType} />
      </View>
      <View style={styles.buttonRow}>
        <TestButton title="Can Biometric?" onPress={testCanPerformBiometric} />
      </View>

      {/* Security Method */}
      <SectionHeader title="Security Method" />
      <View style={styles.buttonRow}>
        <TestButton title="Set Method" onPress={testSetSecurityMethod} />
        <TestButton title="Get Method" onPress={testGetSecurityMethod} />
        <TestButton title="Is Locked?" onPress={testIsAccountLocked} />
      </View>
      <View style={styles.buttonRow}>
        <TestButton title="Best Available Method" onPress={testGetBestAvailableAccountSecurityMethod} />
      </View>

      {/* Device Security */}
      <SectionHeader title="Device Security" />
      <View style={styles.buttonRow}>
        <TestButton title="Setup" onPress={testSetupDeviceSecurity} />
        <TestButton title="Unlock" onPress={testUnlockWithDeviceSecurity} />
      </View>

      {/* Auth Request */}
      <SectionHeader title="Auth Request" />
      <View style={styles.buttonRow}>
        <TestButton title="Set" onPress={testSetAuthRequest} />
        <TestButton title="Get" onPress={testGetAuthRequest} />
        <TestButton title="Delete" onPress={testDeleteAuthRequest} />
      </View>

      {/* Account Flags */}
      <SectionHeader title="Account Flags" />
      <View style={styles.buttonRow}>
        <TestButton title="Set Flags" onPress={testSetAccountFlags} />
        <TestButton title="Get Flags" onPress={testGetAccountFlags} />
        <TestButton title="Delete Flags" onPress={testDeleteAccountFlags} />
      </View>
    </ScreenWrapper>
  )
}
