import { BCSCLoadingProvider } from '@/bcsc-theme/contexts/BCSCLoadingContext'
import { useNavigation } from '@mocks/@react-navigation/native'
import { BasicAppContext } from '@mocks/helpers/app'
import { fireEvent, render, waitFor } from '@testing-library/react-native'
import React from 'react'
import { canPerformDeviceAuthentication, setAccountSecurityMethod, setPIN, verifyPIN } from 'react-native-bcsc-core'
import Toast from 'react-native-toast-message'
import { ChangePINContent } from './ChangePINContent'

jest.mock('react-native-bcsc-core', () => ({
  canPerformDeviceAuthentication: jest.fn().mockResolvedValue(false),
  setPIN: jest.fn().mockResolvedValue({ success: true, walletKey: 'new-key', isAutoGenerated: false }),
  verifyPIN: jest.fn().mockResolvedValue({ success: true, walletKey: 'current-key', locked: false, message: '' }),
  setAccountSecurityMethod: jest.fn().mockResolvedValue(true),
  AccountSecurityMethod: {
    PinNoDeviceAuth: 'app_pin_no_device_authn',
    PinWithDeviceAuth: 'app_pin_has_device_authn',
    DeviceAuth: 'device_authentication',
  },
}))

jest.mock('react-native-toast-message', () => ({
  show: jest.fn(),
}))

jest.mock('@/bcsc-theme/hooks/useBCSCApiClient', () => ({
  useBCSCApiClientState: () => ({
    client: {},
    isClientReady: true,
  }),
}))

jest.mock('@/bcsc-theme/api/hooks/useRegistrationApi', () => ({
  __esModule: true,
  default: () => ({
    register: jest.fn().mockResolvedValue(undefined),
  }),
}))

const mockSetPIN = jest.mocked(setPIN)
const mockVerifyPIN = jest.mocked(verifyPIN)
const mockCanPerformDeviceAuthentication = jest.mocked(canPerformDeviceAuthentication)
const mockSetAccountSecurityMethod = jest.mocked(setAccountSecurityMethod)
const mockToastShow = jest.mocked(Toast.show)

describe('ChangePINContent', () => {
  let mockNavigation = useNavigation()
  let onChangePINSuccess = mockNavigation['goBack']
  let onCreatePINSuccess = mockNavigation['goBack']

  beforeEach(() => {
    mockNavigation = useNavigation()
    onChangePINSuccess = mockNavigation.goBack
    onCreatePINSuccess = mockNavigation.goBack
    jest.clearAllMocks()
    jest.useFakeTimers()
  })

  afterEach(() => {
    jest.useRealTimers()
  })

  describe('when changing existing PIN (isChangingExistingPIN = true)', () => {
    it('renders ChangePINForm with current PIN field', () => {
      const tree = render(
        <BasicAppContext>
          <BCSCLoadingProvider>
            <ChangePINContent
              onChangePINSuccess={onChangePINSuccess}
              onCreatePINSuccess={onCreatePINSuccess}
              isChangingExistingPIN={true}
            />
          </BCSCLoadingProvider>
        </BasicAppContext>
      )

      expect(tree.getByText('BCSC.ChangePIN.EnterCurrentPIN')).toBeTruthy()
      expect(tree.getByText('BCSC.ChangePIN.EnterNewPIN')).toBeTruthy()
      expect(tree.getByText('BCSC.ChangePIN.ReenterNewPIN')).toBeTruthy()
      expect(tree).toMatchSnapshot()
    })

    it('shows change PIN button', () => {
      const tree = render(
        <BasicAppContext>
          <BCSCLoadingProvider>
            <ChangePINContent
              onChangePINSuccess={onChangePINSuccess}
              onCreatePINSuccess={onCreatePINSuccess}
              isChangingExistingPIN={true}
            />
          </BCSCLoadingProvider>
        </BasicAppContext>
      )

      expect(tree.getByText('BCSC.ChangePIN.ButtonTitle')).toBeTruthy()
    })

    it('navigates back and shows toast on successful PIN change', async () => {
      mockVerifyPIN.mockResolvedValue({
        success: true,
        locked: false,
        remainingTime: 0,
        walletKey: 'current-key',
      })
      mockSetPIN.mockResolvedValue({
        success: true,
        walletKey: 'new-key',
        isAutoGenerated: false,
      })

      const tree = render(
        <BasicAppContext>
          <BCSCLoadingProvider>
            <ChangePINContent
              onChangePINSuccess={onChangePINSuccess}
              onCreatePINSuccess={onCreatePINSuccess}
              isChangingExistingPIN={true}
            />
          </BCSCLoadingProvider>
        </BasicAppContext>
      )

      // Fill in all PIN fields
      const inputs = tree.getAllByAccessibilityHint('Enter your 6-digit PIN')
      fireEvent.changeText(inputs[0], '123456') // Current
      fireEvent.changeText(inputs[1], '654321') // New
      fireEvent.changeText(inputs[2], '654321') // Confirm

      // Check the checkbox
      const checkbox = tree.getByTestId('com.ariesbifold:id/IUnderstand')
      fireEvent.press(checkbox)

      // Press change PIN button
      const button = tree.getByTestId('com.ariesbifold:id/ChangePIN')
      fireEvent.press(button)

      await waitFor(() => {
        expect(mockVerifyPIN).toHaveBeenCalledWith('123456')
        expect(mockSetPIN).toHaveBeenCalledWith('654321')
        expect(onChangePINSuccess).toHaveBeenCalled()
        expect(mockToastShow).toHaveBeenCalledWith(
          expect.objectContaining({
            type: 'success',
            text1: 'BCSC.Settings.ChangePIN.SuccessTitle',
            text2: 'BCSC.Settings.ChangePIN.PINChanged',
          })
        )
      })
    })
  })

  describe('when switching from Device Auth to PIN (isChangingExistingPIN = false)', () => {
    it('renders PINEntryForm without current PIN field', () => {
      const tree = render(
        <BasicAppContext>
          <BCSCLoadingProvider>
            <ChangePINContent
              onChangePINSuccess={onChangePINSuccess}
              onCreatePINSuccess={onCreatePINSuccess}
              isChangingExistingPIN={false}
            />
          </BCSCLoadingProvider>
        </BasicAppContext>
      )

      // Should not have current PIN field
      expect(tree.queryByText('BCSC.ChangePIN.EnterCurrentPIN')).toBeNull()
      // Should have create/confirm PIN fields
      expect(tree.getByText('BCSC.PIN.CreatePIN')).toBeTruthy()
      expect(tree.getByText('BCSC.PIN.ConfirmPIN')).toBeTruthy()
      expect(tree).toMatchSnapshot()
    })

    it('shows continue button instead of change PIN button', () => {
      const tree = render(
        <BasicAppContext>
          <BCSCLoadingProvider>
            <ChangePINContent
              onChangePINSuccess={onChangePINSuccess}
              onCreatePINSuccess={onCreatePINSuccess}
              isChangingExistingPIN={false}
            />
          </BCSCLoadingProvider>
        </BasicAppContext>
      )

      expect(tree.getByText('Global.Continue')).toBeTruthy()
    })

    it('sets security method and shows toast on successful PIN creation', async () => {
      mockSetPIN.mockResolvedValue({
        success: true,
        walletKey: 'new-key',
        isAutoGenerated: false,
      })
      mockCanPerformDeviceAuthentication.mockResolvedValue(true)
      mockSetAccountSecurityMethod.mockResolvedValue(true)

      const tree = render(
        <BasicAppContext>
          <BCSCLoadingProvider>
            <ChangePINContent
              onChangePINSuccess={onChangePINSuccess}
              onCreatePINSuccess={onCreatePINSuccess}
              isChangingExistingPIN={false}
            />
          </BCSCLoadingProvider>
        </BasicAppContext>
      )

      // Fill in PIN fields
      const inputs = tree.getAllByAccessibilityHint('Enter your 6-digit PIN')
      fireEvent.changeText(inputs[0], '123456') // Create
      fireEvent.changeText(inputs[1], '123456') // Confirm

      // Check the checkbox
      const checkbox = tree.getByTestId('com.ariesbifold:id/IUnderstand')
      fireEvent.press(checkbox)

      // Press continue button
      const button = tree.getByTestId('com.ariesbifold:id/Continue')
      fireEvent.press(button)

      await waitFor(() => {
        expect(mockSetPIN).toHaveBeenCalledWith('123456')
        expect(mockCanPerformDeviceAuthentication).toHaveBeenCalled()
        expect(mockSetAccountSecurityMethod).toHaveBeenCalledWith('app_pin_has_device_authn')
        expect(onCreatePINSuccess).toHaveBeenCalled()
        expect(mockToastShow).toHaveBeenCalledWith(
          expect.objectContaining({
            type: 'success',
            text1: 'BCSC.Settings.AppSecurity.SuccessTitle',
            text2: 'BCSC.Settings.AppSecurity.SwitchedToPIN',
          })
        )
      })
    })

    it('uses PinNoDeviceAuth when device auth is not available', async () => {
      mockSetPIN.mockResolvedValue({
        success: true,
        walletKey: 'new-key',
        isAutoGenerated: false,
      })
      mockCanPerformDeviceAuthentication.mockResolvedValue(false)
      mockSetAccountSecurityMethod.mockResolvedValue(true)

      const tree = render(
        <BasicAppContext>
          <BCSCLoadingProvider>
            <ChangePINContent
              onChangePINSuccess={onChangePINSuccess}
              onCreatePINSuccess={onCreatePINSuccess}
              isChangingExistingPIN={false}
            />
          </BCSCLoadingProvider>
        </BasicAppContext>
      )

      // Fill in PIN fields
      const inputs = tree.getAllByAccessibilityHint('Enter your 6-digit PIN')
      fireEvent.changeText(inputs[0], '123456')
      fireEvent.changeText(inputs[1], '123456')

      // Check the checkbox
      const checkbox = tree.getByTestId('com.ariesbifold:id/IUnderstand')
      fireEvent.press(checkbox)

      // Press continue button
      const button = tree.getByTestId('com.ariesbifold:id/Continue')
      fireEvent.press(button)

      await waitFor(() => {
        expect(mockSetAccountSecurityMethod).toHaveBeenCalledWith('app_pin_no_device_authn')
      })
    })
  })
})
