package com.bcsccore.keypair.repos.key;

import android.os.Build;
import android.os.Build.VERSION;
import android.os.Build.VERSION_CODES;
import android.security.keystore.KeyGenParameterSpec;
import android.security.keystore.KeyProperties;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import com.bcsccore.keypair.core.utils.SimpleLog;
import com.bcsccore.keypair.core.exceptions.AlertKey;
import com.bcsccore.keypair.core.models.BcscKeyPair;
import com.bcsccore.keypair.core.exceptions.BcscException;
import com.bcsccore.keypair.core.exceptions.KeyAlreadyExistsException;
import com.bcsccore.keypair.core.exceptions.KeyNotFoundException;
import com.bcsccore.keypair.core.exceptions.KeypairGenerationException;
import com.bcsccore.keypair.core.models.KeyPairInfo;
import com.bcsccore.keypair.core.interfaces.KeyPairInfoSource;
import com.bcsccore.keypair.core.interfaces.BcscKeyPairSource;
import com.nimbusds.jose.JWSAlgorithm;
import com.nimbusds.jose.JWSHeader;
import com.nimbusds.jose.crypto.RSASSASigner;
import com.nimbusds.jose.jwk.JWK;
import com.nimbusds.jose.jwk.RSAKey;
import com.nimbusds.jwt.JWTClaimsSet;
import com.nimbusds.jwt.SignedJWT;
import java.security.InvalidAlgorithmParameterException;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.KeyStore;
import java.security.KeyStoreException;
import java.security.NoSuchAlgorithmException;
import java.security.NoSuchProviderException;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.UnrecoverableEntryException;
import java.security.interfaces.RSAPublicKey;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Android KeyStore implementation of BcscKeyPairSource.
 * 
 * This class manages RSA key pairs stored in Android's hardware-backed KeyStore.
 * Key features:
 * - Generates 4096-bit RSA keys with RS512 signing
 * - Hardware security module backing when available
 * - Automatic key rotation and cleanup
 * - JWT signing with private keys
 * 
 * IMPORTANT: Keys generated by this class are:
 * - Tied to the specific app installation
 * - Bound to the app's signing certificate
 * - Cannot be exported or shared between apps
 */
public class BcscKeyPairRepo implements BcscKeyPairSource {

  private static final String RSA_ALIAS_PREFIX = "rsa";
  private static final String ALIAS_RSA = RSA_ALIAS_PREFIX + "1";
  private static final String KEYSTORE_TYPE = "AndroidKeyStore";
  private static final String TAG = "BcscKeyPairRepo";
  private static final Pattern RSA_ALIAS_PATTERN = Pattern.compile("^" + RSA_ALIAS_PREFIX + "(\\d+)$");

  @NonNull
  private final KeyPairInfoSource keyPairInfoSource;

  /**
   * Create a new BcscKeyPairRepo.
   * @param keyPairInfoSource the source for storing key pair metadata
   */
  public BcscKeyPairRepo(@NonNull KeyPairInfoSource keyPairInfoSource) {
    this.keyPairInfoSource = keyPairInfoSource;
  }

  @Override
  public boolean isAvailable() {
    try {
      loadAndroidKeyStore();
      return true;
    } catch (Exception e) {
      return false;
    }
  }

  @NonNull
  public BcscKeyPair getCurrentBcscKeyPair() throws BcscException {
    try {
      KeyStore keyStore = loadAndroidKeyStore();

      // Log full keystore contents on entry so we can diagnose both the
      // v3→older-v4→this-v4 path and the direct v3→this-v4 path.
      // Non-rsa\d+ aliases here indicate v3 keys that reconcile will ignore.
      try {
        java.util.List<String> allAliases = new java.util.ArrayList<>();
        Enumeration<String> en = keyStore.aliases();
        while (en.hasMoreElements()) allAliases.add(en.nextElement());
        SimpleLog.d(TAG, "getCurrentBcscKeyPair: keystore aliases=" + allAliases);
      } catch (KeyStoreException kse) {
        SimpleLog.d(TAG, "getCurrentBcscKeyPair: could not list keystore aliases: " + kse.getMessage());
      }
      SimpleLog.d(TAG, "getCurrentBcscKeyPair: rsa keystore aliases="
          + findRsaAliasesInKeyStore(keyStore).values());

      // Reconcile metadata with the keystore before picking the active key.
      // Required for v3 -> v4 migrated users whose v4 SharedPreferences was
      // initialized with a stale rsa1 entry by an earlier code path, while
      // the AndroidKeyStore (preserved across the in-place upgrade) still
      // holds higher-numbered rsa\d+ aliases that are the keys actually
      // registered with IAS.
      reconcileKeyPairInfoWithKeyStore(keyStore);

      HashMap<String, KeyPairInfo> allInfo = keyPairInfoSource.getKeyPairInfo();
      SimpleLog.d(TAG, "getCurrentBcscKeyPair: KeyPairInfo after reconcile=" + allInfo.keySet());

      KeyPairInfo info = getNewestKeyPairInfo(allInfo);

      if (info == null) {
        SimpleLog.d(TAG, "getCurrentBcscKeyPair: no KeyPairInfo found — seeding fresh " + ALIAS_RSA);
        info = new KeyPairInfo(ALIAS_RSA, System.currentTimeMillis());
        keyPairInfoSource.saveKeyPairInfo(info);
      } else {
        SimpleLog.d(TAG, "getCurrentBcscKeyPair: newest KeyPairInfo="
            + info.getAlias() + " createdAt=" + info.getCreatedAt());
      }

      boolean aliasPresent = keyStore.containsAlias(info.getAlias());
      SimpleLog.d(TAG, "getCurrentBcscKeyPair: alias '" + info.getAlias()
          + "' present in keystore=" + aliasPresent);
      if (!aliasPresent) {
        SimpleLog.d(TAG, "getCurrentBcscKeyPair: generating new key pair for alias " + info.getAlias());
        generateKeyPair(info.getAlias());
      }

      final KeyPair keyPair;
      try {
        keyPair = getKeyPair(keyStore, info.getAlias());
      } catch (Exception e) {
        throw new KeyNotFoundException(
            "Failed to retrieve key pair for alias '" + info.getAlias() + "': " + e.getMessage(), e);
      }
      SimpleLog.d(TAG, "getCurrentBcscKeyPair: returning active key pair " + info.getAlias());
      return new BcscKeyPair(keyPair, info);
    } catch (KeypairGenerationException e) {
      throw e;
    } catch (Exception e) {
      throw new KeypairGenerationException(e.getMessage(), e);
    }
  }

  @Nullable
  @Override
  public BcscKeyPair getBcscKeyPair(@NonNull String kid) throws BcscException {
    try {
      KeyStore keyStore = loadAndroidKeyStore();

      if (!keyStore.containsAlias(kid)) {
        return null;
      }

      KeyPairInfo info = keyPairInfoSource.getKeyPairInfo(kid);
      if (info == null) {
        info = new KeyPairInfo(kid, System.currentTimeMillis());
        keyPairInfoSource.saveKeyPairInfo(info);
      }

      final KeyPair keyPair = getKeyPair(keyStore, kid);
      return new BcscKeyPair(keyPair, info);
    } catch (Exception e) {
      return null;
    }
  }

  @NonNull
  @Override
  public BcscKeyPair getNewBcscKeyPair() throws BcscException {
    try {
      KeyStore keyStore = loadAndroidKeyStore();

      // Reconcile so rotation increments off the highest existing rsa\d+
      // alias rather than colliding with a leftover v3 keystore entry.
      reconcileKeyPairInfoWithKeyStore(keyStore);

      KeyPairInfo info = getNewestKeyPairInfo(keyPairInfoSource.getKeyPairInfo());

      if (info == null) {
        info = new KeyPairInfo(ALIAS_RSA, System.currentTimeMillis());
        keyPairInfoSource.saveKeyPairInfo(info);
      }

      int id = Integer.parseInt(info.getAlias().replaceAll("\\D+", ""));

      id += 1;

      final String alias = String.format(Locale.ROOT, "%s%d", RSA_ALIAS_PREFIX, id);

      final KeyPairInfo newInfo = new KeyPairInfo(alias, System.currentTimeMillis());
      keyPairInfoSource.saveKeyPairInfo(newInfo);

      generateKeyPair(alias);
      final KeyPair keyPair;
      try {
        keyPair = getKeyPair(keyStore, alias);
      } catch (Exception e) {
        throw new KeyNotFoundException(
            "Failed to retrieve newly generated key pair for alias '" + alias + "': " + e.getMessage(), e);
      }
      SimpleLog.d(TAG, "Generated new key pair " + alias);
      return new BcscKeyPair(keyPair, newInfo);
    } catch (KeypairGenerationException e) {
      throw e;
    } catch (Exception e) {
      throw new KeypairGenerationException(e.getMessage(), e);
    }
  }

  @Override
  public void deleteBcscKeyPair(@NonNull String alias) throws BcscException {
    SimpleLog.d(TAG, "Deleting key pair " + alias);
    keyPairInfoSource.deleteKeyPairInfo(alias);
    boolean success = deleteKeyEntry(alias);
    if (!success) {
      throw new BcscException(AlertKey.ERR_108_UNABLE_TO_DELETE_KEY_PAIR);
    }
  }

  @Override
  public void cleanUpBcscKeyPairs() throws BcscException {
    KeyPairInfo info = getOldestKeyPairInfo(keyPairInfoSource.getKeyPairInfo());

    if (info == null) {
      return;
    }
    SimpleLog.d(TAG, "Cleaning up key pair " + info.getAlias());
    keyPairInfoSource.deleteKeyPairInfo(info.getAlias());
    boolean success = deleteKeyEntry(info.getAlias());
    if (!success) {
      throw new BcscException(AlertKey.ERR_108_UNABLE_TO_DELETE_KEY_PAIR);
    }
  }

  @Nullable
  private KeyPairInfo getNewestKeyPairInfo(HashMap<String, KeyPairInfo> infoMap) {
    KeyPairInfo info = null;
    for (KeyPairInfo keyPairInfo : infoMap.values()) {
      if (info == null) {
        info = keyPairInfo;
      } else {
        if (keyPairInfo.getCreatedAt() > info.getCreatedAt()) {
          info = keyPairInfo;
        }
      }
    }
    return info;
  }

  @Nullable
  private KeyPairInfo getOldestKeyPairInfo(HashMap<String, KeyPairInfo> infoMap) {

    if (infoMap.size() < 3) {
      return null;
    }

    String alias = null;
    long currentOldKeyTime = System.currentTimeMillis();
    for (KeyPairInfo keyPairInfo : infoMap.values()) {
      if (keyPairInfo.getCreatedAt() < currentOldKeyTime) {
        currentOldKeyTime = keyPairInfo.getCreatedAt();
        alias = keyPairInfo.getAlias();
      }
    }
    return infoMap.get(alias);
  }

  @NonNull
  private KeyStore loadAndroidKeyStore() throws Exception {
    KeyStore keyStore = KeyStore.getInstance(KEYSTORE_TYPE);
    keyStore.load(null);
    return keyStore;
  }

  /**
   * Conservative bootstrap for KeyPairInfo metadata when nothing is tracked yet.
   *
   * Source of truth for "which kid is active" is the server (validated via
   * GET /device/register/{client_id} and the recovery flow in the app layer).
   * This method exists only to bootstrap metadata when we have no other
   * information at all: e.g. a v3 user upgraded in place, keystore preserved,
   * but SharedPreferences empty.
   *
   * Behaviour:
   *   - If metadata already has any entry, this is a no-op. We trust metadata;
   *     orphaned keystore aliases (e.g. left over from a v3 account reset) are
   *     intentionally NOT promoted to "newest" here. The recovery flow will
   *     prune them once the server confirms which kid is real.
   *   - If metadata is empty AND keystore has rsa\d+ aliases, backfill them
   *     with synthetic createdAt values so the highest-numbered alias becomes
   *     newest. This is a last-resort guess (numeric ordering is wrong after
   *     a v3 account reset that restarts at rsa1); the recovery flow corrects
   *     it on the first 401.
   */
  private void reconcileKeyPairInfoWithKeyStore(@NonNull KeyStore keyStore) throws BcscException {
    HashMap<String, KeyPairInfo> existing = keyPairInfoSource.getKeyPairInfo();
    if (!existing.isEmpty()) {
      SimpleLog.d(TAG, "reconcile: metadata non-empty; trusting existing entries (" + existing.keySet() + ")");
      return;
    }

    java.util.TreeMap<Integer, String> keystoreAliases = findRsaAliasesInKeyStore(keyStore);
    if (keystoreAliases.isEmpty()) {
      SimpleLog.d(TAG, "reconcile: metadata empty and no rsa\\d+ aliases in keystore; nothing to do");
      return;
    }

    long now = System.currentTimeMillis();
    int highestId = keystoreAliases.lastKey();
    for (java.util.Map.Entry<Integer, String> entry : keystoreAliases.entrySet()) {
      long createdAt = now - (long) (highestId - entry.getKey());
      keyPairInfoSource.saveKeyPairInfo(new KeyPairInfo(entry.getValue(), createdAt));
    }
    SimpleLog.d(TAG, "reconcile: bootstrapped empty metadata from keystore aliases "
        + keystoreAliases.values() + " (synthetic timestamps; will be corrected on first 401 recovery)");
  }

  /**
   * Enumerate every rsa\d+ alias that exists in the AndroidKeyStore, augmented
   * with the createdAt from metadata when present. This is the source of truth
   * for "what private keys does this device actually hold" — used by the
   * recovery flow to match local keys against the server's jwks.
   *
   * @return list of KeyPairInfo, one per keystore alias matching rsa\d+. The
   *         createdAt is 0 for aliases not yet tracked in metadata. Empty list
   *         (never null) if the keystore can't be read.
   */
  @NonNull
  @Override
  public List<KeyPairInfo> getAllBcscKeyPairInfos() throws BcscException {
    try {
      KeyStore keyStore = loadAndroidKeyStore();
      java.util.TreeMap<Integer, String> keystoreAliases = findRsaAliasesInKeyStore(keyStore);
      HashMap<String, KeyPairInfo> metadata = keyPairInfoSource.getKeyPairInfo();
      List<KeyPairInfo> result = new ArrayList<>(keystoreAliases.size());
      for (String alias : keystoreAliases.values()) {
        KeyPairInfo tracked = metadata.get(alias);
        result.add(tracked != null ? tracked : new KeyPairInfo(alias, 0L));
      }
      return result;
    } catch (BcscException e) {
      throw e;
    } catch (Exception e) {
      throw new BcscException("Failed to enumerate keystore aliases: " + e.getMessage());
    }
  }

  /**
   * Mark the given alias as the active (newest) key in metadata. Called by
   * the recovery flow after the server confirms which kid it accepts.
   *
   * Updates createdAt = now so getNewestKeyPairInfo returns this alias on
   * subsequent calls. If the alias has no metadata entry yet (e.g. it was a
   * keystore-only orphan before recovery), an entry is created.
   */
  @Override
  public void markActiveBcscKeyPair(@NonNull String alias) throws BcscException {
    keyPairInfoSource.saveKeyPairInfo(new KeyPairInfo(alias, System.currentTimeMillis()));
    SimpleLog.d(TAG, "markActiveBcscKeyPair: " + alias + " stamped as newest");
  }

  /**
   * Return every keystore alias that looks like rsa\d+, keyed by its number
   * so iteration is in numeric order. Returns an empty map (never null) if
   * the keystore can't be read.
   */
  @NonNull
  private java.util.TreeMap<Integer, String> findRsaAliasesInKeyStore(@NonNull KeyStore keyStore) {
    java.util.TreeMap<Integer, String> result = new java.util.TreeMap<>();
    try {
      Enumeration<String> aliases = keyStore.aliases();
      while (aliases.hasMoreElements()) {
        String alias = aliases.nextElement();
        Matcher m = RSA_ALIAS_PATTERN.matcher(alias);
        if (m.matches()) {
          result.put(Integer.parseInt(m.group(1)), alias);
        }
      }
    } catch (KeyStoreException e) {
      SimpleLog.e(TAG, "Failed to enumerate keystore aliases for reconciliation", e);
    }
    return result;
  }

  /**
   * Generate a new RSA key pair in Android KeyStore.
   * Creates a 4096-bit RSA key with SHA-512 digest for signing.
   * 
   * @param alias the alias to store the key pair under
   * @throws KeypairGenerationException if key generation fails
   */
  private void generateKeyPair(String alias) throws KeypairGenerationException {
    try {
      KeyStore keyStore = loadAndroidKeyStore();
      if (keyStore.containsAlias(alias)) {
        throw new KeyAlreadyExistsException(
            "Key pair already exists for alias '" + alias + "'");
      }

      final KeyGenParameterSpec.Builder builder = new KeyGenParameterSpec.Builder(
          alias,
          KeyProperties.PURPOSE_SIGN
              | KeyProperties.PURPOSE_VERIFY
              | KeyProperties.PURPOSE_ENCRYPT
              | KeyProperties.PURPOSE_DECRYPT
      );

      builder.setDigests(KeyProperties.DIGEST_SHA512)
          .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_RSA_PKCS1)
          .setKeySize(4096)
          .setSignaturePaddings(KeyProperties.SIGNATURE_PADDING_RSA_PKCS1);

      if (VERSION.SDK_INT >= VERSION_CODES.N) {
        builder.setInvalidatedByBiometricEnrollment(false);
      }

      final KeyGenParameterSpec spec = builder.build();

      final KeyPairGenerator gen = KeyPairGenerator.getInstance(
          KeyProperties.KEY_ALGORITHM_RSA, "AndroidKeyStore");
      gen.initialize(spec);
      gen.generateKeyPair();
    } catch (KeyAlreadyExistsException e) {
      throw e;
    } catch (InvalidAlgorithmParameterException
        | NoSuchAlgorithmException
        | NoSuchProviderException e) {
      SimpleLog.e(TAG, "Failed to generate key pair", e);
      throw new KeypairGenerationException("Failed to generate key pair for alias '" + alias + "': " + e.getMessage(), e);
    } catch (Exception e) {
      SimpleLog.e(TAG, "Failed to generate key pair", e);
      throw new KeypairGenerationException("Failed to generate key pair for alias '" + alias + "': " + e.getMessage(), e);
    }
  }

  private boolean deleteKeyEntry(String alias) {
    try {
      KeyStore keyStore = loadAndroidKeyStore();
      keyStore.deleteEntry(alias);
      return true;
    } catch (Exception e) {
      return false;
    }
  }

  @NonNull
  @Override
  public JWK convertBcscKeyPairToJWK(@NonNull BcscKeyPair bcscKeyPair) {
    return new RSAKey.Builder((RSAPublicKey) bcscKeyPair.getKeyPair().getPublic())
        .keyID(bcscKeyPair.getKeyInfo().getAlias())
        .build();
  }

  @Override
  @NonNull
  public String signAndSerializeClaimsSet(@NonNull JWTClaimsSet claimsSet) throws BcscException {
    try {
      SignedJWT signedJWT = signClaimsSet(claimsSet);
      return signedJWT.serialize();
    } catch (Exception e) {
      throw new BcscException(AlertKey.ERR_207_UNABLE_TO_SIGN_CLAIMS_SET, e.getMessage());
    }
  }

  /**
   * This is the core signing method where attestation signing happens.
   * 
   * Signs a JWT claims set using the current key pair's private key.
   * Uses RS512 algorithm (RSA signature with SHA-512 hash).
   * 
   * @param claimsSet the JWT claims to sign
   * @return the signed JWT
   * @throws BcscException if signing fails
   */
  @Override
  @NonNull
  public SignedJWT signClaimsSet(@NonNull JWTClaimsSet claimsSet) throws BcscException {
    try {
      BcscKeyPair currentKeyPair = getCurrentBcscKeyPair();
      JWSHeader header = new JWSHeader.Builder(JWSAlgorithm.RS512)
          .keyID(currentKeyPair.getKeyInfo().getAlias())
          .build();
      SignedJWT signedJWT = new SignedJWT(header, claimsSet);
      signedJWT.sign(new RSASSASigner(currentKeyPair.getKeyPair().getPrivate()));
      return signedJWT;
    } catch (Exception e) {
      throw new BcscException(AlertKey.ERR_207_UNABLE_TO_SIGN_CLAIMS_SET, e.getMessage());
    }
  }

  @NonNull
  private KeyPair getKeyPair(@NonNull KeyStore keyStore, @NonNull String kid)
      throws UnrecoverableEntryException, NoSuchAlgorithmException, KeyStoreException {
    if (Build.VERSION.SDK_INT <= VERSION_CODES.O_MR1) {
      final PrivateKey privateKey = (PrivateKey) keyStore.getKey(kid, null);
      final PublicKey publicKey = keyStore.getCertificate(kid).getPublicKey();
      return new KeyPair(publicKey, privateKey);
    } else {
      final KeyStore.PrivateKeyEntry privateKeyEntry =
          (KeyStore.PrivateKeyEntry) keyStore.getEntry(kid, null);
      return new KeyPair(
          privateKeyEntry.getCertificate().getPublicKey(),
          privateKeyEntry.getPrivateKey()
      );
    }
  }

}
