name: Export Signed iOS Archive
description: Export a signed iOS Archive

inputs:
  certificate:
    description: |
      The Base64 encoded certificate to use for 
      signing the archive. This should be in p12 format.
    required: true
  certificate_password:
    description: |
      The password for importing the certificate.
    required: true
  app_store_connect_private_key:
    description: |
      The private key for the App Store Connect API.
    required: true

runs:
  using: composite
  steps:
    - name: Build Keychain
      shell: bash
      env:
        CERTIFICATE: ${{ inputs.certificate }}
      run: |
        scripts/makekc.sh ${{ inputs.certificate_password }}

    - name: Build API AuthKey
      shell: bash
      env:
        AUTHKEY_P8: ${{ inputs.app_store_connect_private_key }}
      run: |
        scripts/makeauthkey.sh
