name: Export Signed iOS Archive
description: Export a signed iOS Archive

inputs:
  certificate:
    description: |
      The Base64 encoded certificate to use for 
      signing the archive. This should be in p12 format.
    required: true
  certificate_password:
    description: |
      The password for importing the certificate.
    requred: true
  provisioning_profile:
    description: |
      The Base64 encoded provisioning profile to use for 
      signing the archive. This should be in mobileprovision format.
    requred: true

runs:
  using: composite
  steps:
    - name: Build Keychain
      shell: bash
      env:
        CERTIFICATE: ${{ inputs.certificate }}
      run: |
        scripts/makekc.sh ${{ inputs.certificate_password }}

      # https://docs.github.com/en/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development
    - name: Create Provisioning Profile
      shell: bash
      env:
        PROVISIONING_PROFILE: ${{ inputs.provisioning_profile }}
      run: |
        scripts/makepp.sh
