// prettier-ignore
const translation = {
  "BCID": {
    "GetID": "Get BCID (PT-BR)",
    "GetDigitalID": "Get your Person credential (PT-BR)",
  },
  "Error": {
    "Title2020": "Unable to parse invitation (PT-BR)",
    "Message2020": "There was a problem parsing the connection invitation. (PT-BR)",
    "Title2021": "Unable to receive invitation (PT-BR)",
    "Message2021": "There was a problem receiving the invitation to connect. (PT-BR)",
    "Title2022": "Unable to find legacy DID (PT-BR)",
    "Message2022": "There was a problem extracting the did repository. (PT-BR)",
    "Title2025": "BCSC Authentication (PT-BR)",
    "Message2025": "There was a problem reported by BCSC. (PT-BR)",
    "Title2026": "Oops! Something went wrong (PT-BR)",
    "Message2026": "The app has encountered a problem. Try restarting the app. (PT-BR)",
    "NoMessage": "No Message (PT-BR)",
  },
  "CameraDisclosure": {
    "AllowCameraUse": "Allow camera use (PT-BR)",
    "CameraDisclosure": "A câmera é usada para escanear QR Codes para processamento imediato no dispositivo. Nenhuma informação sobre as imagens é armazenada, usada para análise, ou compartilhada.",
    "ToContinueUsing": "To continue using the BC Wallet scan feature, please allow camera permissions. (PT-BR)",
    "Allow": "Allow (PT-BR)",
    "OpenSettings": "Open settings (PT-BR)",
  },
  "Biometry": {
    "Toggle": "Toggle Biometrics (PT-BR)",
    "EnabledText1": "Log in with your phone's biometrics instead of your wallet PIN. (PT-BR)",
    "EnabledText1Bold": "you will need to use biometrics to open your QC Wallet. (PT-BR)",
    "EnabledText2": "This means all fingerprint and facial data added on this phone can be used to access your QC Wallet. (PT-BR)",
    "EnabledText3": "Anyone who can access your phone with biometrics can access your QC Wallet. (PT-BR)",
    "EnabledText3Bold": "Ensure only you have access to your wallet. (PT-BR)",
    "Warning": "Ensure only you have access to your wallet. (PT-BR)",
    "UseToUnlock": "Use biometrics to unlock wallet? (PT-BR)",
  },
  "Credentials": {
    "AddCredential": "Add Credential (PT-BR)",
    "EmptyList": "Your wallet is empty. (PT-BR)",
    "AddFirstCredential": "Add your first credential (PT-BR)"
  },
  "Onboarding": {
    "Welcome": "Welcome (PT-BR)",
    "WelcomeParagraph1": "BC Wallet lets you receive, store and use digital credentials. (PT-BR)",
    "WelcomeParagraph2": "It is highly secure, and helps protect your privacy online. (PT-BR)",
    "WelcomeParagraph3": "BC Wallet is currently in its early stages and the technology is being explored. Most people will not have a use for BC Wallet yet, because very few digital credentials are available. (PT-BR)",
    "StoredSecurelyTitle": "Digital credentials, stored securely (PT-BR)",
    "StoredSecurelyBody": "BC Wallet holds digital credentials—the digital versions of things like licenses, identities and permits.\n\nThey are stored securely, only on this device. (PT-BR)",
    "UsingCredentialsTitle": "Receiving and using credentials (PT-BR)",
    "UsingCredentialsBody": "To receive and use credentials you use the “Scan” feature in the app to scan a special QR code.\n\nInformation is sent and received over a private, encrypted connection. (PT-BR)",
    "PrivacyConfidentiality": "Privacy and confidentiality (PT-BR)",
    "PrivacyParagraph": "You approve every use of information from your BC Wallet. You also only share what is needed for a situation.\n\nThe Government of British Columbia is not told when you use your digital credentials. (PT-BR)",
    "GetStarted": "Get Started (PT-BR)",
    "SkipA11y": "Skip introduction to BC Wallet (PT-BR)",
  },
  "Screens": {
    "Onboarding": "QC Wallet (PT-BR)",
    "Settings": "Menu (PT-BR)",
  },
  "PersonCredentialNotification": {
    "Title": "Get your Person credential (PT-BR)",
    "Description": "Add your Person credential to your wallet and use it to get access to services online. (PT-BR)"
  },
  "PersonCredential": {
    "Issuer": "Service BC (PT-BR)",
    "Name": "Person (PT-BR)",
    "GivenName": "Sample Given Name (PT-BR)",
    "FamilyName": "Sample Family Name (PT-BR)",
    "Description": "Add your Person credential to your wallet to prove your personal information online and get access to services online.\n\nYou'll need the BC Service Card app set up on this mobile device. (PT-BR)",
    "LinkDescription": "Get the BC Services Card app (PT-BR)",
    "GetCredential": "Get your Person credential (PT-BR)",
    "Decline": "Get this later (PT-BR)",
    "PageTitle": "Person Credential (PT-BR)",
    "Onboarding": "QC Wallet (PT-BR)",
  },
  "NetInfo": {
    "NoInternetConnectionTitle": "No internet connection (PT-BR)",
    "NoInternetConnectionMessage": "You're unable to access services using BC Wallet or receive credentials until you're back online.\n\nPlease check your internet connection. (PT-BR)",
  },
  "Tour": {
    "GuideTitle": "Welcome to BC Wallet (PT-BR)",
    "WouldYouLike": "Would you like some guidance on how to use BC Wallet? (PT-BR)",
    "UseAppGuides": "Use app guides (PT-BR)",
    "DoNotUseAppGuides": "Don't use app guides (PT-BR)",
    "AddAndShare": "Add and share credentials (PT-BR)",
    "AddAndShareDescription": "To add and use credentials you scan a QR code displayed by the service provider. (PT-BR)",
    "Notifications": "Notifications (PT-BR)",
    "NotificationsDescription": "After you scan a QR code, the credential offer or proof request will appear here, as well as other notable events. (PT-BR)",
    "YourCredentials": "Your credentials (PT-BR)",
    "YourCredentialsDescription": "Your added digital credentials appear here. You can review credential details and add and delete credentials. (PT-BR)",
    "Skip": "Skip (PT-BR)",
    "Next": "Next (PT-BR)",
    "Back": "Back (PT-BR)",
    "Done": "Done (PT-BR)",
  },
  "Settings": {
    "Help": "Help (PT-BR)",
    "MoreInformation": "More Information (PT-BR)",
    "HelpUsingBCWallet": "Help using BC Wallet (PT-BR)",
    "GiveFeedback": "Give feedback (PT-BR)",
    "ReportAProblem": "Report a problem (PT-BR)",
    "TermsOfUse": "Terms of use (PT-BR)",
    "PrivacyStatement": "Privacy statement (PT-BR)",
    "VulnerabilityDisclosurePolicy": "Vulnerability disclosure policy (PT-BR)",
    "Accessibility": "Accessibility (PT-BR)",
    "IntroductionToTheApp": "Introduction to the app (PT-BR)",
  },
  "Developer": {
    "Environment": "Environment (PT-BR)",
    "Production": "Production (PT-BR)",
    "Development": "Development (PT-BR)",
    "Test": "Test (PT-BR)",
    "DeveloperMode": "Developer mode",
    "Toggle": "Toggle Developer Mode"
  },
  "Tips": {
    "Header": "Tips (PT-BR)",
    "GettingReady": "Getting your wallet ready... (PT-BR)",
    "Tip1": "For extra security, BC Wallet locks the app after 5 minutes of inactivity (PT-BR)",
    "Tip2": "Unlike showing physical cards, you share only what is necessary from your credentials (PT-BR)",
    "Tip3": "Your credentials are stored only on this phone, nowhere else (PT-BR)",
    "Tip4": "Information is sent and received over an untraceable encrypted connection (PT-BR)",
    "Tip5": "Remember your PIN. If you forget it, you'll need to reinstall and re-add your credentials (PT-BR)",
    "Tip6": "Skip the PIN and unlock your wallet using your biometrics for a faster experience (PT-BR)",
    "Tip7": "Your most recently added credentials are placed at the top (PT-BR)",
    "Tip8": "Remove credentials in your wallet from the credential details screen (PT-BR)",
    "Tip9": "You can dismiss notifications without opening them by tapping “X” in the top right corner (PT-BR)",
    "Tip10": "Need help? Find answers in the help section within the “☰” button on the top left corner (PT-BR)",
    "Tip11": "You can turn on the camera flash if the QR code is hard to see (PT-BR)",
    "Tip12": "If the QR code isn't scanning, try increasing the screen's brightness (PT-BR)",
    "Tip13": "Information sent via your wallet is trusted by you and your Contacts you interact with (PT-BR)",
    "Tip14": "Even revoked or expired credentials can be usable if the organisation doesn't request for it (PT-BR)",
  },
  "Init": {
    "Retry": "Retry (PT-BR)",
    "Starting": "Starting... (PT-BR)",
    "CheckingAuth": "Checking authentication... (PT-BR)",
    "FetchingPreferences": "Fetching preferences... (PT-BR)",
    "VerifyingOnboarding": "Verifying onboarding... (PT-BR)",
    "GettingCredentials": "Getting wallet credentials... (PT-BR)",
    "RegisteringTransports": "Registering transports... (PT-BR)",
    "InitializingAgent": "Initializing agent... (PT-BR)",
    "ConnectingLedgers": "Connecting to ledgers... (PT-BR)",
    "SettingAgent": "Setting agent... (PT-BR)",
    "Finishing": "Finishing... (PT-BR)",
  },
  "Feedback": {
    "GiveFeedback": "Give Feedback (PT-BR)",
  }
}

export default translation
