// prettier-ignore
const translation = {
  "BCID": {
    "GetID": "Get BCID (PT-BR)",
    "GetDigitalID": "Get your Person credential (PT-BR)",
  },
  "Error": {
    "Title2020": "Unable to parse invitation (PT-BR)",
    "Message2020": "There was a problem parsing the connection invitation. (PT-BR)",
    "Title2021": "Unable to receive invitation (PT-BR)",
    "Message2021": "There was a problem receiving the invitation to connect. (PT-BR)",
    "Title2022": "Unable to find legacy DID (PT-BR)",
    "Message2022": "There was a problem extracting the did repository. (PT-BR)",
    "Title2025": "BCSC Authentication (PT-BR)",
    "Message2025": "There was a problem reported by BCSC. (PT-BR)",
    "Title2026": "Oops! Something went wrong (PT-BR)",
    "Message2026": "The app has encountered a problem. Try restarting the app. (PT-BR)",
    "Title2027": "Unable to parse invitation (PT-BR)",
    "Message2027": "There was a problem parsing the attestation connection invitation. (PT-BR)",
    "Title2028": "Unable to receive invitation (PT-BR)",
    "Message2028": "There was a problem receiving the attestation invitation to connect. (PT-BR)",
    "Title2029": "Unable to handle attestation proof (PT-BR)",
    "Message2029": "There was a problem while handling an attestation proof request. (PT-BR)",
    "NoMessage": "No Message (PT-BR)",
  },
  "CameraDisclosure": {
    "AllowCameraUse": "Allow camera use (PT-BR)",
    "CameraDisclosure": "A câmera é usada para escanear QR Codes para processamento imediato no dispositivo. Nenhuma informação sobre as imagens é armazenada, usada para análise, ou compartilhada.",
    "ToContinueUsing": "To continue using the BC Wallet scan feature, please allow camera permissions. (PT-BR)",
    "Allow": "Allow (PT-BR)",
    "OpenSettings": "Open settings (PT-BR)",
  },
  "Biometry": {
    "Toggle": "Toggle Biometrics (PT-BR)",
    "EnabledText1": "Log in with your phone's biometrics instead of your wallet PIN. (PT-BR)",
    "EnabledText1Bold": "you will need to use biometrics to open your BC Wallet. (PT-BR)",
    "EnabledText2": "This means all fingerprint and facial data added on this phone can be used to access your BC Wallet. (PT-BR)",
    "EnabledText3": "Anyone who can access your phone with biometrics can access your BC Wallet. (PT-BR)",
    "EnabledText3Bold": "Ensure only you have access to your wallet. (PT-BR)",
    "Warning": "Ensure only you have access to your wallet. (PT-BR)",
    "UseToUnlock": "Use biometrics to unlock wallet? (PT-BR)",
  },
  "Credentials": {
    "AddCredential": "Add Credential (PT-BR)",
    "EmptyList": "Your wallet is empty. (PT-BR)",
    "AddFirstCredential": "Add your first credential (PT-BR)"
  },
  "Onboarding": {
    "DifferentWalletHeading": "A different smart wallet (PT-BR)",
    "DifferentWalletParagraph": "Unlike other digital wallets, BC Wallet helps you prove who you are in-person or online by storing and using digital credentials issued by participating services.\n\nInteract with confidence with individuals and organisations you trust. (PT-BR)",
    "DigitalCredentialsHeading": "Digital credentials (PT-BR)",
    "DigitalCredentialsParagraph": "Digital credentials are the electronic equivalent of physical credentials such as certifications and permits offered by participating services.\n\nServices are simplified and expedited as organisations and individuals can confirm who you are with trusted information from digital credentials. (PT-BR)",
    "PrivateConfidentialHeading": "Private and confidential (PT-BR)",
    "PrivateConfidentialParagraph": "Your privacy is important.\n\nThe B.C. government doesn't know when you use digital credentials, unless you're interacting with them. No analytics are recorded.\n\nYou approve every use of your digital credentials, and only provide the information that’s needed. (PT-BR)",
    "GetStarted": "Get Started (PT-BR)",
  },
  "Preface": {
    "Paragraph1": "Most people will not have a need for BC Wallet because very few digital credentials are currently available. (PT-BR)",
    "Link1": "See where you can use BC Wallet (PT-BR)",
    "Paragraph2": "If BC Wallet isn't what you're looking for but you're curious, check out our (PT-BR)",
    "Link2": "BC Wallet showcase (PT-BR)",
  },
  "Screens": {
    "Onboarding": "BC Wallet (PT-BR)",
    "Terms": "Terms of Use (PT-BR)",
    "Settings": "Menu (PT-BR)",
    "Preface": "BC Wallet",
  },
  "PersonCredentialNotification": {
    "Title": "Get your Person credential (PT-BR)",
    "Description": "Add your Person credential to your wallet and use it to get access to services online. (PT-BR)"
  },
  "PersonCredential": {
    "ServicesCardInstalled": "Step 1: BC Services Card app installed (PT-BR)",
    "InstallServicesCard": "Step 1: Install the BC Services Card app (FR",
    "InstallApp": "Install the app (PT-BR)",
    "AppOnOtherDevice": "I have it on another device (PT-BR)",
    "CreatePersonCred": "Step 2: Create your Person credential (PT-BR)",
    "StartProcess": "Start the process (PT-BR)",
    "PageTitle": "Person Credential (PT-BR)"
  },
  "NetInfo": {
    "NoInternetConnectionTitle": "No internet connection (PT-BR)",
    "NoInternetConnectionMessage": "You're unable to access services using BC Wallet or receive credentials until you're back online.\n\nPlease check your internet connection. (PT-BR)",
  },
  "Tour": {
    "GuideTitle": "Welcome to BC Wallet (PT-BR)",
    "WouldYouLike": "Would you like some guidance on how to use BC Wallet? (PT-BR)",
    "UseAppGuides": "Use app guides (PT-BR)",
    "DoNotUseAppGuides": "Don't use app guides (PT-BR)",
    "AddAndShare": "Add and share credentials (PT-BR)",
    "AddAndShareDescription": "To add and use credentials you scan a QR code displayed by the service provider. (PT-BR)",
    "AddCredentials": "Add credentials (PT-BR)",
    "AddCredentialsDescription": "Add credentials by scanning a QR code displayed on the issuer service. (PT-BR)",
    "Notifications": "Notifications (PT-BR)",
    "NotificationsDescription": "After you scan a QR code, the credential offer or proof request will appear here, as well as other notable events. (PT-BR)",
    "YourCredentials": "Your credentials (PT-BR)",
    "YourCredentialsDescription": "Your added digital credentials appear here. You can review credential details and add and delete credentials. (PT-BR)",
    "CredentialOffers": "Credential offers (PT-BR)",
    "CredentialOffersDescription": "An organization has offered you a credential. Review the credentials details and choose to accept or decline it. Accepted credentials will be added to your wallet. (PT-BR)",
    "ProofRequests": "Proof requests (PT-BR)",
    "ProofRequestsDescription": "An organization is asking you to prove your credentials. Review what they're asking for and choose to accept or decline it. (PT-BR)",
    "Skip": "Skip (PT-BR)",
    "Next": "Next (PT-BR)",
    "Back": "Back (PT-BR)",
    "Done": "Done (PT-BR)",
  },
  "Settings": {
    "Help": "Help (PT-BR)",
    "MoreInformation": "More Information (PT-BR)",
    "PlayWithBCWallet": "Play with BC Wallet (PT-BR)",
    "HelpUsingBCWallet": "Help using BC Wallet (PT-BR)",
    "GiveFeedback": "Give feedback (PT-BR)",
    "ReportAProblem": "Report a problem (PT-BR)",
    "TermsOfUse": "Terms of use (PT-BR)",
    "PrivacyStatement": "Privacy statement (PT-BR)",
    "VulnerabilityDisclosurePolicy": "Vulnerability disclosure policy (PT-BR)",
    "Accessibility": "Accessibility (PT-BR)",
    "IntroductionToTheApp": "Introduction to the app (PT-BR)",
  },
  "Developer": {
    "Environment": "Environment (PT-BR)",
    "Production": "Production (PT-BR)",
    "Development": "Development (PT-BR)",
    "Test": "Test (PT-BR)",
    "DeveloperMode": "Developer mode",
    "Toggle": "Toggle Developer Mode",
    "AttestationSupport": "Attestation support (PT-BR)",
  },
  "Tips": {
    "Header": "Tips (PT-BR)",
    "GettingReady": "Getting your wallet ready... (PT-BR)",
    "Tip1": "For extra security, BC Wallet locks the app after 5 minutes of inactivity (PT-BR)",
    "Tip2": "Unlike showing physical cards, you share only what is necessary from your credentials (PT-BR)",
    "Tip3": "Your credentials are stored only on this phone, nowhere else (PT-BR)",
    "Tip4": "Information is sent and received over an untraceable encrypted connection (PT-BR)",
    "Tip5": "Remember your PIN. If you forget it, you'll need to reinstall and re-add your credentials (PT-BR)",
    "Tip6": "Skip the PIN and unlock your wallet using your biometrics for a faster experience (PT-BR)",
    "Tip7": "Your most recently added credentials are placed at the top (PT-BR)",
    "Tip8": "Remove credentials in your wallet from the credential details screen (PT-BR)",
    "Tip9": "You can dismiss notifications without opening them by tapping “X” in the top right corner (PT-BR)",
    "Tip10": "Need help? Find answers in the help section within the “☰” button on the top left corner (PT-BR)",
    "Tip11": "You can turn on the camera flash if the QR code is hard to see (PT-BR)",
    "Tip12": "If the QR code isn't scanning, try increasing the screen's brightness (PT-BR)",
    "Tip13": "Information sent via your wallet is trusted by you and your Contacts you interact with (PT-BR)",
    "Tip14": "Even revoked or expired credentials can be usable if the organisation doesn't request for it (PT-BR)",
  },
  "Init": {
    "Retry": "Retry (PT-BR)",
    "Starting": "Starting... (PT-BR)",
    "CheckingAuth": "Checking authentication... (PT-BR)",
    "FetchingPreferences": "Fetching preferences... (PT-BR)",
    "VerifyingOnboarding": "Verifying onboarding... (PT-BR)",
    "GettingCredentials": "Getting wallet credentials... (PT-BR)",
    "RegisteringTransports": "Registering transports... (PT-BR)",
    "InitializingAgent": "Initializing agent... (PT-BR)",
    "ConnectingLedgers": "Connecting to ledgers... (PT-BR)",
    "SettingAgent": "Setting agent... (PT-BR)",
    "Finishing": "Finishing... (PT-BR)",
  },
  "Feedback": {
    "GiveFeedback": "Give Feedback (PT-BR)",
  },
  "PushNotifications": {
    "BulletFour": "new messages (PT-BR)",
    "BulletOne": "new credential offers (PT-BR)",
    "BulletThree": "updates to your credentials (PT-BR)",
    "BulletTwo": "new proof requests (PT-BR)",
    "DeveloperTitle": "Push Notifications (PT-BR)",
    "HeadingOne": "It is recommended you allow this app to receive push notifications. (PT-BR)",
    "HeadingTwo": "Notifications will be sent to you when you receive: (PT-BR)",
    "NotAvailable": " (Not Available) (PT-BR)",
    "Title": "Notifications (PT-BR)",
    "PushNotifications": "Push Notifications (PT-BR)",
    "Continue": "Continue (PT-BR)",
  },
  "AddCredentialSlider": {
    "Choose": "Choose (PT-BR)",
    "ScanQRCode": "Scan a QR code (PT-BR)",
  },
  "Scan": {
    "ScanOnySpecial": "Only special QR codes can be scanned by BC Wallet. (PT-BR)",
    "ScanOnlySpecial3": "BC Wallet currently doesn't support adding digital credential by scanning or taking photos of physical ones. (PT-BR)",
    "WhereToUseLink": "See where you can use BC Wallet (PT-BR)",
    "BadQRCodeDescription": "Ths QR code scanned doesn't work with BC Wallet. BC Wallet only works with participating services.\n\nIt currently can't add digital credentials by taking photos of physical ones. (PT-BR)"
  },
  "RemoteLogging": {
    "ScreenTitle": "Remote Logging (PT-BR)",
    "Paragraph1": "Only turn on remote logging if you are in a debugging session or if you are asked and agree to do so. This action will send logs to Technical Support at the the Government of British Columbia. (PT-BR)",
    "Paragraph2": "Logs are automatically deleted after three days. They are kept and used only for debugging, as outlined in our (PT-BR)",
    "Paragraph3": "Provide the debug session id {sessionId} to technical support. (PT-BR)",
    "CheckBoxTitle": "I understand and wish to enable remote logging (PT-BR)",
    "IAgree": "I Agree (PT-BR)",
    "ButtonTitle": "Turn on remote logging (PT-BR)",
  },
}

export default translation
