// Mock implementations for react-native-bcsc-core module
// Provides jest mock functions for all exported methods

// TODO (bm): we should re-export the actual types / enums from bcsc-core package to avoid duplication
// but Jest is having issues with that currently

export enum TokenType {
  Access = 0,
  Refresh = 1,
  Registration = 2,
}

export enum AccountSecurityMethod {
  PinNoDeviceAuth = 'app_pin_no_device_authn',
  PinWithDeviceAuth = 'app_pin_has_device_authn',
  DeviceAuth = 'device_authentication',
}

export enum BiometricType {
  None = 'none',
  TouchID = 'touchID',
  FaceID = 'faceID',
  OpticID = 'opticID',
}

export enum BCSCCardProcess {
  BCSCPhoto = 'IDIM L3 Remote BCSC Photo Identity Verification',
  BCSCNonPhoto = 'IDIM L3 Remote BCSC Non-Photo Identity Verification',
  NonBCSC = 'IDIM L3 Remote Non-BCSC Identity Verification',
  None = 'N/A',
}

export enum BCSCCardType {
  PhotoCard = 'BC Services Card Photo',
  NonPhotoCard = 'BC Services Card Non-Photo',
  ComboCard = 'BC Services Card Combo',
  NonBcsc = 'N/A',
}

export enum BCSCAccountType {
  PhotoCard = 'BC Services Card with photo',
  NonPhotoCard = 'BC Services Card without photo',
  NoBcscCard = 'Other - no BC Services Card',
}

// Kept in sync with the real `BcscNativeErrorCodes` in packages/bcsc-core/src/index.ts.
// Jest cannot currently re-export the real enum (see TODO above), so it is duplicated here.
export const BcscNativeErrorCodes = {
  // DCR / keychain (E_120_* series)
  TOJSON_METHOD_FAILURE: 'E_120_TOJSON_METHOD_FAILURE',
  TOJSONSTRING_METHOD_FAILURE: 'E_120_TOJSONSTRING_METHOD_FAILURE',
  KEYCHAIN_KEY_EXISTS: 'E_120_KEYCHAIN_KEY_EXISTS_ERROR',
  KEYCHAIN_KEY_DOESNT_EXIST: 'E_120_KEYCHAIN_KEY_DOESNT_EXIST_ERROR',
  KEYCHAIN_KEY_GENERATION_ERROR: 'E_120_KEYCHAIN_KEY_GENERATION_ERROR',
  JWT_DEVICE_INFO_ERROR: 'E_120_JWT_DEVICE_INFO_ERROR',
  KEYCHAIN_UNAVAILABLE: 'E_120_KEYCHAIN_UNAVAILABLE_ERROR',
  // Account / Token
  ACCOUNT_NOT_FOUND: 'E_ACCOUNT_NOT_FOUND',
  INVALID_TOKEN_TYPE: 'E_INVALID_TOKEN_TYPE',
  TOKEN_DELETE_ERROR: 'E_TOKEN_DELETE_ERROR',
  // Key operations
  KEY_NOT_FOUND: 'E_KEY_NOT_FOUND',
  KEY_EXPORT_FAILED: 'E_KEY_EXPORT_FAILED',
  KEY_ERROR: 'E_KEY_ERROR',
  KEYSTORE_UNAVAILABLE: 'E_KEYSTORE_UNAVAILABLE',
  KEYSTORE_ERROR: 'E_KEYSTORE_ERROR',
  // JWT / Signing
  UUID_NOT_FOUND: 'E_UUID_NOT_FOUND',
  NO_KEYS_FOUND: 'E_NO_KEYS_FOUND',
  KEYPAIR_RETRIEVAL_FAILED: 'E_KEYPAIR_RETRIEVAL_FAILED',
  JWT_SIGN_FAILED: 'E_JWT_SIGN_FAILED',
  // PIN
  INVALID_PARAMETERS: 'E_INVALID_PARAMETERS',
  SET_PIN_FAILED: 'E_SET_PIN_FAILED',
  DELETE_PIN_FAILED: 'E_DELETE_PIN_FAILED',
  // Parsing
  JSON_SERIALIZATION_FAILED: 'E_JSON_SERIALIZATION_FAILED',
  FAILED_TO_PARSE_JWS: 'E_FAILED_TO_PARSE_JWS',
} as const

export const isBcscNativeError = jest.fn((error: unknown): boolean => {
  return error instanceof Error && 'code' in error
})

// Issuer Management
export const setIssuer = jest.fn().mockResolvedValue(true)
export const getIssuer = jest.fn().mockResolvedValue(null)

// Key Management
export const getAllKeys = jest.fn().mockResolvedValue([])
export const getKeyPair = jest.fn().mockResolvedValue({
  id: 'test-key',
  public: 'mock-public-key',
  privateKeyAvailable: 'true',
})

// Token Management
export const getToken = jest.fn().mockResolvedValue(null)
export const setToken = jest.fn().mockResolvedValue(true)
export const deleteToken = jest.fn().mockResolvedValue(true)
export const getRegistrationToken = jest.fn().mockResolvedValue(null)

// Account Management
export const setAccount = jest.fn().mockResolvedValue(undefined)
export const getAccount = jest.fn().mockResolvedValue(null)
export const removeAccount = jest.fn().mockResolvedValue(undefined)
export const getDeviceId = jest.fn().mockResolvedValue('mock-device-id')

// Request Body Construction
export const getRefreshTokenRequestBody = jest.fn().mockResolvedValue('mock-request-body')
export const signPairingCode = jest.fn().mockResolvedValue('mock-signature')
export const getDynamicClientRegistrationBody = jest.fn().mockResolvedValue('mock-registration-body')
export const getDeviceCodeRequestBody = jest.fn().mockResolvedValue('mock-device-code-body')

// JWT and Cryptography
export const decodePayload = jest.fn().mockResolvedValue({})
export const createDeviceSignedJWT = jest.fn().mockResolvedValue('mock-jwt')
export const createPreVerificationJWT = jest.fn().mockResolvedValue('mock-pre-verification-jwt')
export const createQuickLoginJWT = jest.fn().mockResolvedValue('mock-quick-login-jwt')
export const hashBase64 = jest.fn().mockResolvedValue('mock-hash')

// PIN Authentication
export const setPIN = jest
  .fn()
  .mockResolvedValue({ success: true, walletKey: 'mock-wallet-key', isAutoGenerated: false })
export const verifyPIN = jest
  .fn()
  .mockResolvedValue({ success: true, locked: false, remainingTime: 0, walletKey: 'mock-wallet-key' })
export const deletePIN = jest.fn().mockResolvedValue(true)
export const hasPINSet = jest.fn().mockResolvedValue(false)

// Device Authentication
export const performDeviceAuthentication = jest.fn().mockResolvedValue(true)
export const canPerformDeviceAuthentication = jest.fn().mockResolvedValue(false)
export const getAvailableBiometricType = jest.fn().mockResolvedValue(BiometricType.None)
export const canPerformBiometricAuthentication = jest.fn().mockResolvedValue(false)

// Account Security Methods
export const setAccountSecurityMethod = jest.fn().mockResolvedValue(true)
export const getAccountSecurityMethod = jest.fn().mockResolvedValue(AccountSecurityMethod.PinNoDeviceAuth)
export const isAccountLocked = jest.fn().mockResolvedValue({ locked: false, remainingTime: 0 })

// Device Security Methods
export const setupDeviceSecurity = jest
  .fn()
  .mockResolvedValue({ success: true, walletKey: 'mock-wallet-key', isAutoGenerated: true })
export const unlockWithDeviceSecurity = jest.fn().mockResolvedValue({ success: true, walletKey: 'mock-wallet-key' })
export const isPINAutoGenerated = jest.fn().mockResolvedValue(false)

// Authorization Request Storage
export const getAuthorizationRequest = jest.fn().mockResolvedValue(null)
export const setAuthorizationRequest = jest.fn().mockResolvedValue(true)
export const deleteAuthorizationRequest = jest.fn().mockResolvedValue(true)

// Account Flags Storage
export const getAccountFlags = jest.fn().mockResolvedValue({})
export const setAccountFlags = jest.fn().mockResolvedValue(true)
export const deleteAccountFlags = jest.fn().mockResolvedValue(true)
export const getMaxDevicesBannerLastDisplayedDate = jest.fn().mockResolvedValue(null)
export const getHideDeviceAuthPrepFlag = jest.fn().mockResolvedValue(false)
export const setHideDeviceAuthPrepFlag = jest.fn().mockResolvedValue(false)
export const setMaxDevicesBannerLastDisplayedDate = jest.fn().mockResolvedValue(false)
// Evidence Storage
export const getEvidence = jest.fn().mockResolvedValue([])
export const setEvidence = jest.fn().mockResolvedValue(true)
export const deleteEvidence = jest.fn().mockResolvedValue(true)
export const saveEvidencePhoto = jest.fn().mockResolvedValue('/mock/path/to/photo.jpg')

// Saved Services Storage
export const getSavedServices = jest.fn().mockResolvedValue([])
export const setSavedServices = jest.fn().mockResolvedValue(true)
export const deleteSavedServices = jest.fn().mockResolvedValue(true)

// Credential Management
export const setCredential = jest.fn().mockResolvedValue(undefined)
export const getCredential = jest.fn().mockResolvedValue(null)
export const deleteCredential = jest.fn().mockResolvedValue(undefined)
export const hasCredential = jest.fn().mockResolvedValue(false)
