// Mock implementations for react-native-bcsc-core module
// Provides jest mock functions for all exported methods

// Enums
export enum TokenType {
  Access = 0,
  Refresh = 1,
  Registration = 2,
}

export enum AccountSecurityMethod {
  PinNoDeviceAuth = 'app_pin_no_device_authn',
  PinWithDeviceAuth = 'app_pin_has_device_authn',
  DeviceAuth = 'device_authentication',
}

export enum BiometricType {
  None = 'none',
  TouchID = 'touchID',
  FaceID = 'faceID',
  OpticID = 'opticID',
}

// Key Management
export const getAllKeys = jest.fn().mockResolvedValue([])
export const getKeyPair = jest.fn().mockResolvedValue({
  id: 'test-key',
  public: 'mock-public-key',
  privateKeyAvailable: 'true',
})

// Token Management
export const getToken = jest.fn().mockResolvedValue(null)
export const setToken = jest.fn().mockResolvedValue(true)
export const deleteToken = jest.fn().mockResolvedValue(true)
export const getRegistrationToken = jest.fn().mockResolvedValue(null)

// Account Management
export const setAccount = jest.fn().mockResolvedValue(undefined)
export const getAccount = jest.fn().mockResolvedValue(null)
export const removeAccount = jest.fn().mockResolvedValue(undefined)
export const getDeviceId = jest.fn().mockResolvedValue('mock-device-id')

// Request Body Construction
export const getRefreshTokenRequestBody = jest.fn().mockResolvedValue('mock-request-body')
export const signPairingCode = jest.fn().mockResolvedValue('mock-signature')
export const getDynamicClientRegistrationBody = jest.fn().mockResolvedValue('mock-registration-body')
export const getDeviceCodeRequestBody = jest.fn().mockResolvedValue('mock-device-code-body')

// JWT and Cryptography
export const decodePayload = jest.fn().mockResolvedValue({})
export const createDeviceSignedJWT = jest.fn().mockResolvedValue('mock-jwt')
export const createPreVerificationJWT = jest.fn().mockResolvedValue('mock-pre-verification-jwt')
export const createQuickLoginJWT = jest.fn().mockResolvedValue('mock-quick-login-jwt')
export const hashBase64 = jest.fn().mockResolvedValue('mock-hash')

// PIN Authentication
export const setPIN = jest
  .fn()
  .mockResolvedValue({ success: true, walletKey: 'mock-wallet-key', isAutoGenerated: false })
export const verifyPIN = jest
  .fn()
  .mockResolvedValue({ success: true, locked: false, remainingTime: 0, walletKey: 'mock-wallet-key' })
export const deletePIN = jest.fn().mockResolvedValue(true)
export const hasPINSet = jest.fn().mockResolvedValue(false)

// Device Authentication
export const performDeviceAuthentication = jest.fn().mockResolvedValue(true)
export const canPerformDeviceAuthentication = jest.fn().mockResolvedValue(false)
export const getAvailableBiometricType = jest.fn().mockResolvedValue(BiometricType.None)
export const canPerformBiometricAuthentication = jest.fn().mockResolvedValue(false)

// Account Security Methods
export const setAccountSecurityMethod = jest.fn().mockResolvedValue(true)
export const getAccountSecurityMethod = jest.fn().mockResolvedValue(AccountSecurityMethod.PinNoDeviceAuth)
export const isAccountLocked = jest.fn().mockResolvedValue({ locked: false, remainingTime: 0 })
export const getBestAvailableAccountSecurityMethod = jest.fn().mockResolvedValue(AccountSecurityMethod.PinNoDeviceAuth)

// Device Security Methods
export const setupDeviceSecurity = jest
  .fn()
  .mockResolvedValue({ success: true, walletKey: 'mock-wallet-key', isAutoGenerated: true })
export const unlockWithDeviceSecurity = jest.fn().mockResolvedValue({ success: true, walletKey: 'mock-wallet-key' })
export const isPINAutoGenerated = jest.fn().mockResolvedValue(false)

// Authorization Request Storage
export const getAuthorizationRequest = jest.fn().mockResolvedValue(null)
export const setAuthorizationRequest = jest.fn().mockResolvedValue(true)
export const deleteAuthorizationRequest = jest.fn().mockResolvedValue(true)

// Account Flags Storage
export const getAccountFlags = jest.fn().mockResolvedValue({})
export const setAccountFlags = jest.fn().mockResolvedValue(true)
export const deleteAccountFlags = jest.fn().mockResolvedValue(true)

// Evidence Metadata Storage
export const getEvidenceMetadata = jest.fn().mockResolvedValue([])
export const setEvidenceMetadata = jest.fn().mockResolvedValue(true)
export const deleteEvidenceMetadata = jest.fn().mockResolvedValue(true)

// Credential Management
export const setCredential = jest.fn().mockResolvedValue(undefined)
export const getCredential = jest.fn().mockResolvedValue(null)
export const deleteCredential = jest.fn().mockResolvedValue(undefined)
export const hasCredential = jest.fn().mockResolvedValue(false)
