// Alert interaction types (display, action ie: 'OK' button pressed)
export enum AlertInteractionEvent {
  ALERT_DISPLAY = 'alert_display',
  ALERT_ACTION = 'alert_action',
}

/**
 * App event codes
 *
 * Includes:
 *    - Alert events
 *    - Error events
 */
export enum AppEventCode {
  GENERAL = 'general',
  ADD_CARD_CAMERA_BROKEN = 'add_card_camera_broken',
  ADD_CARD_DYNAMIC_REGISTRATION = 'add_card_dynamic_registration', //being tracked
  ADD_CARD_INCORRECT_OS = 'add_card_incorrect_os',
  ADD_CARD_KEYPAIR_GENERATION = 'add_card_keypair_generation',
  ADD_CARD_PIN_STORE = 'add_card_pin_store',
  ADD_CARD_PROVIDER = 'add_card_provider',
  ADD_CARD_SERVER_CONFIGURATION = 'add_card_server_configuration',
  ADD_CARD_SERVER_ERROR = 'add_card_server_error',
  ADD_CARD_TERMS_OF_USE = 'add_card_terms_of_use',
  ADD_CARD_DYNAMIC_REGISTRATION_APPVERSION_NOT_SUPPORTED = 'add_card_dynamic_registration_appversion_not_supported',
  ANDROID_APP_UPDATE_REQUIRED = 'android_app_update_required',
  ANDROID_DEVICE_PROTECTION_REQUIRED = 'android_device_protection_required',
  CARD_EXPIRED_WILL_REMOVE = 'card_expired_will_remove',
  CARD_STATUS_ADDITIONAL_CARD = 'card_status_additional_card',
  CARD_STATUS_CANCELLED = 'card_status_cancelled',
  CARD_STATUS_CANCELLED_BY_USER = 'card_status_cancelled_by_user',
  CARD_STATUS_EXPIRED = 'card_status_expired',
  CARD_STATUS_REMOVED = 'card_status_removed',
  CARD_STATUS_UPDATED = 'card_status_updated',
  CARD_TYPE_CHANGED = 'card_type_changed',
  CLOCK_SKEW_ERROR = 'clock_skew_error',
  DATA_USE_WARNING = 'data_use_warning',
  EVIDENCE_UPLOAD_SERVER_ERROR = 'evidence_upload_server_error',
  EVIDENCE_UPLOAD_UNKNOWN_ERROR = 'evidence_upload_unknown_error',
  INVALID_PAIRING_CODE = 'invalid_pairing_code',
  INVALID_TOKEN = 'invalid_token',
  IN_CALL_HAVING_TROUBLE = 'in_call_having_trouble',
  IOS_APP_UPDATE_REQUIRED = 'ios_app_update_required',
  IOS_DEVICE_PROTECTION_REQUIRED = 'ios_device_protection_required',
  LOGIN_PARSE_URI = 'login_parse_uri',
  LOGIN_REJECTED_400 = 'login_rejected_400',
  LOGIN_REJECTED_401 = 'login_rejected_401',
  LOGIN_REJECTED_403 = 'login_rejected_403',
  LOGIN_REMEMBERED_DEVICE_INVALID_PAIRING_CODE = 'login_remembered_device_invalid_pairing_code',
  LOGIN_SAME_DEVICE_INVALID_PAIRING_CODE = 'login_same_device_invalid_pairing_code',
  LOGIN_SERVER_ERROR = 'login_server_error',
  NO_INTERNET = 'no_internet',
  NO_TOKENS_RETURNED = 'no_tokens_returned',
  PHYSICAL_CARD_WILL_EXPIRE = 'physical_card_will_expire',
  PROBLEM_WITH_CONNECTION = 'problem_with_connection',
  SERVER_ERROR = 'server_error',
  SERVER_TIMEOUT = 'server_timeout',
  UNSECURED_NETWORK = 'unsecured_network',
  USER_INPUT_BIRTHDATE_EMPTY = 'user_input_birthdate_empty',
  USER_INPUT_CSN_EMPTY = 'user_input_csn_empty',
  USER_INPUT_EXPIRED_VERIFY_REQUEST = 'user_input_expired_verify_request',
  USER_INPUT_INVALID_CSN = 'user_input_invalid_csn',
  USER_INPUT_PAIRING_CODE_EMPTY = 'user_input_pairing_code_empty',
  VALID_CREDENTIAL_EMPTY_KEYCHAIN = 'valid_credential_empty_keychain',
  VERIFY_NOT_COMPLETE = 'verify_not_complete',
  VERIFY_COMPLETE_FEEDBACK = 'verify_complete_feedback',
  ERR_100_FAILED_TO_WRITE_LOCAL_STORAGE = 'err_100_failed_to_write_local_storage',
  ERR_101_FAILED_TO_READ_LOCAL_STORAGE = 'err_101_failed_to_read_local_storage',
  ERR_102_CLIENT_REGISTRATION_UNEXPECTEDLY_NULL = 'err_102_client_registration_unexpectedly_null',
  ERR_103_AUTHORIZATION_REQUEST_UNEXPECTEDLY_NULL = 'err_103_authorization_request_unexpectedly_null',
  ERR_104_CREDENTIAL_UNEXPECTEDLY_NULL = 'err_104_credential_unexpectedly_null',
  ERR_105_UNABLE_TO_DECRYPT_AND_VERIFY_ID_TOKEN = 'err_105_unable_to_decrypt_and_verify_id_token',
  ERR_106_UNABLE_TO_DESERIALIZE_ID_TOKEN = 'err_106_unable_to_deserialize_id_token',
  ERR_107_UNABLE_TO_PARSE_JWT_TOKENS = 'err_107_unable_to_parse_jwt_tokens',
  ERR_108_UNABLE_TO_DELETE_KEY_PAIR = 'err_108_unable_to_delete_key_pair',
  ERR_109_FAILED_TO_DESERIALIZE_JSON = 'err_109_failed_to_deserialize_json', //being tracked
  ERR_110_UNABLE_TO_DECRYPT_JWE = 'err_110_unable_to_decrypt_jwe',
  ERR_111_UNABLE_TO_VERIFY_MISSING_JWK = 'err_111_unable_to_verify_missing_jwk',
  ERR_112_JWS_VERIFICATION_FAILED = 'err_112_jws_verification_failed',
  ERR_113_UNABLE_TO_VERIFY_JOSE_EXCEPTION = 'err_113_unable_to_verify_jose_exception',
  ERR_114_FAILED_TO_GET_CLAIMS_SET_AFTER_DECRYPT_AND_VERIFY = 'err_114_failed_to_get_claims_set_after_decrypt_and_verify',
  ERR_115_VIDEO_SERVICE_HOURS_UNEXPECTEDLY_NULL = 'err_115_video_service_hours_unexpectedly_null', //being tracked
  ERR_115_FAILED_TO_SERIALIZE_JSON = 'err_115_failed_to_serialize_json',
  ERR_116_VIDEO_CAPTURE_ERROR = 'err_116_video_capture_error',
  ERR_116_PROVIDER_UNEXPECTEDLY_NULL = 'err_116_provider_unexpectedly_null',
  ERR_117_FAILED_TO_PARSE_JWS = 'err_117_failed_to_parse_jws',
  ERR_118_FAILED_TO_RETRIEVE_TOKEN_EXPIRY = 'err_118_failed_to_retrieve_token_expiry',
  ERR_119_TOKEN_UNEXPECTEDLY_NULL = 'err_119_token_unexpectedly_null',
  ERR_120_CLIENT_REGISTRATION_FAILURE = 'err_120_client_registration_failure',
  ERR_120_TOJSON_METHOD_FAILURE = 'err_120_tojson_method_failure',
  ERR_120_TOJSONSTRING_METHOD_FAILURE = 'err_120_tojsonstring_method_failure',
  ERR_120_KEYCHAIN_KEY_EXISTS_ERROR = 'err_120_keychain_key_exists_error',
  ERR_120_KEYCHAIN_KEY_DOESNT_EXIST_ERROR = 'err_120_keychain_key_doesnt_exist_error',
  ERR_120_KEYCHAIN_KEY_GENERATION_ERROR = 'err_120_keychain_key_generation_error',
  ERR_120_JWT_DEVICE_INFO_ERROR = 'err_120_jwt_device_info_error',
  ERR_206_MISSING_OR_NULL_VALUES_IN_JSON_RESPONSE = 'err_206_missing_or_null_values_in_json_response', //being tracked
  ERR_207_UNABLE_TO_SIGN_CLAIMS_SET = 'err_207_unable_to_sign_claims_set',
  ERR_208_UNEXPECTED_NETWORK_CALL_EXCEPTION = 'err_208_unexpected_network_call_exception', //being tracked
  ERR_209_BAD_REQUEST = 'err_209_bad_request',
  ERR_210_UNAUTHORIZED = 'err_210_unauthorized',
  ERR_212_RETRY_LATER = 'err_212_retry_later',
  ERR_211_SERVER_OUTAGE = 'err_211_server_outage',
  ERR_213_FAILED_CREATING_CLIENT_REGISTRATION = 'err_213_failed_creating_client_registration',
  ERR_299_KEYS_OUT_OF_SYNC = 'err_299_keys_out_of_sync', //being tracked
  ERR_221_FETCHED_PROVIDER_NULL_EXCEPTION = 'err_221_fetched_provider_null_exception',
  ERR_400_FAILED_TO_RETRIEVE_STRING_RESOURCE = 'err_400_failed_to_retrieve_string_resource',
  ERR_300_EMPTY_RESPONSE = 'err_300_empty_response',
  ERR_500_INVALID_URL = 'err_500_invalid_url',
  ERR_501_INVALID_REGISTRATION_REQUEST = 'err_501_invalid_registration_request',
  RATE_IN_APP_STORE = 'rate_in_app_store',
  VOLUME_TOO_LOW = 'volume_too_low',
  CANCEL_PENDING_BACKCHECK_VERIFICATION = 'cancel_pending_backcheck_verification',
  INCOMPLETE_REMOTE_VERIFICATION = 'incomplete_remote_verification',
  CONFIRM_CANCEL_MOBILE_CARD_SETUP = 'confirm_cancel_mobile_card_setup',
  TOO_MANY_ATTEMPTS = 'too_many_attempts',
  INVALID_QR_CODE = 'invalid_qr_code',
  NON_BCSC_ACCEPT_CONDITIONS = 'non_bcsc_accept_conditions',
  NON_BCSC_HAS_BEEN_DISABLED = 'non_bcsc_has_been_disabled',
  DELETE_VERIFY_REQUEST_ERROR = 'delete_verify_request_error',
  VERIFY_STEPS_INCOMPLETE = 'verify_steps_incomplete',
  CONFIRM_TO_CONTINUE = 'confirm_to_continue',
  INFORMATION_REQUIRED = 'information_required',
  APP_SETUP_NOT_COMPLETE = 'app_setup_not_complete',
  NEW_UPDATE_AVAILABLE = 'new_update_available',
  EMAIL_ADDRESS_EMPTY = 'email_address_empty',
  EMAIL_VERIFICATION_CODE_EMPTY = 'email_verification_code_empty',
  EMAIL_VERIFICATION_CODE_INVALID = 'email_verification_code_invalid',
  EMAIL_ADDRESS_INVALID = 'email_address_invalid',
  CONFIRM_SKIP_EMAIL_ADDRESS = 'confirm_skip_email_address',
  FILE_UPLOAD_ERROR = 'file_upload_error',
  NO_DOCUMENT_NUMBER_ENTERED_ERROR = 'no_document_number_entered_error',
  VIDEO_VERIFY_NOT_COMPLETE = 'video_verify_not_complete',
  REMOVE_UNVERIFIED_CARD = 'remove_unverified_card',
  REMOVE_VERIFIED_CARD = 'remove_verified_card',
  ALREADY_VERIFIED = 'already_verified',
  IGNORED = 'ignored',
  BETA_FEEDBACK_PROMPT_IOS = 'beta_feedback_prompt_ios',
  CANCEL_VERIFICATION_REQUEST = 'cancel_verification_request',
  REMOTE_VERIFICATION_PENDING = 'remote_verification_pending',
  CANCEL_MOBILE_CARD_SETUP = 'cancel_mobile_card_setup',
  NON_BCSC_WAS_DISABLED = 'non_bcsc_was_disabled',
  TOO_MANY_ACTIVE_ACCOUNTS = 'too_many_active_accounts',
  DEVICE_AUTHORIZATION_ERROR = 'device_authorization_error',
  // Wallet/Agent Errors
  STATE_LOAD_ERROR = 'state_load_error',
  AGENT_INITIALIZATION_ERROR = 'agent_initialization_error',
  WALLET_SECRET_NOT_FOUND = 'wallet_secret_not_found',
  // BCID/Connection Errors
  PARSE_INVITATION_ERROR = 'parse_invitation_error',
  RECEIVE_INVITATION_ERROR = 'receive_invitation_error',
  LEGACY_DID_ERROR = 'legacy_did_error',
  APP_TO_APP_URL_ERROR = 'app_to_app_url_error',
  SERVICE_CARD_AUTH_ERROR = 'service_card_auth_error',
  // Attestation Errors
  ATTESTATION_BAD_INVITATION = 'attestation_bad_invitation',
  ATTESTATION_CONNECTION_ERROR = 'attestation_connection_error',
  ATTESTATION_NONCE_ERROR = 'attestation_nonce_error',
  ATTESTATION_GENERATION_ERROR = 'attestation_generation_error',
  ATTESTATION_VALIDATION_ERROR = 'attestation_validation_error',
  ATTESTATION_AGENT_UNDEFINED = 'attestation_agent_undefined',
  ATTESTATION_INTEGRITY_UNAVAILABLE = 'attestation_integrity_unavailable',
  ATTESTATION_GENERAL_PROOF_ERROR = 'attestation_general_proof_error',
  ATTESTATION_REQUEST_ERROR = 'attestation_request_error',
  ATTESTATION_UNSUPPORTED_PLATFORM = 'attestation_unsupported_platform',
}
