name: AMTH AATH integration Test

on:
  workflow_dispatch:

jobs:
  run-on-device-ios-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - name: run-aath-agents
        uses: ./.github/workflows/actions/run-aath-agents

      - name: Fetch mobile test harness repo
        uses: actions/checkout@v2
        with:
          repository: hyperledger/aries-mobile-test-harness
          path: aries-mobile-test-harness
          ref: main

      - name: Run iOS SauceLabs smoke-test
        uses: ./.github/workflows/actions/run-test-harness
        env:
          LEDGER_URL_CONFIG: "http://test.bcovrin.vonx.io"
          REGION: "us-west-1"
        with:
          MOBILE_WALLET: "-w bc_wallet"
          ISSUER_AGENT: '-i "AATH;http://0.0.0.0:9020"'
          VERIFIER_AGENT: '-v "AATH;http://0.0.0.0:9030"'
          DEVICE_CLOUD: "-d SauceLabs"
          DEVICE_CLOUD_USER: "-u ${{ secrets.SAUCE_USERNAME }}"
          DEVICE_CLOUD_KEY: "-k ${{ secrets.SAUCE_ACCESS_KEY }}"
          MOBILE_PLATFORM: "-p iOS"
          APP_FILE_NAME: "-a AriesBifold-127.ipa"
          TEST_SCOPE: "-t @bc_wallet -t ~@wip"
          REPORT_PROJECT: ios-one-device-smoke
        continue-on-error: true

      - name: Upload iOS smoke-test results to Allure
        uses: ./.github/workflows/actions/run-send-gen-test-results-secure
        with:
          REPORT_PROJECT: ios-one-device-smoke
          ADMIN_USER: ${{ secrets.ALLURE_USERNAME }}
          ADMIN_PW: ${{ secrets.ALLURE_PASSWD }}

  run-on-device-android-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - name: run-aath-agents
        uses: ./.github/workflows/actions/run-aath-agents

      - name: Fetch mobile test harness repo
        uses: actions/checkout@v2
        with:
          repository: hyperledger/aries-mobile-test-harness
          path: aries-mobile-test-harness
          ref: main

      - name: Run Android SauceLabs smoke-test
        uses: ./.github/workflows/actions/run-test-harness
        env:
          LEDGER_URL_CONFIG: "http://test.bcovrin.vonx.io"
          REGION: "us-west-1"
        with:
          MOBILE_WALLET: "-w bc_wallet"
          ISSUER_AGENT: '-i "AATH;http://0.0.0.0:9020"'
          VERIFIER_AGENT: '-v "AATH;http://0.0.0.0:9030"'
          DEVICE_CLOUD: "-d SauceLabs"
          DEVICE_CLOUD_USER: "-u ${{ secrets.SAUCE_USERNAME }}"
          DEVICE_CLOUD_KEY: "-k ${{ secrets.SAUCE_ACCESS_KEY }}"
          MOBILE_PLATFORM: "-p Android"
          APP_FILE_NAME: "-a AriesBifold-127.aab"
          TEST_SCOPE: "-t @bc_wallet -t ~@wip"
          REPORT_PROJECT: android-one-device-smoke
        continue-on-error: true

      - name: Upload Android smoke-test results to Allure
        uses: ./.github/workflows/actions/run-send-gen-test-results-secure
        with:
          REPORT_PROJECT: android-one-device-smoke
          ADMIN_USER: ${{ secrets.ALLURE_USERNAME }}
          ADMIN_PW: ${{ secrets.ALLURE_PASSWD }}
